### ISSUE TITLE
Sensor 

### ISSUE THREAD

**Issue by kweebix** [saniho/apiEnedis#10]
Peut tu faire en sorte que plusieurs sensor soient créé pour détaillé si on veut faire plusieurs card ?

**Comment by saniho** [comment]
hello @kweebix ,peux-tu préciser ton besoin ? car normalement les card on accès aux attributs du sensor, donc tu peux récupérer les elements..

**Comment by kweebix** [comment]
J'aimerais faire un graphique avec le prix HC+HP(graphique 1) et consommation HC(graphique 2) et consommation HP (graphique 3)

**Comment by saniho** [comment]
à mon avis, on doit pouvoir s'en sortir avec la card mini-graph-card, par contre à ce jour, pas d'accès aux attributes, mais il y a une merge request en attente, donc peut-etre attendre de voir ce que cela donne
https://github.com/kalkih/mini-graph-card/pull/501

**Comment by kweebix** [comment]
Oui j'utilise déjà cette card, mais voilà elle peut que utiliser un sensor pour l'instant si elle peut utiliser les attribue t'en mieux

**Comment by saniho** [comment]
la dernier version alpha integre un nouveau sensor pour le prix de la veille, dis moi ce que tu en penses
1.1.1.0alpha1

**Comment by kweebix** [comment]
Actuellement il est à 0€ mais bizarrement sur ta cart tout fonctionne bien

**Comment by kweebix** [comment]
Ça fait maintenant plusieurs jour et tout fonctionne parfaitement merci pour ça, j'ai pu intégrer un graphique à la carte
![Screenshot_20210106-095733.jpg](https://user-images.githubusercontent.com/12646272/103749298-a0564900-5005-11eb-8b55-01f8c664f04f.jpg)

**Comment by saniho** [comment]
la derniere version  v1.1.1.0 règle ce soucis de valeur à zéro
