### ISSUE TITLE
extra keys not allowed @ data['currency']. Got '€'

### ISSUE THREAD

**Issue by trandbert37** [saniho/apiEnedis#107]
Bonjour,
J'essaie d'ajouter ma consommation dans la partie énergie de Home Assistant mais j'ai cette erreur :

extra keys not allowed @ data['currency']. Got '€'

Est-ce que je fais quelque chose pas correctement ?

J'utilise la dernière beta de cette intégration  avec la dernière version de Home Assistant.
![Screenshot_20220104-002851__01.jpg](https://user-images.githubusercontent.com/16879382/147991761-cffffdaa-241c-4f7f-b004-792813f85688.jpg)

Merci d'avance pour votre aide !
Alex

**Comment by saniho** [comment]
utilises-tu la derniere version ?

**Comment by trandbert37** [comment]
Oui, j'ai mis que j'utilise la dernière version

**Comment by saniho** [comment]
J'ai refais le test sur mon installation, et je n'ai pas cette erreur, peux-tu me copier le contenu de ton instance : 
sensor.myenedis_energy_xxxx

**Comment by trandbert37** [comment]
Salut, voici ce que j'ai:
![image](https://user-images.githubusercontent.com/16879382/148193732-4854b513-dd80-4938-966a-db2151ad2b4e.png)

**Comment by saniho** [comment]
comment fais-tu la config, appli homeassistant mobile ou site web ?
Si tu ne le fais pas via le site web, peux-tu essayer ?

**Comment by trandbert37** [comment]
J'ai essayé sur les deux et c'est pareil

**Comment by saniho** [comment]
est-ce que d'autres on le meme soucis  ?

**Comment by trandbert37** [comment]
J'ai réinstallé l'intégration j'ai regénéré un token sur la passerelle et c'est toujours pareil

**Comment by saniho** [comment]
@trandbert37 , sur ton entité, elle n'est jamais remplie, tu as toujours zéro ?


> Salut, voici ce que j'ai:
> ![image](https://user-images.githubusercontent.com/16879382/148193732-4854b513-dd80-4938-966a-db2151ad2b4e.png)

car moi, j'ai ceci : 
![image](https://user-images.githubusercontent.com/52693545/148838120-64da225c-5ca9-4176-9fe1-749cfb0647d7.png)

**Comment by trandbert37** [comment]
Maintenant, j'ai bien un état différent de 0 mais j'ai toujours le même problème lors de l'ajout dans la partie "énergie"

**Comment by trandbert37** [comment]
Je viens de me rendre compte que le problème est peut-être ici: 
![image](https://user-images.githubusercontent.com/16879382/148921783-e5bc1d19-032a-48f2-8ee0-5bd906b91a14.png)

**Comment by saniho** [comment]
je ne pense pas .. car cette entité n'a pas de lié avec l'autre...
Peut-etre pourrais-tu ouvrir un ticket sur le forum principal homeassistant version englaise, ils nous aideront peut-etre ?

**Comment by saniho** [comment]
j'ai trouvé le problème( € au lieu de EUR ) et j'en ai profité pour créé deux sensors hour pour Energy que vous pouvez intégrer..
La version est en pre-release

**Comment by trandbert37** [comment]
De mon côté, j'ai toujours la même erreur même en installant la version pre release..
