### ISSUE TITLE
Plus d'un mois sans aucun accès

### ISSUE THREAD

**Issue by Manox35** [saniho/apiEnedis#109]
J'ai tout essayé, réinstallé, etc toujours le même résultat.
Mon token est bon, le PDL est bon, la collecte des données est active mais rien n'y fait

Si quelqu'un a le même problème ?
![enedis](https://user-images.githubusercontent.com/76265804/149150468-2956aa66-264a-4dda-be22-1aca7da74be6.jpg)

**Comment by philuxe** [comment]
Pareil ici

**Comment by jacme31** [comment]
Pareil pour moi .  Ci joint une log HA . J'ai modifié mon n°PDL par numeroPDL
[test.log](https://github.com/saniho/apiEnedis/files/7861303/test.log)

**Comment by Manox35** [comment]
>

**Comment by Manox35** [comment]
> Pareil pour moi . Ci joint une log HA . J'ai modifié mon n°PDL par numeroPDL [test.log](https://github.com/saniho/apiEnedis/files/7861303/test.log)
Bonjour,

et du coup ca marche ou pas ?
Dans quel fichier as tu fait les modifications ?

**Comment by jacme31** [comment]
La trace est destinée au développeur, si j'ai modifié mon PDL dans le fichier c'est juste pour mettre sous github une trace sans trop de données personnelles ...

**Comment by saniho** [comment]
Attention le sujet était clos par erreur, j ai reouvert ;)
Pour le soucis, si quelqu'un peut partager son privé son token et pdl je jetterai un œil.

**Comment by Manox35** [comment]
> Attention le sujet était clos par erreur, j ai reouvert ;) Pour le soucis, si quelqu'un peut partager son privé son token et pdl je jetterai un œil.

Quel est ton adresse email ? je t'enverrai mon token et mon pdl

**Comment by saniho** [comment]
La voici : sanihogithub@gmail.com

**Comment by saniho** [comment]
merci @Manox35 , j'ai passé au  debug l'appel, et le retour est : 
{'usage_point_id': 'xxx', 'error': 'token_refresh_401', 'description': 'Une erreur est survenue, merci de renouveller vos consentements.', 'user_alert': True}
donc certainement un soucis au niveau consentement du partage de donnée .. à mon avis, il faut tenté de refaire un consentement surla plateforme https://enedisgateway.tech/ et retenter avec le nouveau token qui te sera fournit.

**Comment by Skuair** [comment]
Bonjour, j'avais ouvert une issue tout récemment sur le même souci. J'ai effectivement renouvelé les consentements et des données sont revenues.
Par contre pour mon cas, tout n'est pas complétement revenu : la valeur principale "Yesterday" vaut toujours 0 alors que les autres comme YesterdayMaxPower ou les conso mois précédent sont remplies.
Je ne sais pas si c'est côté enedis ou intégration mais cette fois aucun log ni erreur.

**Comment by Frankster-NL** [comment]
Am having the exact same issue. Tried to renew the credentials multiple times, but result is always the same.

Running the mentioned query (curl -X POST https://enedisgateway.tech/api -H 'Authorization: TOKEN' -H 'Content-Type: application/json' -d '{"type": "consumption_load_curve","usage_point_id": "METERNUMBER","start": "2022-01-14","end": "2022-01-15"}'

Results in "{"tag":"enedis_return_ko","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}"

**Comment by Manox35** [comment]
Merci de votre retour mais le problème c'est que j'ai déjà fait ça une
bonne dizaine de fois

**Comment by saniho** [comment]
malheureusement pas trop d'idée, il faudrait prendre contact avec @M4dm4rtig4n, qui est l'auteur de la passerelle avec Enedis, il aura peut-etre une idée...

**Comment by m4dm4rtig4n** [comment]
Plait il ? 

Je peut essayer de jeter un oeil dans les log de la passerelle pour voir ce qui ce passe si besoin :)
Par contre j'ai besoin de vos PDL, go sur le Discord en lien et go m'envoyer vos PDL en privé ou par mail (m4dm4rtig4n@gmail.com)

**Comment by saniho** [comment]
est-ce que vous avez toujours le probleme ?

**Comment by Manox35** [comment]
Non apparemment ça fonctionne mieux.
