### ISSUE TITLE
Module énergie HA

### ISSUE THREAD

**Issue by Skuair** [saniho/apiEnedis#110]
Bonjour,

Je ne suis pas sûr de comprendre si cette intégration est compatible avec le module Energy ?
D'après les release notes, il semble que ça soit le cas depuis les versions 1.3.X mais dans ce cas je n'ai pas compris comment il fallait l'utiliser.
Quand je rentre dans le module Energy, je dois sélectionner l'entité statistiques, sauf que je n'ai rien dans la liste. J'ai loupé quelque chose ? Pourtant je vois bien dans les entités de l'intégration une nommée myenedis.energy.xxxxx qui a une valeur correspondant à la conso du mois actuelle.

**Comment by najie** [comment]
Pareil de mon côté, il semblerait que les entités ne soient pas correctement déclarées comme indiqué ici: https://www.home-assistant.io/more-info/statistics/

**Comment by saniho** [comment]
@najie , @Skuair , essayé avec la pre release : 1.4.0.1 .. cela devrait être mieux....

**Comment by najie** [comment]
Effectivement ça m'a l'air bon, merci bbeaucoup !

**Comment by Skuair** [comment]
Je ne retrouve plus comment dans HA on passe sur le canal beta pour mettre à jour l'intégration ?
