### ISSUE TITLE
Bug remontés conso

### ISSUE THREAD

**Issue by aardjoun** [saniho/apiEnedis#116]
Bonjour, depuis quelques jours j'ai de gros écarts de remontés de consommation. Un jour j'ai 0 puis le lendemain la bonne consommation. HA faisant la différence, je me retrouve avec des conso négatives. Est-ce normal ? Merci
![image](https://user-images.githubusercontent.com/5985672/151171798-35a2f15d-fb8a-4149-af50-55b076eebc7b.jpeg)

**Comment by fabiencharrasse** [comment]
Bonjour,

Même chose de mon côté mais ça a toujours été un peu aléatoire depuis que j'ai installé le plugin (29 décembre 2021)
Je viens également de me rendre compte que cette vue "énergie" est décalée d'un jour (la donnée du jour correspond à celle d'hier)

Les données remontées par la carte linky (https://github.com/saniho/content-card-linky) sont les bonnes (vérifié avec les données disponibles sur le site d'Enedis.) 

![image](https://user-images.githubusercontent.com/86050782/151190858-b8ce4117-092a-4f16-b840-19119019a870.png)

**Comment by WarC0zes** [comment]
>  Je viens également de me rendre compte que cette vue "énergie" est décalée d'un jour (la donnée du jour correspond à celle d'hier)
> 
C'est normal, c'est pas en temps réelle les remontés, ta 1 jour de décalage.

Sinon moi aussi j'ai des bug identique, j'ai remarqué que quand on reboot ca fausse les données dans le panneau énergie.
Le soucis c'est le serveur enedis qui est pas stable et si pas de remonté un jours ca fausse les donnée et fait de la consommation négative.

**Comment by fabiencharrasse** [comment]
> C'est normal, c'est pas en temps réelle les remontés, ta 1 jour de décalage.
Je comprend que ça ne soit pas en direct, mais l'affichage devrait indiquer le 25 et non le 26 (et donc la barre décalée d'un cran à gauche.)
![image](https://user-images.githubusercontent.com/86050782/151211298-955dd99e-b024-4012-a2cd-949d786ae00b.png)

**Comment by mdeweerd** [comment]
Le problème c'est que les barres de l'énergie consommé sont déterminés par HA toutes les heures d'après les valeurs d'état.  Il faudrait demander (ou soutenir la demande) de faire de sorte que la valeur de comptage puisse être associé à un horodatage et qu'HA fasse de sorte que le suivi énergétique le prenne en compte.

**Comment by fabiencharrasse** [comment]
Merci pour l'info ! Un lien existe il pour soutenir la demande ?

**Comment by mdeweerd** [comment]
Je n'ai pas regardé s'il y a une demande.  Donc s'il n'y en a pas, il faudrait la faire...
