### ISSUE TITLE
Vérification locale du code - Makefile

### ISSUE THREAD

**Issue by mdeweerd** [saniho/apiEnedis#118]
@saniho 

J'ai ajouté à dev un Makefile + les modifications de code minimales pour faire passer les vérifications diverses tel que celles de mypy .

En lancant make, d'autres modifications automatiques de code s'appliqueront.
J'ai évité d'en faire le commit moi-même pour que les modifications 'limite' fonctionnelles resortent mieux.

**Comment by Djailla** [comment]
Hello, j'ai un peu de temps pour donner un coup de main, on procède comment, faire tourner la CI sur la branch dev déjà ?

**Comment by Djailla** [comment]
Quelques petits points remontés :
- Il faudrait rajouter une règle dans le Makefile pour ignorer les vend
- Il faudrait faire tourner `autoflake` pour supprimer les imports inutilisés
- Est ce que ça ne vaudrait pas le coup de mettre le contenu du Makefile dans un fichier tox.ini ?

**Comment by mdeweerd** [comment]
Je ne connais pas encore tout l'ecosystème Python, et je n'ai pas réussi rapidement à mettre en place tox.  Du coup j'ai fait avec make - je connais mieux et c'est facile de transformer l'action github en un make. 

Perso je suis preneur pour tox.

- Que veux tu dire par "vend'.
- Je crois que le CI tourne sur toute branche suite à un push.
- Imports inutilisés: je crois qu'il y a des amélioriations à faire pour les tests aussi à ce propos.
- autoflake8 ajouté au Makefile (je n'ai pas poussé les modifs automatiques des fichiers).

**Comment by saniho** [comment]
@Djailla  : si tu veux participer, je peux te rajouter dans le projet

**Comment by Djailla** [comment]
Si tu préfères faire des Pull Requests ? Je veux bien participer, mais je ne veux pas tout casser ! Il faut que je me penche sur comment tester en local

**Comment by saniho** [comment]
en effet pour les pull request, il serait bien dans un premier temps, de juste la faire, et que celui qui la valide ne soit pas celui qui l'ai demandée( review process )
Pour le test local, @Djailla , si besoin dis moi...

**Comment by mdeweerd** [comment]
Dans le 'Makefile', il y a 'test' - cela lance le test (dans test/) en local, mais pas le test à la racine.

**Comment by saniho** [comment]
tout est merge...merci pour le job
