### ISSUE TITLE
Intégrations

### ISSUE THREAD

**Issue by foXaCe** [saniho/apiEnedis#12]
Bonjour,

est il possible de l'ajouter dans les intégrations pour une configuration avec config flow.
comme ca la configuration serais plus simple et éviterai les erreurs.
en tout cas merci pour le super taf.

**Comment by saniho** [comment]
ceci arrive .... une version beta est disponible
https://github.com/saniho/apiEnedis/releases/tag/v1.1.0.0alpha2

**Comment by foXaCe** [comment]
bonjour
il manque les textes de descriptions

![image](https://user-images.githubusercontent.com/290678/103165430-1b567d00-4818-11eb-9187-4c0554543cd0.png)

**Comment by foXaCe** [comment]
a part le petit probleme de texte tout fonctionne bien pour moi
bravo

**Comment by saniho** [comment]
la derniere release alpha4 contient maintenant les textes ;)
