### ISSUE TITLE
Pertes de l'historique des relevé Enedis après reboot HA

### ISSUE THREAD

**Issue by Moustik2002** [saniho/apiEnedis#120]
Fait suite à https://github.com/saniho/content-card-linky/issues/58#issuecomment-1030344173

Après un soft restart de HA, perte de l'historique :
 
 
![image](https://user-images.githubusercontent.com/7987482/152602910-6205f5a3-9002-407a-8f4f-dfa83b537164.png)

**Comment by WarC0zes** [comment]
J'ai remarquer ça depuis un bon moment. Si après minuit et avant les remontés du jour on reboot HA, on perd toutes les infos. Donc si je doit reboot, j'attends les remontés du jour. Je reboot souvent, a cause de maj, de modification sur ha ...

**Comment by Moustik2002** [comment]
vous avez ca aussi vous ? Ca fait deux jours :
![image](https://user-images.githubusercontent.com/7987482/152682331-44897854-39ff-469b-b39e-b3f4c97c0fac.png)

**Comment by mdeweerd** [comment]
Moi j'ai deux compteurs, les deux sont ok en ce moment.

**Comment by WarC0zes** [comment]
Moi ca va, appart aujourd'hui. j'ai pas toute les infos, mais c'est le we et enedis bug souvent.
![enedis card](https://user-images.githubusercontent.com/91471397/152690324-33392f9c-e16e-4812-a4d5-52b92b1a8a44.jpg)

**Comment by saniho** [comment]
La pre-release 1.4.1.0 devrait regler le probleme de la perte d'information lors d'un reboot
dans l'attente de votre confirmation

**Comment by Moustik2002** [comment]
Ca marche j'installe ca et je te fais un retour d'ici un a deux jours ;)

**Comment by WarC0zes** [comment]
Je viens d'install le maj et j'ai reboot pour la finaliser ( normal :) ). Il est 4h32 et j'ai aucune infos conserver. Peu être je doit attendre les prochain remontées pour que ca fonctionne. 

@Moustik2002 
Normal que ça fonctionne tu as reboot avant minuit ;) 
C'est après minuit et les remonté du jours que ca remonte pas. Genre de 00h00 à 10h00.

**Comment by Moustik2002** [comment]
Effectivement, avant reboot :
![image](https://user-images.githubusercontent.com/7987482/152947553-0715a8b5-d190-472d-97e6-6f74c1ee8af0.png)
 Apres :
 
![image](https://user-images.githubusercontent.com/7987482/152947917-f317cb81-dfe1-4dc1-8d01-6758638f9023.png)

**Comment by WarC0zes** [comment]
Certe dans energie ca conserve l'historique jusqu'a l'heure du reboot. Mais après un reboot ca stop l'historique.
Dans mon cas, j'ai reboot a 4h32 et comme on le voit ca stop l'historique a 4h.
![enedis1 4 1 0 bug](https://user-images.githubusercontent.com/91471397/152954663-b7758b38-0ccd-429c-b21f-4c0255f53a75.jpg)

**Comment by saniho** [comment]
hello, la version pre-release 1.4.1.1 devrait regler les soucis ....

**Comment by Moustik2002** [comment]
Merci @saniho je test et je te tiens au jus ;)

**Comment by WarC0zes** [comment]
Tu y est presque :)
J'ai la 1.4.1.1 et j'ai reboot a 3h52, il y a l'historique qui est rester mais il manque 1 jour. Je vais installer le core 22022.2.4 qui vient de sortir et reboot voir si c'est bon.
![enedis1 4 1 1](https://user-images.githubusercontent.com/91471397/153112846-09282244-bcc5-4ab5-996b-33cb11c4cc91.jpg)

**Comment by Moustik2002** [comment]
Je viens de reboot pour test, je pense qu'on est bon !
![image](https://user-images.githubusercontent.com/7987482/153155894-88dc4c33-d984-488c-a840-422adda1847f.png)
Merci @saniho pour tes modifications !

**Comment by saniho** [comment]
Good news
@WarC0zes a voir si demain tu as toujours le problème... Peut-être lié a un soucis chez enedis

**Comment by WarC0zes** [comment]
Retest ce matin a 5h un reboot et c'est bon. il y a que le jours qui est a 0% mais c'est normal.
![enedis 1 4 1 1 ok](https://user-images.githubusercontent.com/91471397/153340974-9b8ec58b-2e94-42fa-9b46-affa87c42271.jpg)

C'est bon aussi dans énergie sa garde bien l'historique et continu l'affiche de l'historique après reboot. 
(  j'ai attendu 1h après le reboot pour être sur )
![energie ok](https://user-images.githubusercontent.com/91471397/153341256-747828bf-f697-40ae-babb-c35891d843e9.jpg)

Encore merci @saniho pour toutes ces modifications.

**Comment by WarC0zes** [comment]
@saniho 
Quand il y a une erreur pendant les remontées du jour, et qu'on voit le message: "on retentera plus tard"
c'est quand plus tard ? dans les prochaine heures, le lendemain ?

**Comment by saniho** [comment]
la prochaine tentative aura lieu 1 heure après jusqu'à 23:30, et si pas ok, cela sera le lendemain
