### ISSUE TITLE
yesterday % error

### ISSUE THREAD

**Issue by saniho** [saniho/apiEnedis#125]
Par contre il y a un problème sur le pourcentage du jours, car j'ai bien les infos remonté mais le calcul se fait pas. Ca reste sur -100%
![linky jours](https://user-images.githubusercontent.com/91471397/151537889-e648d3ec-eefb-4933-9fd8-1c7b33ea6996.jpg)

_Originally posted by @WarC0zes in https://github.com/saniho/apiEnedis/issues/111#issuecomment-1024118480_

**Comment by saniho** [comment]
la pre release 1.4.1.0 doit reglé se soucis

**Comment by WarC0zes** [comment]
Ok, je te tient au courant avec les remontées de ce matin.

**Comment by WarC0zes** [comment]
![enedis1 4 1 0 jour ok](https://user-images.githubusercontent.com/91471397/152965230-dff6fc3f-d700-41de-b52d-ed6d9b4b2150.jpg)

La photo parle d'elle même, ça fonctionne :)
Grand merci pour tout ce travaille fournie.
