### ISSUE TITLE
Forfait de base (non HC/HP) documentation

### ISSUE THREAD

**Issue by BrunoFL** [saniho/apiEnedis#13]
Bonjour,

Ce serait pas mal de mettre à jour la documentation (fournir un exemple) pour désactiver le mode heure pleine/heure creuse (forfait de base). Avec le prix à entrer correspondant pour le calcul.

Ou alors une option dans la config pour activer/désactiver 

Merci, super travail !

**Comment by saniho** [comment]
@BrunoFL , tu peux mettre cette declaration : 

- platform: myEnedis
  token: yyyy
  code: xxx
  hp_cout: 0.1175
  scan_interval: 120

**Comment by BrunoFL** [comment]
C'est gentil pour moi, mais ça peut intéresser d'autres personnes, dans le readme ça peut être une bonne idée ?

**Comment by riyas1980** [comment]
@saniho 

Bonjour,

Je l'ai fait comme tu as dit. Mais la consommation  est toujours affiché en HP/HC

Voici la déclaratgion 

# enedis
- platform: myEnedis
  token: FRyzB7oU0nDuhPc13gxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  code: 2147400000000
  hp_cout: 0.155953
  scan_interval: 120

Et le résultat est le suivant : 

**********************************************
attribution: 
version: 1.0.5.4
typeCompteur: consommation
lastSynchro: 2020-12-15T09:17:48.285334
lastUpdate: 2020-12-15T09:17:48.285308
timeLastCall: 2020-12-15T09:17:48.285043
yesterday: 13069
last_week: 110953
day_1_HP: 4243
day_2_HP: 8110
day_3_HP: 5092
day_4_HP: 5258
day_5_HP: 5263
day_6_HP: 6695
day_7_HP: 7266
day_1_HC: 8826
day_2_HC: 9165
day_3_HC: 9221
day_4_HC: 10549
day_5_HC: 10217
day_6_HC: 11225
day_7_HC: 8945
dailyweek_cost: 0.66, 1.26, 0.79, 0.82, 0.82, 1.04, 1.13
dailyweek_costHC: 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00
dailyweek_HC: 8.826, 9.165, 9.221, 10.549, 10.217, 11.225, 8.945
dailyweek: 2020-12-14, 2020-12-13, 2020-12-12, 2020-12-11, 2020-12-10, 2020-12-09, 2020-12-08
dailyweek_costHP: 0.66, 1.26, 0.79, 0.82, 0.82, 1.04, 1.13
dailyweek_HP: 4.243, 8.110, 5.092, 5.258, 5.263, 6.695, 7.266
***************************************************

Est-ce normal ?

Cordialement,

**Comment by algernon2607** [comment]
Bonjour à tous
je serais également intéressé par l'affichage correct du contrat base . Les suggestions ci dessus ne fonctionnent pas .
J'aimerais également incorporer l'index injection ....

Cordialement

**Comment by saniho** [comment]
index d'injection ?

**Comment by algernon2607** [comment]
Dans une installation photovoltaïque avec vente de surplus , le même compteur Linky est utilisé pour la consommation et la  production . Il y a donc un index qui compte la production : c'est l'index injection.Mon souhait serait d’intégrer cet index .

**Comment by saniho** [comment]
Si tu peux me donnerton pdl et token en mp...je peux voir si cette information est disponible...

**Comment by algernon2607** [comment]
Ok mais quelle est la procedure pour un MP?? Je ne trouve pas ta boite ...

**Comment by saniho** [comment]
sur hacf si tu a comptes( forum francais de home assistant )
sinon, je te donne mon mail
