### ISSUE TITLE
Error - No data

### ISSUE THREAD

**Issue by Drealine** [saniho/apiEnedis#14]
Bonjour,

J'ai ce message en tout début de journée depuis 2J. 

![image](https://user-images.githubusercontent.com/61891683/102180425-21a83900-3ea9-11eb-9aa8-01a94c388693.png)

>  Logger: custom_components.myEnedis.sensor
> 
> Source: custom_components/myEnedis/apiEnedis.py:57
> Integration: myEnedis
> First occurred: 14 décembre 2020 à 12:55:24 (54 occurrences)
> Last logged: 6:55:50
> 
> Erreur last answer ('call', 'error', 'Invalid_request')
> updateYesterday
> myEnedis ...XXX update lancé, status precedent : False, lastCall :updateYesterday
> Erreur inconnue call ERROR ('call', 'error', 'no_data_found')
> Erreur last answer ('call', 'error', 'no_data_found')

Est-ce dû à la remontée des données côté Enedis ?
J'ai activé le relevé horaire.

Ma conf : 

> - platform: myEnedis
    token: XX
    code: XX
    scan_interval: 3600
    delay: 7200
    hc_cout: 0.137
    hp_cout: 0.156

**Comment by saniho** [comment]
Bonjour, ceci est du à un soucis sur la plateforme Enedis, tu devrais voir les données reapparaitre
