### ISSUE TITLE
Error: result_500, technical error

### ISSUE THREAD

**Issue by davidgontier** [saniho/apiEnedis#15]
Dear Saniho,
Thanks for your work! myEnedis works very nicely. I just have this weird error on the card (below the day of the week):

 {'error': 'result_500', 'enedis_return': {'error': 'technical_error', 'error_description': 'Technical error. Please try later.', 'error_uri': 'https://bluecoder.enedis.fr/api-doc/consulter-souscrire'}}

Did I do something wrong?

I also have some Warnings in the logs, of the form (but I think this is unrelated).

Logger: custom_components.myEnedis.sensor
Source: custom_components/myEnedis/sensor.py:174
Integration: myEnedis
First occurred: 1:35:17 (5 occurrences)
Last logged: 15:31:25

############# - **** fin ERROR *** updateLastWeek

**Comment by saniho** [comment]
Hello, this is due to Enedis Server Issue( regulary on the morning ), let me know if this error stay present

**Comment by saniho** [comment]
hello last alpha version alpha5 manage this error, can you test and confirm ?

**Comment by davidgontier** [comment]
Dear Saniho,
Indeed, the error appears and vanishes... this morning I had it, so I tried alpha5. After reboot, I now have Nan everywhere and a warning symbol on the card (but errors on the card).

Here is (part of) the log:

```
Logger: custom_components.myEnedis.sensor
Source: /home/homeassistant/.homeassistant/custom_components/myEnedis/myEnedis.py:52
Integration: MyEnedis (documentation)
First occurred: 12:20:28 (1 occurrences)
Last logged: 12:20:28

run myEnedis
NoneType: None
```

and the warning
```
Logger: custom_components.myEnedis.sensor
Source: custom_components/myEnedis/myEnedis.py:61
Integration: MyEnedis (documentation)
First occurred: 12:20:31 (4 occurrences)
Last logged: 12:20:45

myEnedis ...############ update lancé, status precedent : True, lastCall :None
Error JSON : {"error":"result_400","enedis_return":{"error":"Invalid_request","error_description":"Start date should be before end date.","error_uri":"https://bluecoder.enedis.fr/api-doc/consulter-souscrire"}}
############# - Erreur call ERROR ('call', 'error', 'Invalid_request')
############# - last call : updateCurrentYear
```

Thx and happy new year!

**Comment by saniho** [comment]
la derniere version  v1.1.1.0 règle ce soucis
