### ISSUE TITLE
Erreur de version

### ISSUE THREAD

**Issue by WarC0zes** [saniho/apiEnedis#155]
J'ai la dernière version 1.5.0.3, mais j'ai un message me disant qu'il y a une mise a jour de disponible.

![myenedis bug1](https://user-images.githubusercontent.com/91471397/158383628-2ab1145a-aea9-4fcc-ae22-852831bf99a0.jpg)
![myenedis bug2](https://user-images.githubusercontent.com/91471397/158383636-3159baf1-10cd-4b98-89c5-26c36d47824b.jpg)
![myenedis bug3](https://user-images.githubusercontent.com/91471397/158383637-27c9f341-bd0e-475d-ab3d-570e102bca87.jpg)

Après j'ai remarquer, que quand on reboot ca relance le scan myenedis alors que ca avait été corriger.

**Comment by mdeweerd** [comment]
Le tag de version n'a pas été bougé par le nouveau script de "release", du coup le fichier récupéré (manifest.json) ne contient pas le bon numéro de version.

J'ai bougé le tag à la main, donc ce sera réglé avec une mise à jour.

A l'avenir ce sera le ZIP qui fera foi, mais je regardes quand même pour que le script agit comme attendu.
