### ISSUE TITLE
Sensor ne fonctionne pas sur mon HA

### ISSUE THREAD

**Issue by Didou30** [saniho/apiEnedis#16]
Bonjour,

pas moyen de le faire fonctionner lors de la vérification de la config: Platform error sensor.myEnedis - Integration 'myEnedis' not found.
Tout est dans custom component voir image merci de votre aide
![image](https://user-images.githubusercontent.com/75094327/102701022-0b0c3400-4253-11eb-9c3c-d2f579eb56a4.png)
version  Home Assistant OS 5.8

Didier

**Comment by Didou30** [comment]
Bonjour,

j'ai trouvé le problème le domaine était "SANIHO" au lien de "MyEnedis" dans le sensor.py tout fonctionne bien, merci à Saniho pour le développement du composant.
![image](https://user-images.githubusercontent.com/75094327/102719557-13b24800-42ef-11eb-84f3-f13efb044786.png)

**Comment by saniho** [comment]
bonjour la version beta https://github.com/saniho/apiEnedis/releases/tag/v1.1.0.0alpha2 règle en autre ce soucis...
