### ISSUE TITLE
Code erreur 'enedis_return'

### ISSUE THREAD

**Issue by cedsib** [saniho/apiEnedis#17]
Hello,

Quand j'exécute la commande de test j'ai plein de retours corrects.
Mais dans HA, j'ai le code 'enedis_return' dans le sensor :
`errorLastCall: '''enedis_return'''`

Pourtant sur ma précédente version de HA (avant les grosses mises à jour de nouvelles versions) ça marchait comme un charme (même compteur, j'ai renouvelé le token pour être sûr mais en fait il fonctionne vu que le CURL de test tourne)

**Comment by saniho** [comment]
la plateforme Enedis était HS...
Certaines erreurs sont aussi corrigées dans la version : https://github.com/saniho/apiEnedis/releases/tag/v1.1.0.0alpha2
si vous avez moyen de tester?*

**Comment by saniho** [comment]
duplicate issue
