### ISSUE TITLE
Somme trompeuse sur plusieurs jours

### ISSUE THREAD

**Issue by mdeweerd** [saniho/apiEnedis#170]
![image](https://user-images.githubusercontent.com/1504752/160816203-2ad940c9-355a-46c7-bbda-45fbcfde57bc.png)
![image](https://user-images.githubusercontent.com/1504752/160816617-686c76c7-4b30-4777-a1c9-5f4572ed2a58.png)

Les images disent prèsque tout:
- En haut à gauche on a 8.9kWh;
- Pour lundi le total serait 17.7kWh;
- Le mardi à 15h41, 9.9kWh est enregistré;
- Le mercredi à 14h41, 8.87kWh est enregistré (9.9+8.87=18.77kWh);
- Le linky, à travers son port TIC donne 9.9kWh pour dimanche, 8.87kWh pour lundi, 8.35kWh pour mardi .  Ce qui est remonté à travers l'API est donc correct.

Ainsi, la valeur de 8.9 kWh est étrange, la valeur de 17.7kWh est étrange, le cout de l'énergie ne correspond pas à la consommation en haut à driote, mait peut correspondre à la consommation de 17.7kWh .

(J'ai gardé une copie du contenu du répertoire myEnedis sous data_20220330.tar.gz).

**Comment by WarC0zes** [comment]
Salut, j'ai remarquer la même erreur. Lundi j'ai eu des remontées bizarre comme toi et aujourd'hui c'est bon.
![enedis bug](https://user-images.githubusercontent.com/91471397/160870416-47f8c919-5ce2-4b00-8212-7cee5b592a49.jpg)

**Comment by bckthomas** [comment]
L'intégration m'affiche 1301kwh pour le mois de novembre, mais quand je vais sur https://mon-compte.enedis.fr je suis à 582kwh
Qu'est-ce qui peut expliquer une telle différence ?

**Comment by mdeweerd** [comment]
Je ferme ce ticket car entretemps il y a eu pas mal d'évolutions et je n'utilise plus l'intégration.
