### ISSUE TITLE
Nouvelle API

### ISSUE THREAD

**Issue by navycrow** [saniho/apiEnedis#174]
A force d'erreur dans le fonctionnement de l'intégration, je me suis rendu compte que l'API utilisée est obsolète.
Il y en a une nouvelle à cette adresse : https://www.enedisgateway.fr/

**Comment by saniho** [comment]
merci pour l'information, en effet, il va y avoir une petite migration à réaliser....

**Comment by archit3kt** [comment]
Ah, je pense que ca explique les erreurs suivantes que j'ai dans les logs !

`2022-04-09 16:23:08 ERROR (SyncWorker_5) [myEnedis] ====== Appel http #1 !!! requests.exceptions.HTTPError
2022-04-09 16:38:28 ERROR (SyncWorker_6) [myEnedis] ====== Appel http #2 !!! requests.exceptions.HTTPError
`

Nouvel utilisateur de HA, je n'ai pas encore pu voir cette intégration fonctioner mais j'ai hâte, merci pour votre boulo :)

**Comment by mdeweerd** [comment]
@archit3kt L'ancienne api fonctionne encore - le " requests.exceptions.HTTPError" a probablement une autre cause.

Vous avez probablement un fichier "data_1.txt" et "data_2.txt" dans "custom_components/archive/myEnedis/test_data" ou "custom_components/myEnedis/myEnedis/test_data" .  Si ce fichier est à la date du jour, il contient le retour de la gateway .

Dans mon cas le premier appel contient toujours `"usage_point_id":"..............","error":"token_refresh_401","description":"Une erreur est survenue, merci de renouveller vos consentements.","user_alert":true}"` bien que cela ne correspond pas à là réalité - aux appels suivants "tout" passe.
J'ai un HTTPError pour une autre réponse, également systématiquement, mais c'est aussi anodin (je ne suis pas producteur d'énergie).

**Comment by archit3kt** [comment]
Merci @mdeweerd pour votre réponse ! J'ai finalement refait les autorisations Enedis et ca a débloqué le problème.

**Comment by mdeweerd** [comment]
J'ai fermé ce ticket en partie par erreur car l'intervention de @archit3kt est résolu, mais ce n'est pas lié au ticket initial.

J'ai ajouté cette activité à la liste pour le développement.

Merci de ne pas ajouter de commentaires qui ne sont pas liés avec certitude avec l'évolution de l'API.  `apiEnedis` fonctionne toujours avec l'ancienne API.

**Comment by mdeweerd** [comment]
Peut-être à prendre comme une occasion pour creer un nouveau projet github (pas un fork), y déposer le projet, renommer le 'domain' pour entrer dans les clous de HA & HACS.  Chaque utilisateur changera à son rythme et on n'impose pas l'évolution du code à tout le monde (pendant la stabilisation du code).

**Comment by saniho** [comment]
bof, je trouve cela dommage, d'un point de vue user, il faudrait arriver à trouver un moyen pour migrer .. à mon avis, il doit y avoir une solution, non ?

**Comment by mdeweerd** [comment]
Je ne sais pas si HA permet à un 'custom_component' d'accéder à la configuration d'un autre 'custom_component'.

Pour le moment les données sont (en partie) stockées dans un repértoire de custom_component qui n'est pas celui du composant.
On pourrait y enregistrer la configuration (sur demande de l'utilisateur à travers un appel de service?), afin que celle-ci puisse être lue par la nouvelle version.  Comme ce sont en pratique 2 composants différents, elles peuvent "co-exister" un moment - et on peu éviter les double appels à travers des états, fichiers, ou etc.
