### ISSUE TITLE
Detected blocking call to putrequest

### ISSUE THREAD

**Issue by RoniCo97** [saniho/apiEnedis#175]
Bonjour,

J'ai essayé de lier mon compteur et j'ai ce problème quelqu'un aurait un solution

Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom component author for myEnedis doing blocking calls at custom_components/myEnedis/gitinformation.py, line 37: myURL = urlopen(self._serverName)

**Comment by mdeweerd** [comment]
Ce n'est pas critique est lié à #159 .

**Comment by RoniCo97** [comment]
J'ai bien la bonne version mais ca ne fonctionne pas

**Comment by mdeweerd** [comment]
Je propose d'activer les traces de débogue pour le composant.  Je viens d'ajouter une petite explication dans la doc:

https://github.com/saniho/apiEnedis/tree/docDebug#activer-le-d%C3%A9bogue
