### ISSUE TITLE
Compteurs de consommation et de production

### ISSUE THREAD

**Issue by Forgeron05** [saniho/apiEnedis#177]
Bonjour,

Je n'arrive pas à faire fonctionner mon compteur production avec apiEnedis. J'ai peut-être mal configuré quelque chose alors je vais décrire comment j'ai procédé :
1. J'ai autorisé les collectes de données sur Enedis
2. J'ai autorisé la collecte par la gateway en cochant les deux compteurs (j'ai obtenu **un** token que j'utilise pour les deux compteurs)
3. J'ai ajouté l'intégration apiEnedis pour le compteur de consommation --> ça fonctionne bien
4. J'ai fait pareil avec le compteur de production --> ça ne fonctionne pas (j'ai des petits triangles /!\ à la place dans données dans le tableau de bord).

Je crois voir un problème au niveau des "attributs" de ce compteur, à la ligne "TypeCompteur" il est écrit "consommation" alors que c'est le compteur de production.

Je ne sais pas si vous avez assez d'informations pour m'aider mais n'hésitez pas à me demander tout ce qu'il vous faut :)

Merci d'avance

**Comment by candelwick** [comment]
Bonjour, j'ai également le même soucis

**Comment by omolko** [comment]
idem mais sur mon compte enedis le partage de données pour la production ne s'active pas

**Comment by cob94440** [comment]
Même souci pour moi

**Comment by saniho** [comment]
je garde que le  #183 
si vous voulez me partager votre credential
