### ISSUE TITLE
aborted message

### ISSUE THREAD

**Issue by laurent941** [saniho/apiEnedis#178]
Bonjour,

Je n'arrive pas valider les paramètre j'ai un message aborted quand je clique sur submit

Une idée ?

Merci d'avance de vos réponses
Je tourne en rond :)

![image](https://user-images.githubusercontent.com/56654098/166109650-57a17ea5-2c75-412f-8369-deb72957b902.png)

![image](https://user-images.githubusercontent.com/56654098/166109660-c7ad0f4a-f289-48e5-a883-16f990dd8bde.png)

**Comment by WarC0zes** [comment]
c'est le format de t'es heures creuses qui est pas bon. 
le format des HC est comme ceci: `[['00:00','06:34'],['22:34','24:00']]`  (pour ton cas)

**Comment by laurent941** [comment]
Merci Beaucoup WarCozes.
