### ISSUE TITLE
erreur "enedis_return"

### ISSUE THREAD

**Issue by cedsib** [saniho/apiEnedis#18]
Hello,

Quand j'exécute la commande de test j'ai plein de retours corrects.
Mais dans HA, j'ai le code 'enedis_return' dans le sensor :
`errorLastCall: '''enedis_return'''`

Pourtant sur ma précédente version de HA (avant les grosses mises à jour de nouvelles versions) ça marchait comme un charme (même compteur, j'ai renouvelé le token pour être sûr mais en fait il fonctionne vu que le CURL de test tourne)

**Comment by gw1gw1** [comment]
Même souci de mon côté

**Comment by francodutch** [comment]
+1

**Comment by cedsib** [comment]
J'ai l'impression que ça évolue.
Toujours pas de résultat probant, mais maintenant l'erreur est vide :
`errorLastCall: ''
unit_of_measurement: kWh`

**Comment by cedsib** [comment]
si ça peut aider :

`Logger: custom_components.myEnedis.sensor
Source: custom_components/myEnedis/sensor.py:187
Integration: myEnedis
First occurred: 12:08:17 (4 occurrences)
Last logged: 17:10:28

[CODE DU COMPTEUR] - **** CRASH ***`

**Comment by saniho** [comment]
Ceci est du à une erreur sur la plateforme Enedis
Avez-vous toujours le soucis ?

**Comment by cedsib** [comment]
Je suis entrain de tester la nouvelle version Alpha2. Je te tiens au courant !

**Comment by cedsib** [comment]
![Screenshot_20201227-012901](https://user-images.githubusercontent.com/55406881/103161504-2642ea80-47e3-11eb-801b-b630e16680fd.jpg)

Petit bug avec le paramètre "delay", je le commente et on re démarre 😉

**Comment by cedsib** [comment]
Ça a pas encore l'air bon : 

```
Logger: homeassistant.components.sensor
Source: custom_components/myEnedis/sensor.py:239
Integration: Capteur (documentation, issues)
First occurred: 1:31:26 (1 occurrences)
Last logged: 1:31:26

Error while setting up myEnedis platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/myEnedis/sensor.py", line 95, in setup_platform
    add_entities([myEnedisSensor(session, name, update_interval, mSS )], True)
  File "/config/custom_components/myEnedis/sensor.py", line 239, in __init__
    self.update = Throttle( timedelta(seconds=interval))(self._update)
TypeError: unsupported type for timedelta seconds component: datetime.timedelta
```

**Comment by saniho** [comment]
peux-tu essayer vaec la derniere release : v1.1.0.0alpha4

**Comment by cedsib** [comment]
Ecoute ça répond beaucoup mieux a priori :

```
attribution: ''
version: 1.1.0.0a
typeCompteur: consommation
lastUpdate: '2020-12-27T23:32:05.268399'
timeLastCall: '2020-12-27T23:32:05.268073'
yesterday: 9970
last_week: 111256
unit_of_measurement: kWh
friendly_name: myEnedis.XXXXXXXX

``` 

par contre ça n'a pas encore l'air bon dans la carte :
<img width="459" alt="Capture d’écran 2020-12-27 à 23 33 54" src="https://user-images.githubusercontent.com/55406881/103180991-0ae7e600-489c-11eb-8821-00b1a12eeec4.png">

**Comment by cedsib** [comment]
Ça s'améliore, on y est presque 😉

![Screenshot_20201228-132749](https://user-images.githubusercontent.com/55406881/103214399-9307d300-4910-11eb-8fdd-f07dcc0bcc36.jpg)

**Comment by saniho** [comment]
par contre, bizarre, cette absence de données...peux-tu me donner en mp ton token/PDL( ici : https://forum.hacf.fr/u/saniho/ )

**Comment by cedsib** [comment]
Je n'arrive pas à avoir les droits pour t'envoyer un MP sur le forum.
J'ai tenté de demander un nouveau token, mais ça ne change rien.
Et pourtant, en test "CURL" j'ai bien pas mal de données :
<img width="1027" alt="Capture d’écran 2020-12-29 à 09 05 43" src="https://user-images.githubusercontent.com/55406881/103268999-0d8a2e80-49b5-11eb-91b3-70bb010bc26f.png">

**Comment by saniho** [comment]
Mon mail sanihogithub(at)gmail.com

**Comment by cedsib** [comment]
`you've got mail ` 👍

**Comment by saniho** [comment]
la version alpha5 devrait resoudre ton pb...tiens moi au courant

**Comment by cedsib** [comment]
❤️ 

<img width="456" alt="Capture d’écran 2020-12-30 à 22 53 41" src="https://user-images.githubusercontent.com/55406881/103383133-e5ecb080-4af1-11eb-8897-f0fb499c4cdf.png">
