### ISSUE TITLE
Demande de Token

### ISSUE THREAD

**Issue by tatawi** [saniho/apiEnedis#182]
Bonjour,
Je souhaite demander un nouveau token car j'ai reinstallé HomeAssistant. Tout est bien configuré au niveau de mon compte Enedis.

Sur https://enedisgateway.tech/, je fais la demande de consentement. Le bouton me renvoie vers le site Enedis. Je valide la coche (je conscens librement ...)

Le click sur le bouton valider ne fait rien. Je reste sur la même page (et rien ne charge). Je reçois tout de même un mail d'enedis avec un récapitulatif du partage.

Cependant, je n'ai pas d’accès à un token car la page n'a rien chargé.

Est-ce que cela vient de chez moi ou c'est plus global ?

j'ai ça au niveau de l'inspecteur, je ne sais pas si ça peut aider
![image](https://user-images.githubusercontent.com/9949011/170832971-4ad91d54-37f1-405e-a5fe-bfe0235695af.png)

**Comment by istornz** [comment]
J'ai exactement le même problème de mon côté... J'ai comme l'impression d'un bug venant de Enedis ...

**Comment by karba78** [comment]
j ai exactement le meme probleme

**Comment by Alniro77** [comment]
Bonjour,
Même chose pour moi

**Comment by dragonis41** [comment]
Même issue sur le GitHub de Bokub, Enedis a merdé quelque part et leur API est cassé depuis le 31 mai. Pour le moment on n'a pas d'autres choix que d'attendre qu'un fix soit déployé :/
https://github.com/bokub/linky/issues/36#issuecomment-1145833084

**Comment by loicdugay** [comment]
Bonjour, toujours pas de nouvelles de la part de Enedis ?
