### ISSUE TITLE
Warning avec nouvelles version home-assistant

### ISSUE THREAD

**Issue by MaxWaldorf** [saniho/apiEnedis#184]
Bonjour,

Je reçois le message d'erreur suivant:

`Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom component author for myEnedis doing blocking calls at custom_components/myEnedis/gitinformation.py, line 37: myURL = urlopen(self._serverName)`

Update possible ?

Merci

**Comment by saniho** [comment]
corrigé
