### ISSUE TITLE
récupération des données pour un seul compteur parmi 2 sous le même token

### ISSUE THREAD

**Issue by nmrtn** [saniho/apiEnedis#189]
Hello! Merci pour le boulot d'intégration. Hyper cool!

Rapide issue, sur le site d'enedis, je vois bien des donnés sur les 2 PDL. 
Lors des calls API à enedisgateway, j'ai cette réponse sur un des 2 compteurs. 

{"tag":"enedis_return_ko","error_code":"no_data_found","description":"no measure found for this usage point","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}%

Y a t'il un problème sur les accès multi-compteurs ? 
Merci

**Comment by mdeweerd** [comment]
J'ai 2 compteurs sur le même compte et cela fonctionne.

**Comment by saniho** [comment]
As-tu bien activé la remonté(partage ) des deux compteurs ?
