### ISSUE TITLE
Aucun sensor dispo dans les entités

### ISSUE THREAD

**Issue by Manox35** [saniho/apiEnedis#19]
Bonjour,

Je ne comprends pas, aucun sensor disponible alors que j'ai des données avec la commande Curl

    - platform: myEnedis
        token: XX
        code: XX
        heures_creuses: "['22:40', '06:40']"
        hc_cout: 0.1295
        hp_cout: 0.1725
        scan_interval: 3600  
        delay: 7200

**Comment by uowis** [comment]
- Tu as installer via HACS ou directement en copiant les fichiers ?

> Bonjour,
> 
> Je ne comprends pas, aucun sensor disponible alors que j'ai des données avec la commande Curl
> 
> ```
> - platform: myEnedis
>     token: XX
>     code: XX
>     heures_creuses: "['22:40', '06:40']"
>     hc_cout: 0.1295
>     hp_cout: 0.1725
>     scan_interval: 3600  
>     delay: 7200
> ```

Comment a tu installer le sensor ? via HACS ou en copiant les fichiers ?

**Comment by Manox35** [comment]
Bonjour, installé via HACS et à chaque foi j’ai cette erreur qui correspond au départ du token (34,12). J’ai essayé avec guillement, quote, sans rien, bref rien n’y fait

   - platform: myEnedis
      token: LmkFM0qxhXO4MXRHYBvdhbWuBDc9wlu0nEmPEJ0XUPxshBdcT5lf4y                             (Exemple)
      code: 14541244549805
      heures_creuses: "['22:40', '06:40']"
      hc_cout: 0.1295
      hp_cout: 0.1725
      scan_interval: 3600  
      delay: 7200

Error loading /config/configuration.yaml: mapping values are not allowed here in "/config/configuration.yaml", line 34, column 12
11:10:39 – Home Assistant Core Integration (ERROR)
mapping values are not allowed here in "/config/configuration.yaml", line 34, column 12
11:10:39 – util/yaml/loader.py (ERROR)

Merci pour votre aide car ca fait 4 jours que je galère !




De : uowis
Envoyé le :mercredi 23 décembre 2020 22:51
À : saniho/apiEnedis
Cc : Manox35; Author
Objet :Re: [saniho/apiEnedis] Aucun sensor dispo dans les entités (#19)

• Tu as installer via HACS ou directement en copiant les fichiers ?
Bonjour,
Je ne comprends pas, aucun sensor disponible alors que j'ai des données avec la commande Curl
- platform: myEnedis

    token: XX

    code: XX

    heures_creuses: "['22:40', '06:40']"

    hc_cout: 0.1295

    hp_cout: 0.1725

    scan_interval: 3600  

    delay: 7200

Comment a tu installer le sensor ? via HACS ou en copiant les fichiers ?

**Comment by Manox35** [comment]
J’ai aussi changé le DOMAIN dans sensor.py comme dit dans le fil de discussion par DOMAIN = "myEnedis"



De : uowis
Envoyé le :mercredi 23 décembre 2020 22:51
À : saniho/apiEnedis
Cc : Manox35; Author
Objet :Re: [saniho/apiEnedis] Aucun sensor dispo dans les entités (#19)

• Tu as installer via HACS ou directement en copiant les fichiers ?
Bonjour,
Je ne comprends pas, aucun sensor disponible alors que j'ai des données avec la commande Curl
- platform: myEnedis

    token: XX

    code: XX

    heures_creuses: "['22:40', '06:40']"

    hc_cout: 0.1295

    hp_cout: 0.1725

    scan_interval: 3600  

    delay: 7200

Comment a tu installer le sensor ? via HACS ou en copiant les fichiers ?

**Comment by Manox35** [comment]
Et quand je mets mon token entre guillements » » plus d’erreur mais toujours aucun sensors dans mes entités !  Je comprends plus rien 😉 😉



De : uowis
Envoyé le :mercredi 23 décembre 2020 22:51
À : saniho/apiEnedis
Cc : Manox35; Author
Objet :Re: [saniho/apiEnedis] Aucun sensor dispo dans les entités (#19)

• Tu as installer via HACS ou directement en copiant les fichiers ?
Bonjour,
Je ne comprends pas, aucun sensor disponible alors que j'ai des données avec la commande Curl
- platform: myEnedis

    token: XX

    code: XX

    heures_creuses: "['22:40', '06:40']"

    hc_cout: 0.1295

    hp_cout: 0.1725

    scan_interval: 3600  

    delay: 7200

Comment a tu installer le sensor ? via HACS ou en copiant les fichiers ?

**Comment by uowis** [comment]
dans ton cas si tu le met dans dans configuration.yaml
alors il faut bien le metre dans un "sensor:" 
Ex :
`sensor:
    - platform: myEnedis
      token: XXXXX
      code: XXXXX
      hp_cout: 0.148
      scan_interval: 3600
      delay: 7200  # OPTION`

**Comment by Manox35** [comment]
Oui il y a bien un sensor déclaré, j’ai même essayé dans sensors.yaml !



De : uowis
Envoyé le :jeudi 24 décembre 2020 13:31
À : saniho/apiEnedis
Cc : Manox35; Author
Objet :Re: [saniho/apiEnedis] Aucun sensor dispo dans les entités (#19)

dans ton cas si tu le met dans dans configuration.yaml
alors il faut bien le metre dans un "sensor:"
Ex :
sensor: - platform: myEnedis token: XXXXX code: XXXXX hp_cout: 0.148 scan_interval: 3600 delay: 7200 # OPTION

**Comment by uowis** [comment]
Tu n'as plus aucune des deux erreurs : 

11:10:39 – Home Assistant Core Integration (ERROR)
mapping values are not allowed here in "/config/configuration.yaml", line 34, column 12
11:10:39 – util/yaml/loader.py (ERROR

?

**Comment by Manox35** [comment]
Ca y est, j’ai trouvé grâce à ta remarque sur le sensor, j’avais plus bas dans le purifer 3h de Xiaomi une declaration sensor dans une platform : Template, j’ai viré tout ca et ca marche 😉 😉 😉



De : uowis
Envoyé le :jeudi 24 décembre 2020 15:36
À : saniho/apiEnedis
Cc : Manox35; Author
Objet :Re: [saniho/apiEnedis] Aucun sensor dispo dans les entités (#19)

Tu n'as plus aucune des deux erreurs :
11:10:39 – Home Assistant Core Integration (ERROR)
mapping values are not allowed here in "/config/configuration.yaml", line 34, column 12
11:10:39 – util/yaml/loader.py (ERROR
?
