### ISSUE TITLE
rythme des interrogations

### ISSUE THREAD

**Issue by Georgesbb83** [saniho/apiEnedis#190]
Bonjour,
la BDD d'Enedis comporte les infos de la veille (et antérieures). La mise à jour se fait dans la nuit (vers 3h du matin).
Il est donc inutile d'interroger l'API toutes les 10mn.
Comment configurer le module pour paramétrer l'intervalle entre interrogations (toutes les 24h) et le moment de l'interrogation (à 5h du matin) ?
Cordialement

**Comment by mdeweerd** [comment]
Le service a des limitations - surtout Enedis limite la gateway.

Voici ce qui se passe à mon avis:

Dans le cas normal, la gateway est géré par un distributeur d'énergie et les appels à Enedis sont bien maitrisés et séquentiels pour interroger tous les comptes selon un planning.  Pour limiter la charge, Enedis limite le nombre d'appels par seconde/par minute/par heure/.

Avec notre gateway, les demandes sont initiées par l'utilisateur.  Donc si tous les utilisateurs font leur demande à 3h30 du matin par exemple, la gateway atteint la limitation et plus personne ne peut récupérer des données.
Du coup, apiEnedis comprend un côté aléatoire et distribué.
Le côté aléatoire c'est que les interrogations ne commencent pas toujours au même moment, et l'espacement entre deux appels individuels à la gateway sont espacés de façon aléatoire.
Le côté espacé, c'est qu'entre deux appels à la gateway, il y a un délai assez important.

L'objectif de cela est de limiter la probabilité que trop d'utilisateurs fassent une demande à l'API en même temps et pour éviter qu'il y a trop d'appels par période.  
Si par malheur il y a trop d'appels à un instant t, ces appels réussiront une prochaine fois.

De mémoire il y a entre outre une limitation de 5 appels par seconde au niveau de la gateway. 

De plus, la gateway elle-même limite le nombre d'appel par jour par compte à 50.

Dans l'historique des "issues" on trouve encore des messages ou des utilisateurs partagent les difficultés d'obtenir des données.  C'est suite à la mise en place de ce mécanisme que tout le monde s'y retrouve à peu près.  C'est à dire que – comme –on aimerait bien avoir les données au plus vite, mais au moins on les a dans la journée grâce au partage collectif des ressources, non pas grâce à l'intelligence collective, mais à grâce à l'effort des développeurs.

Donc du coup, apiEnedis ne laisse pas la possiblité de configurer l'heure de l'interrogation et cela restera ainsi.

**Comment by Georgesbb83** [comment]
bien compris
merci pour cet excellent boulot
y a-t-il possibilité de récupérer le compteur d'injection ? (j'ai des panneaux solaires et j'injecte mon surplus d'énergie)

**Comment by Georgesbb83** [comment]
sur https://enedisgateway.tech/doc, on download le fichier swagger.json dans lequel on trouve :
        ....
        "responses": {
          "200": {
            "description": "Retourne la liste des données.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/ConsumptionLoadCurve"
                    },
                    {
                      "$ref": "#/components/schemas/DailyConsumption"
                    },
                    {
                      "$ref": "#/components/schemas/DailyConsumptionMaxPower"
                    },
                    {
                      "$ref": "#/components/schemas/ProductionLoadCurve"
                    },
                    {
                      "$ref": "#/components/schemas/DailyProduction"
          .....
**Consumption** doit correspondre à la consommation habituelle,
**Production** doit correspondre à l'injection ?????

**Comment by mdeweerd** [comment]
Je suppose - et je vois que dans l'état on a un champ "yesterday_production" dans l'état.
Je n'ai pas trop creusé cette partie des fonctionnalités, mais le typecompteur doit surement être production dans ce cas là:
![image](https://user-images.githubusercontent.com/1504752/178574486-9ae0108d-9cb7-4c5c-af15-d2d9b9ea04e4.png)

**Comment by saniho** [comment]
oui, en effet, le compteur doit etre de type production
Si enedis indique que le compteur double sens.....bien sur ;)

**Comment by saniho** [comment]
je clos et ne arde que une issue sur la production
https://github.com/saniho/apiEnedis/issues/193
