### ISSUE TITLE
Question sur le Sensor myEnedis.energy.Hours

### ISSUE THREAD

**Issue by juju159** [saniho/apiEnedis#191]
Bonjour,

Je ne comprends pas bien ce que renvoit ce sensor?
myEnedis.energy.Hours.19XXXXXXXX

Bien que les données renvoyées sur le site de enedis sont à la demi-heure, j'ai essayé de les comparés avec ce sensor et les valeurs sont complètement fausses?

Cordialement

**Comment by saniho** [comment]
helo, ton sensor myEnedis.energy.Hours.19xx renoi la consommation de J-2 sur la tranche horaire courante
exemple, pour l'heure courante du 02/08 21:33, ce senro aura la valeur du 31/07 entre 21h>21h59
