### ISSUE TITLE
Mauvais attribut pdl

### ISSUE THREAD

**Issue by cob94440** [saniho/apiEnedis#193]
Bonjour,

Je possède deux pdl. Un pour la conso un pour la prod.
Aucun soucis pour celui de conso.
En revanche celui de prod est vu comme un compteur de conso et ne voit ps la prod.
Comment modifier?
Merci d'avance

**Comment by NicolasChauve** [comment]
Bonsoir, j ai extactement le meme probleme.  avez vous trouver une solution pour que le PDL de production soit reconnu  ?

**Comment by saniho** [comment]
la version 2.2.0-beta devrait résoudre le soucis et mettre àdisposition un sensor production
