### ISSUE TITLE
Migration vers MyElectricalData ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [saniho/apiEnedis#198]
Hello @saniho,

Pour information Enedis vient de sortir une nouvelle version des API (v5) et revu le fonctionnement de celle-ci.

Perso je suis en train de rework le projet EnedisGateway qui devient [MyElectricalData](https://myelectricaldata.fr) et j'appliquerais les modification uniquement sur le nouveau projet.

Du coup, faudrait qu'on ce croise pour que t'intégre les evolutions car les anciennes API d'Enedis seront hors ligne en mai 2023.

**Comment by saniho** [comment]
Helo @m4dm4rtig4n 
Avec plaisir pour re prendre contact, dis moi ce qui évolue et je verrai comment l'implementer dans le module.

**Comment by cvalentin-dkt** [comment]
Pour te facilité l'intégration, il y a dorénavant un Swagger :
https://myelectricaldata.fr/swagger

Actuellement ca utilise encore les anciennes API d'Enedis (v4), je n'ai pas encore commencer l'intégration de la v5

**Comment by saniho** [comment]
@cvalentin-dkt , j'ai regardé la nouvelle verison, par contre, à ce que je comprends, il faut refaire un consentement ? ce n'est pas le meme que celui de l'api precédente ? Si c'est le cas, cela va compliqué la migratoin pour les utilisateurs ... une solution ?

**Comment by m4dm4rtig4n** [comment]
Malheuresment c'est une nouvelle application déclaré chez Enedis et il faut donc refaire le consentement sur la nouvelle passerelle :/
J'ai dû abandonner le nom d'EnedisGateway sur la demande d'Enedis.

**Comment by saniho** [comment]
J'ai livré une premier pre-release( v2.0.0 ) qui permet de choisir son "partenaire" : soit EnedisGateway soit myElectriData
Si vous pouvez tester ... et me faire un retour

**Comment by Nackophilz** [comment]
Merci pour la pre release Saniho ! 

Par contre de mon côté, j'ai une erreur 500 quand je tente d'ajouter l'intégration après l'avoir prise sur HACS .. Un problème de mon côté peut être ?

**Comment by m4dm4rtig4n** [comment]
@saniho sur la prochaine MEP de la passerelle MyElectricalData, il sera possible de récupérer les jours Tempo d'EDF ainsi que les données d'Ecowatt si tu désire les intégrer dans la card.

Tempo :
![image](https://user-images.githubusercontent.com/7872518/206392101-74b4b261-2a4e-49cf-979e-c261c1aac1da.png)

Ecowatt : 
![image](https://user-images.githubusercontent.com/7872518/206392137-fee2e30e-4435-47a7-b717-719cc602a4f8.png)

**Comment by m4dm4rtig4n** [comment]
Juste un détail les call ecowatt et tempo ne sont pas soumis à l'authentification étant de la données public.

**Comment by Nackophilz** [comment]
> Aurais-tu une copie ecran de l'erreur ? Un traceback?

Yes voici ce que j'ai dans les logs : 

2022-12-08 10:49:10.909 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/myEnedis/config_flow.py", line 91, in async_step_user
    return self._show_setup_form(user_input, self._errors)
  File "/config/custom_components/myEnedis/config_flow.py", line 60, in _show_setup_form
    default=user_input(CONF_SERVICE_ENEDIS, serviceEnedis)
TypeError: 'dict' object is not callable

**Comment by saniho** [comment]
merci pou rle log, j'ai corrigé et livré la pre release 2.0.2..si tu peux tester et me tenir informé

**Comment by Nackophilz** [comment]
Je n'ai plus l'erreur 500 par contre je n'arrive pas à initialiser l'intégration 

MyElectrical DATA, nous fourni notre numéro PDL + Notre Token

Dans le paramétrage tu demande : 

Le Token 
Le Code --> a quoi cela correspond t-il ? :)

**Comment by Nackophilz** [comment]
Ok je vois pourquoi j'ai pas de remontée 
Je masque mon token, mais sinon le reste est d'origine sur les logs ->


`2022-12-08 23:14:02.479 ERROR (SyncWorker_3) [myEnedis] ====== Appel http #17 !!! requests.exceptions.HTTPError
2022-12-08 23:14:02.479 ERROR (SyncWorker_3) [myEnedis] ************************************************************
2022-12-08 23:14:02.480 ERROR (SyncWorker_3) [myEnedis] header : {'Authorization': 'XXXXXXXXXXXXXX', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.0.2'} 
2022-12-08 23:14:02.481 ERROR (SyncWorker_3) [myEnedis] params : None 
2022-12-08 23:14:02.481 ERROR (SyncWorker_3) [myEnedis] data : {"type": "daily_production", "usage_point_id": "09741389273948", "start": "2022-12-07", "end": "2022-12-08"} 
2022-12-08 23:14:02.482 ERROR (SyncWorker_3) [myEnedis] Error JSON : {"detail":"Le sens de la mesure ne correspond pas pour le PRM demandé"} 
2022-12-08 23:14:02.482 ERROR (SyncWorker_3) [myEnedis] ************************************************************
2022-12-08 23:14:02.483 ERROR (SyncWorker_3) [myEnedis] Data answer: {'detail': 'Le sens de la mesure ne correspond pas pour le PRM demandé'}`

**Comment by saniho** [comment]
@Nackophilz accepterais tu de m'envoyer par mail ton token pour que je puisse reproduire le problème. Mon sanihogithub@gmail.com

**Comment by m4dm4rtig4n** [comment]
L'erreur de @Nackophilz c'est parce que l'intégration demande de récupéré la "production" et qu'a priori le point de livraison n'est as pas.
=> {"detail":"Le sens de la mesure ne correspond pas pour le PRM demandé"}

**Comment by Nackophilz** [comment]
@saniho pas de soucis, mais le token ne sera surement pas suffisant si?

**Comment by saniho** [comment]
Si tu peux l'envoyer je pourrais faire un check.

**Comment by saniho** [comment]
@Nackophilz  : si tu peux m'envoyer ton token en privée..

**Comment by Nackophilz** [comment]
> @Nackophilz : si tu peux m'envoyer ton token en privée..

Ah Yes pardon ça m'était complètement sorti de la tête ^^ 
Je t'envoi sa en PV :)

**Comment by Nackophilz** [comment]
Oh ! 

Je viens de jeter un oeil ce matin  ! 

Et j'ai plus de soucis :  

<img width="360" alt="image" src="https://user-images.githubusercontent.com/61667226/206842588-84b0d18b-1ffe-4b7a-92aa-c948a1e12e73.png">

<img width="598" alt="image" src="https://user-images.githubusercontent.com/61667226/206842599-9453d079-444b-4aa5-9724-7d6cea7d4328.png">

Toutes les infos remonte bien , erreur temporaire ENEDIS peut être ?

**Comment by saniho** [comment]
@m4dm4rtig4n  : as-tu remis le header specifique pour permet de depasser le quota de 50 pour mes tests ?

**Comment by m4dm4rtig4n** [comment]
> @m4dm4rtig4n : as-tu remis le header specifique pour permet de depasser le quota de 50 pour mes tests ?

Ah nous j'ai zapper pour le coup, j'essaie de te faire ca rapidement.

**Comment by saniho** [comment]
@m4dm4rtig4n  : j'ai le message : Pas de consentement détecté sur le point de livraison 
et impossible d'en redemander un( meme si pas normal que celui d'avant soit éperimé" ), car le site enedis HS

**Comment by m4dm4rtig4n** [comment]
> @m4dm4rtig4n : j'ai le message : Pas de consentement détecté sur le point de livraison et impossible d'en redemander un( meme si pas normal que celui d'avant soit éperimé" ), car le site enedis HS

J'ai fait une mep ce weekend qui as mit en caraf le renouvellement des refresh_token.
L'impact est que les consentements sont HS après l'expiration du 1er token fournis par Enedis...

J'aimerais bien debug sauf qu'avec le site d'Enedis HS + Sandbox arrêté la nuit je suis bloqué...

Bref je te tiens au courant.

**Comment by saniho** [comment]
Hello des bonnes nouvelles ?

**Comment by m4dm4rtig4n** [comment]
> Hello des bonnes nouvelles ?

Oui c'est bon excuse j'ai oublier de te prevenir...
Tt est de nouveau opérationnel.

**Comment by saniho** [comment]
Hello idem pour le header ? Meme nom qu'avant ?

**Comment by foXaCe** [comment]
Bonjour @saniho 
Serait t'il possible d'afficher aussi la production dans la nouvelle version de ta carte ?
Merci

**Comment by saniho** [comment]
si tu peux me donner ton pdl et token( enedisgateway ) en privé .. je peux regarder ...

**Comment by foXaCe** [comment]
ok
mail ?

**Comment by saniho** [comment]
sanihogithub@gmail.com

**Comment by saniho** [comment]
@m4dm4rtig4n merci
juste un point avant je pouvais recupérer l'historique par jour sur une longue periode, avec myelectriData ce n'est plus possible, est-il possible de la remettre en place?
ERROR:myEnedis:data : {"type": "daily_consumption", "usage_point_id": "xxx", "start": "2022-01-01", "end": "2022-12-19"} 
ERROR:myEnedis:Error JSON : {"detail":"Il est possible de recevoir au maximun 36j de donnÃ©es consÃ©cutives. Merci de split vos demandes"}

**Comment by m4dm4rtig4n** [comment]
Euh, a moins que j'ai bu trop d'eau ce soir cette limitation à tjr exister car c'est une limitation d'Enedis.

Par contre, si je ne dit pas de bétise :
{"type": "daily_consumption", "usage_point_id": "xxx", "start": "2022-01-01", "end": "2022-12-19"}
C'est l'ancien endpoint (ou le /api deprecated de myelectricaldata qu'il ne faut pas intégrer)

Je te conseille d'intégrer les autres car le endpoint va probablement disparaitre en même temps qu'EnedisGateway.tech.

**Comment by saniho** [comment]
non, c'est bien avec la nouvelle : 'https://www.myelectricaldata.fr/daily_consumption/xxx/start/2022-01-01/end/2022-12-20/
et je te confirme avant cela fonctionnait avec enedisgateway .. et j'ai refait le test, çà fonctionne toujours ;)
Ce qui me gene, c'est que au premier lancement il recupère plusieurs mois d'historique, donc si je fais un call par mois, au premier lancement, je vais exploser le compteur d'appel par jour

**Comment by saniho** [comment]
> @saniho sur la prochaine MEP de la passerelle MyElectricalData, il sera possible de récupérer les jours Tempo d'EDF ainsi que les données d'Ecowatt si tu désire les intégrer dans la card.

Hello @m4dm4rtig4n , sur ces deux endpoint, j'ai pas de retour, un soucis ?

![image](https://user-images.githubusercontent.com/52693545/208763800-9187fd5c-0f45-414f-88f8-4ad67d6cd349.png)

**Comment by m4dm4rtig4n** [comment]
> > @saniho sur la prochaine MEP de la passerelle MyElectricalData, il sera possible de récupérer les jours Tempo d'EDF ainsi que les données d'Ecowatt si tu désire les intégrer dans la card.
> 
> Hello @m4dm4rtig4n , sur ces deux endpoint, j'ai pas de retour, un soucis ?
> 
> ![image](https://user-images.githubusercontent.com/52693545/208763800-9187fd5c-0f45-414f-88f8-4ad67d6cd349.png)

J'ai un cron qui normalement s'execute tt les jours pour synchro, mais j'ai remarquer qu'il y avait un soucis avec celui-ci...

> non, c'est bien avec la nouvelle : 'https://www.myelectricaldata.fr/daily_consumption/xxx/start/2022-01-01/end/2022-12-20/ et je te confirme avant cela fonctionnait avec enedisgateway .. et j'ai refait le test, çà fonctionne toujours ;) Ce qui me gene, c'est que au premier lancement il recupère plusieurs mois d'historique, donc si je fais un call par mois, au premier lancement, je vais exploser le compteur d'appel par jour

Bizarre car j'ai plus aucun souvenir de cette fonctionnalité oO
Pour moi les call ont tjr était brider avec les mêmes limites que celle d'Enedis.

Après si tu active le cache sur la passerelle (avec tt les endpoint qui finissent par /cache) tu as le droit à 500 call / jour et donc de quoi remplir tt l'historique en une fois normalement.

**Comment by saniho** [comment]
En activant le cache, çà n'empechera pas le fait qu'il faille plusieurs jours pour pouvoir recupérer l'historique ;( et tout le monde ne voudras pas du cache...
Ce qui est étonnant, c'est que avant Enedis ne bloquait pas, tu es sur que c'est bloqué ?

**Comment by m4dm4rtig4n** [comment]
Enedis à tjr bloquer, les textes que tu retrouve dans le swagger ce sont directement ceux que j'ai reprit de la doc d'Enedis pour le coup.

Extrait de leur doc :

![image](https://user-images.githubusercontent.com/7872518/208774627-167426c9-ea78-496c-a61a-6e615eea0e5a.png)

Après je ne veut pas forcer les gens à utiliser le cache, mais je les encourage fortement pour eviter de saturer les services d'Enedis qui bride pas mal le nombre de demande (5 query / s max pour la totalité des utilisateurs de la passerelle).

C'était aussi une demande de leur part de le mettre en place sur ma passerelle car leur infra à dû mal à suivre la cadence :/

**Comment by saniho** [comment]
si je lit la doc, c'est 36 mois et 15 jours avant la date d'appel, la dans mon test, je suis sur : 

ERROR:myEnedis:data : {"type": "daily_consumption", "usage_point_id": "xxx", "start": "2022-01-01", "end": "2022-12-19"}
ERROR:myEnedis:Error JSON : {"detail":"Il est possible de recevoir au maximun 36j de donnÃ©es consÃ©cutives. Merci de split vos demandes"}
bizarre l'erreur : 36 jours vs dans la doc 36 mois ... il serait pas là le soucis ?

**Comment by m4dm4rtig4n** [comment]
Tu me met le doute :D

**Comment by m4dm4rtig4n** [comment]
Sur le mode détaillé c'est bloquer à 7j en tout cas c'est sûr :

![image](https://user-images.githubusercontent.com/7872518/208775429-7b46d78b-f298-444b-a684-e6256f0971c8.png)

Mais sur le daily il me semblais que c'était 1 mois, mais je me suis peut être tromper pour le coup...

**Comment by m4dm4rtig4n** [comment]
Bon pour ecowatt quand tu laisse un resultat de test dans le code ca marche moins bien... XD

![image](https://user-images.githubusercontent.com/7872518/208780708-5a39137e-da01-4f30-bd61-a5cc8db0e492.png)

**Comment by m4dm4rtig4n** [comment]
@saniho sur le daily, je viens de basculer sur 1095j max.

**Comment by saniho** [comment]
Hello @m4dm4rtig4n , pour information ce midi, j'ai eut des erreurs, alors que hier il fonctionnait
message : Pas de consentement détecté sur le point de livraison xxxx, merci de les faire sur https://www.myelectricaldata.fr
un soucis ?

**Comment by m4dm4rtig4n** [comment]
Bizarre normalement j'ai pas eu de soucis particulier sur la passerelle pourtant :/
Dit tu arrive à ecrire de la donnée dans le temps avec ton intégration ?

Du style crée une valeur d'un sensor à un instant T ?

**Comment by saniho** [comment]
Désolé j'ai pas compris, tu veux dire ecrire un sensor à un instant t avec t dans le passé ?

**Comment by saniho** [comment]
> Bizarre normalement j'ai pas eu de soucis particulier sur la passerelle pourtant :/

j'ai refait un consentement et c'est reparti .. strange

**Comment by m4dm4rtig4n** [comment]
> Désolé j'ai pas compris, tu veux dire ecrire un sensor à un instant t avec t dans le passé ?

C'est ça 😁

**Comment by saniho** [comment]
J'avais demandé aux archis de HASS et non, ce n'est pas possible, ils n'ont pas prevu de faire des sensors sur le "passé" ;(

**Comment by m4dm4rtig4n** [comment]
Et sur ton sensor history tu envoie la valeur tt les 30min avec un delta d'1 jour ?

**Comment by saniho** [comment]
oui toutes les 30 minutes, mais avec 2 jours, car à J+1 c'est trop juste dès fois

**Comment by saniho** [comment]
myelectricData availabe in last pre-release
