### ISSUE TITLE
Ajouter le support des heures creuses en fonction des jours

### ISSUE THREAD

**Issue by jmarginier** [saniho/apiEnedis#2]
Exemple : Il y a des contrats ou les heures creuses sont appliquées toutes la journée le WE.
Constat: La configuration actuelle ne permet pas d'avoir cette gestion (même configuration pour chaque jour)
Résultat: L'estimation est faussée

Demande : possibilité le champ "heures_creuses" en fct des jours de la semaine.

PS : Merci pour ce plugin ! beau travail

**Comment by saniho** [comment]
hello, si tu peux m'envoyer par mp ton token et ton PDL( sur hacf par exemple ), cela me permettra d'avoir accès aux données.
En fait, j'ai possibilité d'avoir les elements en interrogant Enedis, mais comme j'ai pas de contrat comme le tien, je n'ai pas idée de la sturcture de la réponse et cela sera plus "automatisé que de forcer les données par jour

**Comment by jmarginier** [comment]
> hello, si tu peux m'envoyer par mp ton token et ton PDL( sur hacf par exemple ), cela me permettra d'avoir accès aux données.
> En fait, j'ai possibilité d'avoir les elements en interrogant Enedis, mais comme j'ai pas de contrat comme le tien, je n'ai pas idée de la sturcture de la réponse et cela sera plus "automatisé que de forcer les données par jour

encore faut il la possibilité de MP :)

**Comment by saniho** [comment]
ici, via message direct : https://forum.hacf.fr/u/saniho/summary

**Comment by saniho** [comment]
pas de token/PDL pour checker :(

**Comment by jmarginier** [comment]
je me suis inscrit sur le site....mais il faut rentrer dans la communauté pour pouvoir faire des messages directs...
