### ISSUE TITLE
Problème avec le core 2022.12.1

### ISSUE THREAD

**Issue by WarC0zes** [saniho/apiEnedis#200]
Bonjour,
j'ai mis a jour le core en version 2022.12.1 et au reboot je n'est plus d'information sur la carte. L'entité général n'affiche plus aucune information, juste le statut. On dirait qu'il y a une problème avec les attributs des entitées.
Je suis en version 1.5.1 d'apiEnedis.

erreur dans le log:
```
Logger: homeassistant
Source: custom_components/myEnedis/sensorEnedis.py:116
Integration: MyEnedis ([documentation](https://github.com/saniho/apiEnedis/), [issues](https://github.com/saniho/apiEnedis/issues))
First occurred: 11:03:51 (2 occurrences)
Last logged: 11:05:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 83, in _async_update
    self._update_state()
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 114, in _update_state
    status_counts, state = self._myDataSensorEnedis.getStatus(self._typeSensor)
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 198, in getStatus
    status["versionUpdateAvailable"] = self.getExistsRecentVersion(
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 116, in getExistsRecentVersion
    gitVersionObj = packaging.version.parse(versionGit)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```
![apienedis](https://user-images.githubusercontent.com/91471397/206678525-0d392160-6603-4077-a61b-236e3c4cd47d.png)
![apienedis2](https://user-images.githubusercontent.com/91471397/206679869-99aa65b5-f39b-4695-891f-87f0e1fd8e18.png)

**Comment by Lajull-fr** [comment]
Pareil pour moi

**Comment by WarC0zes** [comment]
A plus rien comprendre, j'ai désactiver l'intégration pendant quelque heures car une message dans les logs apparaisser souvent.
J'ai fait des mises a jour d'intégration et de carte. J'ai reboot et relancer l'intégration que j'avais désactiver et magie ca re fonctionne.
![apienedis3](https://user-images.githubusercontent.com/91471397/206743341-e9ef6f0f-26b5-48a0-b746-7365ebe3f63f.png)

**Comment by saniho** [comment]
en effet etonnant, si tu arrives à reproduire le probleme, je suis preneur

**Comment by louisjeck** [comment]
Pareil pour moi, j'ai découvert cette intégration aujourd'hui, donc dernière version de l'intégration et de home assistant. Sur RPI 4.

**Comment by WarC0zes** [comment]
J'ai juste reboot HA et ca re-bug. J'ai rien fais depuis que ce refonctionner, juste un soft reboot.
```
Logger: homeassistant
Source: custom_components/myEnedis/sensorEnedis.py:116
Integration: MyEnedis ([documentation](https://github.com/saniho/apiEnedis/), [issues](https://github.com/saniho/apiEnedis/issues))
First occurred: 03:49:48 (3 occurrences)
Last logged: 03:53:05

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 83, in _async_update
    self._update_state()
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 114, in _update_state
    status_counts, state = self._myDataSensorEnedis.getStatus(self._typeSensor)
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 198, in getStatus
    status["versionUpdateAvailable"] = self.getExistsRecentVersion(
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 116, in getExistsRecentVersion
    gitVersionObj = packaging.version.parse(versionGit)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by mdeweerd** [comment]
C'est sûrement la récupération del a version git qui pose problème - lié aux avertissement d'un appel "bloquant" (je n'ai plus le message exact car je n'utilise plus apiEnedis.

**Comment by DynaFab** [comment]
> J'ai juste reboot HA et ca re-bug. J'ai rien fais depuis que ce refonctionner, juste un soft reboot.
> 
> ```
> 
> Edit: J'ai trouver une solution. Quand ca fonctionne pas, je désactive l'intégration MyEnedis , je reboot HA et réactive l'intégration et les entités refonctionnent bien avec tout les attributes.

Même erreur et Merci [WarC0zes](https://github.com/WarC0zes) pour la solution provisoire

**Comment by qgouebault** [comment]
> Edit: J'ai trouver une solution. Quand ca fonctionne pas, je désactive l'intégration MyEnedis , je reboot HA et réactive l'intégration et les entités refonctionnent bien avec tout les attributes.

ça ne fonctionne pas chez moi :(
Toutes les entitées restent en indisponibles

**Comment by Pepeanuts** [comment]
Stop intégration, reload HA, start intégration a fonctionné pour moi

**Comment by LGO44** [comment]
> Edit: J'ai trouver une solution. Quand ca fonctionne pas, je désactive l'intégration MyEnedis , je reboot HA et réactive l'intégration et les entités refonctionnent bien avec tout les attributes.

Même souci mais le reboot ne marche pas....

**Comment by saniho** [comment]
#201

**Comment by WarC0zes** [comment]
Bonjour @saniho,
la pre-release v2.0.3 fix le problème, j'ai mis a jour et reboot et c'est bon même pour la passerelle Enedis gateway ( j'ai pas migrer encore).
Merci beaucoup.
