### ISSUE TITLE
Setting window doesn't display all the information

### ISSUE THREAD

**Issue by LGO44** [saniho/apiEnedis#202]
Version : 2.0.2
In the setting window I have no information about the settings, like a blind man I make the setting like in the previous version but I cannot choose wether enedisgateway or myelectricaldata I have the  same result with safari or firefox on a mac and with edge or firefox on Windows.

![image](https://user-images.githubusercontent.com/95585425/207170198-e9364915-8a2b-441a-b916-60f75bdaf89f.png)

**Comment by saniho** [comment]
Try again after a ctrl + f5

**Comment by LGO44** [comment]
I had already done it.
I do it again with the same result, sorry.

**Comment by saniho** [comment]
can you test with the pre release 2.0.3 ?

**Comment by geobar78** [comment]
@saniho not exactly the same but no way to choose Myelectricaldata, only see enedisgateway v2.0.3

![image](https://user-images.githubusercontent.com/75928935/208149120-82974817-34d7-4ae0-92b7-d39cbc222770.png)

**Comment by LGO44** [comment]
For me, on my running platform it's OK  but on my development platform it's alway the same.

**Comment by LGO44** [comment]
Suppress the yaml file was a very good thing but as we have this kind of issue it's not possible to test your great job.
Is it possible to have an yaml configuration file to test all the features?

**Comment by saniho** [comment]
> Suppress the yaml file was a very good thing but as we have this kind of issue it's not possible to test your great job.
> Is it possible to have an yaml configuration file to test all the features?

Hi @LGO44, si tu veux participer au projet ce sera avec plaisir !

**Comment by LGO44** [comment]
Bien sur si je peux aider de quelque manière que ce soit , ce sera avec plaisir

**Comment by LGO44** [comment]
> @saniho not exactly the same but no way to choose Myelectricaldata, only see enedisgateway v2.0.3
> 
> ![image](https://user-images.githubusercontent.com/75928935/208149120-82974817-34d7-4ae0-92b7-d39cbc222770.png)

Je n'avais pas prêté attention mais c'est la même chose sur mon HA en version 2.0.3

**Comment by saniho** [comment]
En effet pour le moment myelectricdata n'est pas active ... Mais d'ici peu cela viendra ;)
