### ISSUE TITLE
EcoWatt

### ISSUE THREAD

**Issue by saniho** [saniho/apiEnedis#212]
Ecowatt : 
![image](https://user-images.githubusercontent.com/7872518/206392137-fee2e30e-4435-47a7-b717-719cc602a4f8.png)

_Originally posted by @m4dm4rtig4n in https://github.com/saniho/apiEnedis/issues/198#issuecomment-1342234737_

**Comment by saniho** [comment]
@m4dm4rtig4n : que penses-tu de cela pour ecowatt ?

![image](https://user-images.githubusercontent.com/52693545/209584837-364a4e6e-dc8b-4e80-a051-865ce12b0a9d.png)

**Comment by m4dm4rtig4n** [comment]
Sympa !
Je mettrais juste des couleurs un peu plus dans le style "material design" moins agressive.
