### ISSUE TITLE
[MyElectricalData] Daily Max Power disponible!

### ISSUE THREAD

**Issue by m4dm4rtig4n** [saniho/apiEnedis#213]
Hello Saniho,

Pour information j'ai également intégre un endpoint pour récupérer la puissance maximun journaliére.

![image](https://user-images.githubusercontent.com/7872518/209811668-6f787359-cbd7-4440-bc97-5693a68ca4b4.png)

Libre à toi de l'intégrer dans la card :)

**Comment by saniho** [comment]
ps c'est deja intégré ;)
