### ISSUE TITLE
saisie configuration en aveugle version 2.3.0

### ISSUE THREAD

**Issue by LGO44** [saniho/apiEnedis#220]
je rencontre un problème d'écran de configuration de l'intégration myenedis , je dois paramétré en aveugle. Je ne peux pas sélectionner la provenance des données myelectricaldata ou enedisgateway...
j'ai bien sur vide les caches des navigateurs (edge, firefox, safari ) mais rien n'y fait
HA tourne sur une machine virtuelle en toutes dernières versions...
myenedis crée 8 entités au lieu de 10 comparaison avec une autre instance HA sur Raspberry.
la création est très longue.

![af443669bd62569f00e834202e748e3d2f3d0332](https://user-images.githubusercontent.com/95585425/210887006-4b063bde-15bb-4b14-8534-276742d44927.png)

**Comment by r-jean-pierre** [comment]
Bonjour,

Je confirme que l'initialisation est "lente". Dans les logs, on voit une douzaine de fois "INFO (SyncWorker_2) [myEnedis] ====== Appel http #13 !!! =====" qui semble dire et faire la même chose

Ca finit bien par un "INFO (MainThread) [myEnedis] *** FIN SENSOR ***" et l'intégration semble fonctionnelle

Sinon, de mon coté, c’est en voyant le warning de la card que j'ai fait la procédure pour passer de enedisgateway à myelectricaldata. J'ai pu donc reconfigurer l'intégration "facilement": il suffisait de choisir le radiobutton et de mettre la nouvelle clé d'accès

J'ai bien les 10 entités et avec quelques minutes de recul , il me semble que ça fonctionne et que la card hacs affiche bien ce qu'il faut (sauf si c'est un cache de enedisgateway (?))

**Comment by LGO44** [comment]
Après avoir tout désinstaller, myenedis, myelectricaldata puis supprimer les repertoires dans custom components et réinstaller  une énième fois c'est bon maintenant.
