### ISSUE TITLE
"La page demandée n'existe plus"

### ISSUE THREAD

**Issue by EryxFR** [saniho/apiEnedis#226]
Bonjour, 
Quand on suit le lien vers le site enedis en bas de la page "enedisgateway" ou sur la page "myelectricaldata", on tombe sur une belle erreur 404, indiquant que la page n'existe pas. 
Suis-je le seul à avoir ce probleme? 

Merci

**Comment by cherjr** [comment]
Il m'arrive la même chose

**Comment by Avent89** [comment]
Problème corrigé du côté de Enedis. L'api était en rade depuis plusieurs semaines

**Comment by Upperfic2002** [comment]
Toujours en rade aujourd'hui

**Comment by Shasdo** [comment]
J'essaye depuis 1 semaine et c'est en rade.

Est-ce que ça a marché entre temps @Upperfic2002 ?

**Comment by Upperfic2002** [comment]
> J'essaye depuis 1 semaine et c'est en rade.
> 
> Est-ce que ça a marché entre temps @Upperfic2002 ?
> 
> Edit:
> 
> En rade depuis un moment, la faute à Enedis : [MyElectricalData/myelectricaldata#372](https://github.com/MyElectricalData/myelectricaldata/issues/372)

C'est bon pour moi ! Mon dns local bloquait la requête
Change de DNS si tu as un dns local mets 8.8.8.8 c'est nickel
