### ISSUE TITLE
[HA][DOWN] L'intégration ne fonctionne plus

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [saniho/apiEnedis#230]
Bonsoir,

Ceci est une repost de mon message sur le Discord API Enedis / gateway, et les devs qui sont gentillement dispo là bas :) (merci à eux)

---

[... blabla ...]

J'ai toujours un souci sur l'intégration HA ;

La demande de consentement a été faite une dizaine de fois (à chaque fois avec un test CLI + apiEnedis intégration HA, le CLI fonctionne, l'intégration HA ne fonctionne pas/ crash), et l'extension Home Assistant me renvoi toujours dans ses logs que le PDL ou le token ne correspondent pas... (là ou en CLI cela fonctionne bien)

Je vous met le maximum de screenshot possible pour l'aide à la compréhension de l'erreur, moi je ne comprend pas ...

---

J'utilise cette intégration home assistant : https://github.com/saniho/apiEnedis (version 2.3.0 - latest stable)
J'ai tenté avec l'option de l'intégration 'myelectricitydata' (token+PDL récupérés en validant la demande de consentement sur https://www.myelectricaldata.fr/) et l'option de l'intégration 'myenedisgateway' (token+PDLrécupérés en validant la demande de consentement sur https://enedisgateway.tech/), mais aucun n'a fonctionné
Je suis sur un home assistant : Home Assistant 2023.3.6 Frontend 20230309.1 - latest (installé dans une Docker image)
+ cela fonctionnait pendant 1 an / auparavant, du au changement de token/renouvellement consentement, ça ne fonctionne plus... 😦

![image](https://github.com/saniho/apiEnedis/assets/8619233/31377b5e-58db-4a6f-b8d2-493a562bf578)
![image](https://github.com/saniho/apiEnedis/assets/8619233/95cc8658-f56d-45d4-884a-6cb327438a62)
![image](https://github.com/saniho/apiEnedis/assets/8619233/24eac759-72f1-4c8d-8225-6f713808c294)
![image](https://github.com/saniho/apiEnedis/assets/8619233/058fd6ea-2a4c-45b2-9700-7137a151f9e0)
![image](https://github.com/saniho/apiEnedis/assets/8619233/ffb161f2-d9f7-4a90-8614-1652d5880076)
![image](https://github.com/saniho/apiEnedis/assets/8619233/a2c0c500-073a-4404-be73-0512e87dee69)

Les appels CURL copier/coller que fournissent les 2 sites suite à la demande de consentement réussi, semblent parcontre bien me retourner mes données de consommation ! L'intégration HA serait-elle en cause ? (Ce serait le plus probable)
![image](https://github.com/saniho/apiEnedis/assets/8619233/068d4b9e-260b-4b1b-ab54-0a456685dbda)
![image](https://github.com/saniho/apiEnedis/assets/8619233/6034c25f-65f1-4481-8520-c14707115430)

**Comment by Pmar13** [comment]
Il faut que tu coches Enedis Gateway dans la boite de dialogue MyEnedis Option

**Comment by BetterToAutomateTheWorld** [comment]
MyEnedisGateway est en end of support et va probavblement totalement disparaitre cette année

Il vaut mieux utiliser MyElectricityData, ducoup, en prévision :)

Je ne sais pas par quelle miracle, mais au bout de 10 essais ça a fonctionné : 
![image](https://github.com/saniho/apiEnedis/assets/8619233/c76b3486-3753-4f1f-82cd-a4a508bf60d7)
![image](https://github.com/saniho/apiEnedis/assets/8619233/630cee73-43d3-4515-92a8-e20256fa4743)

Je ferme le ticket, merci pour ta réponse ! :)
