### ISSUE TITLE
API HS ou Mauvaise config ?

### ISSUE THREAD

**Issue by TweakFurryFR** [saniho/apiEnedis#233]
L'api fonctionnais hier super bien, Puis apres un redemarrage plus rien ne s'affiche,
Est ce HS, Ou ai je fait une mauvaise config ?
![Capture d’écran 2023-08-17 213510](https://github.com/saniho/apiEnedis/assets/142539040/a2d03447-ccda-499a-a2fb-91755f37a66e)
![Capture d’écran 2023-08-17 213450](https://github.com/saniho/apiEnedis/assets/142539040/f53883b8-416b-4a64-a306-5556e28ae63e)

**Comment by Link0Darck** [comment]
Nan j'ai crus aussi mais c'est Enedis qui as des problèmes

**Comment by aeliyos** [comment]
Bonjour,

C'est un soucis de MAJ chez Enedis : [https://myelectricaldata.fr/](https://myelectricaldata.fr/)

Il faut patienter jusqu'au 25 septembre.

**Comment by Link0Darck** [comment]
> Bonjour,
> 
> J'ai la même chose et c'est un soucis de MAJ de l'API v5 chez Enedis : https://myelectricaldata.fr/
> 
> Par contre vu la date du post, pas sûre que le problème soit identique, là il faut patienter jusqu'au 25 septembre.

Bonjour,
J'ai remarquer qu'il beaucoup coupure pour dire des fois une ou deux semaine j'ai plus rien et après ça revient

**Comment by Link0Darck** [comment]
Bonjour,
j'ai vue ce message sur le site car moi ça fait depuis le 21 septembre 2023 que je n'ai plus rien en consommation.

**ATTENTION, grosse instabilité du service à cause de la migration vers les API v5 d'Enedis qui sont en cours depuis le 17/09/2023.

Les consentements sont indisponibles pour l'instant, merci de patienter jusqu'à la fin de la maintenance d'Enedis normalement prévu pour le 25/09/2023.**

voila le problème c'est l'api faut patienter après si le message il y est plus et vous avez toujours pas avec vous respecter les condition :

dans **Gérer l’accès à mes données** avez vous autoriser **Collecte de la consommation horaire**

Cordialement
Link_Darck

**Comment by Link0Darck** [comment]
Les valeurs sont revenue !
