### ISSUE TITLE
Code and card is not within HACS

### ISSUE THREAD

**Issue by Spifthespa** [saniho/apiEnedis#24]
Hi I am running last version 2020.12.2 - Your integration is not in HACS. Did I do something wrong?
I tried to install it manually but, after reboot,  I do not get the sensor MyEnedis. Quite strange. Any idea ?
Regards

**Comment by saniho** [comment]
to have the integration in HACS, you need to add manualy the git in the HACS menu
![image](https://user-images.githubusercontent.com/52693545/103382495-8a212800-4aef-11eb-9719-475fd9ee6130.png)
![image](https://user-images.githubusercontent.com/52693545/103382530-acb34100-4aef-11eb-80d8-d133ea31b21a.png)
and after :
![image](https://user-images.githubusercontent.com/52693545/103382560-d1a7b400-4aef-11eb-977e-9eda3b87220d.png)

**Comment by Spifthespa** [comment]
Hi thanks for prompt answer. It seems we have not the same interface. 
Strange ! I run HA on a PI3+

Regards

-- 
Patrice Deschilder
37 rue des Narcisses
13320 Bouc-bel-Air
06 23 30 17 39

**Comment by Spifthespa** [comment]
Hi,

Eventually found it in menu  top right corner of HACS - was not obvious; 
Thanks

Patrice
