### ISSUE TITLE
[Advices] About the project itself

### ISSUE THREAD

**Issue by kevincaradant** [saniho/apiEnedis#28]
Hi

Your project is really nice and I want to start to say thank you for it ;). Good job buddy !

I know it's a french project. I know it's more easy to write it with our fluent language (I'm french my self).

However, I read it quickly (I'm a dev but not a python developper so I will not to be a huge help for this :P)

Just to help you and help the next / contributors, you really should try to write EVERYTHING in English .

Files name should always have the same behavior / rules =>  `messages.py` and not  `Messages.py` for example. 
Same thing for the variables name in the different files of the project.

Issues (answer of issues in English if you can, it would be a good point for other people ), code and comments all english could be very useful). 
I saw a lot of french comments.

Please, if you add some / remove / edit a feature or a behavior of your plugin, update the README or the documentation about your plugin ;)

Hoping you will take in account of this, because it could be useful for the "plugin survival" if you are not always here to keep it alive :)

**Comment by saniho** [comment]
Good remarks, will do this for the next .. and try to correct the previous ;)
