### ISSUE TITLE
HC non calcules

### ISSUE THREAD

**Issue by francodutch** [saniho/apiEnedis#29]
super travail, merci! Helas je ne retrouve pas mes conso HC. Voici ma config:

platform: myEnedis
token: !secret enedisGateway_token
code: !secret enedisGateway_code
heures_creuses: "[[ '03:00', '08:00'], [ '13:30', '16:30']]"
hc_cout: 0.1131
hp_cout: 0.1482
scan_interval: 3600

Puis le contenue du sensor.myenedis_#############

attribution: ''
version: 1.1.0.1
typeCompteur: consommation
lastUpdate: '2021-01-02T17:19:34.135888'
timeLastCall: '2021-01-02T17:19:34.135570'
yesterday: 47901
last_week: 266278
day_1_HP: 47901
day_2_HP: 58597
day_3_HP: 66319
day_4_HP: 33623
day_5_HP: 37260
day_6_HP: 44884
day_7_HP: 33634
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0

**Comment by welcoMattic** [comment]
Bonjour,

Je rencontre exactement le même problème. Toutes mes HC sont à 0 dans les données remontées par le plugin, mais pas dans mon compte Enedis

**Comment by saniho** [comment]
pourriez-vous me fournir votre token et PDL en mp sur hacf ... à defaut à mon mail de contact

**Comment by francodutch** [comment]
> pourriez-vous me fournir votre token et PDL en mp sur hacf ... à defaut à mon mail de contact

done

**Comment by BUGgs** [comment]
J'ai le même pb : depuis le début, tout remonte dans les HP, et les HC sont à zéro.
Je peux re-fournir mon token si besoin (je vous l'avais déjà envoyé il y a qq semaines pour un autre pb...)

**Comment by saniho** [comment]
Merci, j'ai pu analyser, en fait enedis ne donne pas d'horaire HC/HP d'ou le fait que je ne peux l'utiliser.
Je vais voir pour l'ajouter à la configuration flow.
Par contre, si vous l'ajouter au sensor dans le yaml, est-ce que cela fonctionne ?

**Comment by BUGgs** [comment]
En regardant en détail les réponses renvoyées par Enedis, je n'ai en effet pas de trace de mon horaire HP/HC...
J'ai fonctionné avec le yaml avant, je mettais à la main les plages HC, et c'était pareil... Ce n'était pas pris en compte...

{"customer":{"customer_id":"-xxxxxx","usage_points":[{"usage_point":{"usage_point_id":"xxxxxx","usage_point_status":"com","meter_type":"AMM"},"contracts":{"segment":"C5","subscribed_power":"12 kVA","distribution_tariff":"BTINFMUDT","last_activation_date":"2017-07-28+02:00","contract_type":"Contrat GRD-F","contract_status":"SERVC","last_distribution_tariff_change_date":"2019-01-11+01:00"}}]}}

**Comment by francodutch** [comment]
D'après ce que j'ai compris ce n'est pas Enedis qui détermine les HC, mais le fournisseur. Je pensais d'ailleurs que c'était pour ça qu'il fallait inclure ces horaires dans la config, pour que le sensor classifie chaque plage horaire en HP ou HC:
# enedis linky
- platform: myEnedis
  token: !secret enedisGateway_token
  code: !secret enedisGateway_code
  heures_creuses: "[[ '03:00', '08:00'], [ '13:30', '16:30']]"
  hc_cout: 0.1131
  hp_cout: 0.1482
  scan_interval: 3600
Est-ce que j'ai tout faux?

**Comment by BUGgs** [comment]
Moi, il me semble que c'est plutôt Enedis qui définit les HC/HP... J'ai demandé justement à mon fournisseur mes tranches et il m'a répondu qu'il n'avait pas l'info... Seul Enedis pouvait me le donner...
Le pb, c'est que l'API Enedis ne le retourne pas sur mon contrat (alors que je les ai bien sur mes factures / relevés), et que même en mettant à la main dans le YAML, ce n'était pas pris en compte (testé dès le début avant que je ne passe sur la config flow cette semaine)... 
@saniho : En regardant ton code source, j'ai vu que tu recherche "offpeak_hours" dans les contracts... Hors, je n'en ai pas dans la réponse de l'API...Est-ce que ce n'est pas ça qui cause la non prise en compte des HP/HC ? Est-ce qu'on ne pourrait pas avoir un override manuel pour les contrats qui ne le spécifient pas ?

**Comment by saniho** [comment]
exactement @BUGgs !
LA derniere RC 1.1.2.0RC1 gere ce cas, si tu peux tester.
Pour prendre en compte tes HC/PH, il faut les definir dans le sensor de ton yaml

**Comment by francodutch** [comment]
je viens de tester cette version et malheureusement cela donne ceci:

https://paste.ubuntu.com/p/cWBzRPxSw3/

**Comment by saniho** [comment]
en effet, on tombe avec un soucis enedis :(... Essaye la derniere que je viens de livrer si tu peux....1.1.2.0RC2

**Comment by francodutch** [comment]
Ça a l'air beaucoup mieux, a part vendredi ou il y a un N petit triangle avec point d'exclamation. Je n'ai pas le temps de tester plus en profondeur ce soir. Merci!

**Comment by BUGgs** [comment]
En effet, c'est bon, j'ai bien l'historique des HP/HC maintenant avec la RC2 ! Top !

**Comment by francodutch** [comment]
c'est bon pour moi maintenant! Il faut que je vérifie les % hc/hp et les chiffres mais ca a l'air pas mal.

**Comment by ludoz** [comment]
Hello ! Super boulot ce sensor, merci :-)

Moi j'ai le probléme inverse depuis la RC2 toutes les consos passent sur HC : 
`day_1_HP: 0
day_2_HP: 0
day_3_HP: 0
day_4_HP: 0
day_5_HP: 0
day_6_HP: 0
day_7_HP: 0
day_1_HC: 12192
day_2_HC: 14978
day_3_HC: 10589
day_4_HC: 16196
day_5_HC: 10739
day_6_HC: 18792
day_7_HC: 17955`

J'ai ça comme config : 

`  heures_creuses: "['22:20', '06:20']"
  hc_cout: 0.1344
  hp_cout: 0.1798
  scan_interval: 3600`

Une idée du pb ?

Merci.

**Comment by saniho** [comment]
hello, en effet, ton "bug" est simple, il te suffit d'écrire les horaires de cette manière 
"['00:00','06:20','22:20', '24:00']"
Si tu as toujours le soucis, rouvre un nouveau ticket

**Comment by welcoMattic** [comment]
Pourquoi le paramètre des HC doit s'écrire sour la forme d'une chaine de caractères et pas en utilisant un tableau YAML ?
Ça serait beaucoup plus simple à comprendre pour tout le monde, et ça éviterai un parsing et ce genre d'erreur.

Dans mon cas j'ai 2 plages horaires de HC par jour (01:00 => 06:00 et 12:30 => 14:30), quelle syntaxe dois-je utiliser dans ce cas ? Avec un tableau, j'aurais sur sans problèmes
