### ISSUE TITLE
Coûts de chaque jour 

### ISSUE THREAD

**Issue by herveaurel** [saniho/apiEnedis#3]
Bonjour, et surtout merci pour ce travail extraordinaire ! 
Est-il possible d’avoir le coût en euro de chaque jour ?

**Comment by saniho** [comment]
hello @herveaurel , cette evolution viendra d'ici peu, je finalise l'integration des HC/HP directement depuis le contrat et le prix par jour, sera  la prochaine...

**Comment by saniho** [comment]
@herveaurel , pour information , la version beta permet cela : https://github.com/saniho/apiEnedis/tree/GetContractInformation/custom_components/apiEnedis
+ hacf : https://forum.hacf.fr/t/sensor-pour-enedis-apienedis/935/172
bon test

**Comment by herveaurel** [comment]
> @herveaurel , pour information, la version beta permet cela: https://github.com/saniho/apiEnedis/tree/GetContractInformation/custom_components/apiEnedis
> 
> * hacf: https://forum.hacf.fr/t/sensor-pour-enedis-apienedis/935/172 
>   bon test 
>   + installateur la dernière version de la carte depuis HACS ou vu depuis: [https://github.com/saniho / content-card-linky](https://github.com/saniho/content-card-linky)

Super je vais tester ! 
Je fais des templates et calculs pour récupérer des infos et les afficher dans des graphiques. Mais l’intégration de base serait superbe ! 👍🏼

**Comment by herveaurel** [comment]
Bonjour ! J’ai fait la dernière MàJ dispo aujourd’hui. 
Hélas les remontées ne se font pas... 
J’ai l’historique enregistré mais pas les remontées actuelles. 
Myenedis est « unknown » 
![Uploading AAACB6D8-312B-4E58-AE3D-5133901F5EE5.png…]()

**Comment by saniho** [comment]
hello, je n'ai pas accès à ton image :( ...as-tu dans le log de ha des informations ?
sinon, vu que parfois le site enedis est HS, je te conseil d'augmenter la frequence de ton sensor, genre 120 secondes( ps, il n'interrogera enedis que si la derniere 'est mal passé, les "bonne" mise à jour on tlieu par defaut toutes les 2 heures.

**Comment by herveaurel** [comment]
> hello, je n'ai pas accès à ton image :( ...as-tu dans le log de ha des informations ?
> sinon, vu que parfois le site enedis est HS, je te conseil d'augmenter la frequence de ton sensor, genre 120 secondes( ps, il n'interrogera enedis que si la derniere 'est mal passé, les "bonne" mise à jour on tlieu par defaut toutes les 2 heures.

Merci, mais j’avais déjà changer le rafraîchissement. Avant cette nouvelle MàJ les remontées fonctionnaient très bien. Là depuis la MàJ, rien. Le « unknown » est toujours l’état.

**Comment by herveaurel** [comment]
> hello, je n'ai pas accès à ton image :( ...as-tu dans le log de ha des informations ?
> sinon, vu que parfois le site enedis est HS, je te conseil d'augmenter la frequence de ton sensor, genre 120 secondes( ps, il n'interrogera enedis que si la derniere 'est mal passé, les "bonne" mise à jour on tlieu par defaut toutes les 2 heures.

![75BF02D0-CDAA-427F-ACDC-FA7F431D55F5](https://user-images.githubusercontent.com/64784541/100516626-7481b100-3185-11eb-9b46-858e9fbc6a93.png)

**Comment by herveaurel** [comment]
> hello, je n'ai pas accès à ton image :( ...as-tu dans le log de ha des informations ?
> sinon, vu que parfois le site enedis est HS, je te conseil d'augmenter la frequence de ton sensor, genre 120 secondes( ps, il n'interrogera enedis que si la derniere 'est mal passé, les "bonne" mise à jour on tlieu par defaut toutes les 2 heures.

![47BCC485-789C-4AAE-A434-FC76D515C583](https://user-images.githubusercontent.com/64784541/100517210-6897ee00-3189-11eb-859c-9e8a0a2040de.png)

**Comment by bran2000** [comment]
> Bonjour, et surtout merci pour ce travail extraordinaire !
> Est-il possible d’avoir le coût en euro de chaque jour ?



> Bonjour ! J’ai fait la dernière MàJ dispo aujourd’hui.
> Hélas les remontées ne se font pas...
> J’ai l’historique enregistré mais pas les remontées actuelles.
> Myenedis est « unknown »

Bonjour,

je confirme de mon côté également mon état est en unknown

**Comment by gogui63** [comment]
Salut et merci pour le super travail, voici quelques logs :

Logger: custom_components.myEnedis.sensor
Source: custom_components/myEnedis/apiEnedis.py:49
Integration: myEnedis
First occurred: 15:13:19 (5 occurrences)
Last logged: 16:13:30

Erreur inconnue call ERROR ('call', 'error', 'Internal Server error')
Erreur last answer ('call', 'error', 'Internal Server error')
updateYesterday
Erreur call ERROR ('call', 'error', 'Internal Server error')
updateCurrentMonth

Logger: custom_components.myEnedis.sensor
Source: custom_components/myEnedis/sensor.py:116
Integration: myEnedis
First occurred: 15:13:14 (2 occurrences)
Last logged: 16:13:19

call update

**Comment by saniho** [comment]
merci pour vos remontés, pourriez-vous me dire si c'est mieux avec la version du jour...sinon, pourriez-vous me fournir en mp vos token+pdl ?

**Comment by gogui63** [comment]
Bien joué c'est fix de mon côté 👍 il m'a récupérer heure pleine et heure creuse alors que je n'ai pas ce type de contrat mais c'est pas grave (pour débug je peux te mp mon pdl et token si tu veux)

**Comment by herveaurel** [comment]
J’ai fait la MàJ. 
Rien.... Ça n’a rien changé :(

**Comment by bran2000** [comment]
Suite à la mise je n’ai plus la card et aucune info qui remonte également

**Comment by herveaurel** [comment]
Myenedis est en unknown mais le reste semble ok... Bizarre. 
![3E6F9D60-82BB-4F71-911A-003E776614D5](https://user-images.githubusercontent.com/64784541/100536590-faebd080-3221-11eb-9dd6-a54583b5d651.png)

**Comment by saniho** [comment]
Merci pour vos remontés, une nouvelle version est disponible, elle devrait régler un certain nombre de vos soucis.
@gogui63 si tu veux bien me donner ton token et pdl en mp, c'est super, cela me fera un jeu de test supplementaire

**Comment by gogui63** [comment]
Impossible de te MP via hacf ... (Il faut que mon profil soit"certifié" genre lire 40 messages ou ouvrir 5 topic)

Je peux te mp comment ? @saniho

**Comment by herveaurel** [comment]
Bonjour @saniho, j’ai fait la MàJ. L’entité sensor.myenedis n’existe carrément plus ! Je ne m’attendais pas à celle là 😅
Je ne sais plus quoi tenter. A part remettre l’ancienne version.... 😢

**Comment by herveaurel** [comment]
Ce n’est pas le lieu... mais merci pour tout !!! 
Ça fonctionne ! 
![925872C1-6F86-4C6F-B0A6-F1306DBCF796](https://user-images.githubusercontent.com/64784541/100773095-b79b8880-3400-11eb-8caf-5b40c5573a08.png)
