### ISSUE TITLE
comparatif 1/01/2021

### ISSUE THREAD

**Issue by aladin2000** [saniho/apiEnedis#30]
bonjour
je viens de refaire un compartif avec les datas de Enedis données via leur application Et
 je m'interroge sur le constat suivant
Les % HP et HC ne seraient il pas inversés qq part ?

Voici les datas reprises depuis l'appli sur la journée du 1/1/2021 
 
HCreuses | 32   KwH  |  soit | 34,4% |  or data Myenedis    donne   | yesterday_HC: | 53243 | soit  57,3%
HPleines  | 61,1 KwH | soit 65,6% |  or depuis MyEnedis j'obtiens ceci   | yesterday_HP: | 39692 | soit  42,7%

Ce constat corrobore le même constat fait via l'appli EDF qui m'indique le ratio 60%HP et 40%HC 
Les erreurs de qq % s'expliquent probablement  par la non concordance des 1/2 heures 00 et 30  avec ma tarnche horaire HC/HP 00:22 et 01:52 ... mais pas dans un sens inverse je pense ....

Pourriez vous svpb re vérifier si il n'y aurait pas qqchose qui déconne  avec le ratio donné par MyEnedis  indiqué   à 43% HP   dans mon cas ?

**Comment by aladin2000** [comment]
Help, any idea ?

**Comment by kweebix** [comment]
J'ai un soucis aussi une différence de 40cts sur ma facturation entre EDF et apienedis

**Comment by saniho** [comment]
je viens de regarder 2/3 cas, et les elements sont bons.
Peut-etre est-ce du au fait que les heures HC/HP donné par Enedis ne sont pas celles de votre contrat avec un opérateur tiers.
Cela peut arriver. Pour cela il faut "forcer" votre HC/HP dans le yaml

**Comment by aladin2000** [comment]
Je viens de voir que ce soir les datas hier hp/hc semblent dans le bon sens
Je n'ai rien change. Car le yaml avait déjà les horaires de mon contrat
Je regarderai pour les jours à venir avant de clore le case

18 janv. 2021 21:23:37 saniho <notifications@github.com>:

**Comment by aladin2000** [comment]
Cest  Ok pour les 7 derniers jours 

Les compteurs sont tous dans le bon sens

Et le %HP est juste

Merci  on peut clore ce  case a priori


19 janv. 2021 00:33:49 Aladin <aladin@free.fr>:

**Comment by aladin2000** [comment]
""Pour cela il faut "forcer" votre HC/HP dans le yaml""
    heures_creuses: "[['00:52', '07:22'], ['12:22', '13:52']]"
 cela correspond bien aux datas en sortie de 
Enedis  
Offpeak hours enedis  HC (0H52-7H22;12H22-13H52)

Question il semble encore que le cumul jour HV soit a 0 en visu alors que le %HP est juste 

![image](https://user-images.githubusercontent.com/16690723/105064570-3fa32380-5a7d-11eb-9f50-fbd5b0b1910c.png)

**Comment by saniho** [comment]
Si le problème perdure, merci de me faire pervenir votre configuration de sensor dans le yaml en mp..

**Comment by aladin2000** [comment]
Bonjour

Voici le code yaml utilisé  du répertoire sensor


- platform: myEnedis
  token: !secret myenedis_token
  code: !secret myenedis_code1
  heures_creuses: "[['00:52', '07:22'], ['12:22', '13:52']]"
  hp_cout: 0.1543
  hc_cout: 0.1175
  scan_interval: 3600


Et la dernière version de card donne ceci
Pièce jointe
On voit le hc=0


Cordlt
Aladin

19 janv. 2021 22:31:49 saniho <notifications@github.com>:

**Comment by aladin2000** [comment]
Il semble que le résultat est mieux depuis la dernière version  de la carte
