### ISSUE TITLE
Configuration des heures 

### ISSUE THREAD

**Issue by kweebix** [saniho/apiEnedis#32]
Bonjour, il n'est pas possible de configurer les heure d'heure creuse, donc mon calcul est pas bon 5,78 sur votre api et 9,68 sur EDF

**Comment by Matilas83** [comment]
Hello, depuis le 20 Novembre et la version v1.0.2.5 (il y a une [discussion sur HACF](https://forum.hacf.fr/t/sensor-pour-enedis-apienedis/935/112)), tu as le paramètre heures_creuses dans ton sensor.
Par exemple
`heures_creuses: "[['00:00','05:00'], ['21:30', '24:00']]"`

**Comment by kweebix** [comment]
Oui mais pas dans la version "intégrations"

**Comment by saniho** [comment]
en effet .. dans la version integration, je recupère ce que donne Enedis, mais il semble que certains n'ait pas les memes heures creuses que celles données par Enedis.
Je vais voir pour integrer ceci dans une future version

**Comment by kweebix** [comment]
Merci

**Comment by saniho** [comment]
hello, la derniere version  1.1.2.0RC1  reprend les données definit dans le yaml, si absent prend les données de enedis
