### ISSUE TITLE
Production d'Electricité

### ISSUE THREAD

**Issue by vincentsticky** [saniho/apiEnedis#33]
Bonjour
Félicitations pour le travail effectué.
Je débute sous HA, pensez vous qu'il est possible de récupérer la production d'électricité ?
Sinon, je suis en triphasé, savez vous si on peut récupérer la conso par phase ?

Merci et encore un grand bravo pour le développement

**Comment by Matilas83** [comment]
Hello,
Pour la production d'électricité, je ne sais pas, je laisse les devs te répondre :)

Pour le triphasé (étant moi même en triphasé), sauf erreur ce n'est pas possible car la donnée n'est pas présente dans le portail Enedis. Si tu veux suivre ça précisément, il faudrait que tu tournes vers des solutions DIY pour récupérer la consommation en direct sur le compteur, ca te permettrait d'avoir les 3 phases + consommation en temps réel mais c'est un projet à part :)

**Comment by saniho** [comment]
hello, pour la production oui c'est possible.

**Comment by vincentsticky** [comment]
Merci beaucoup pour le retour

**Comment by saniho** [comment]
bonsoir la derniere version v1.1.2.0alpha2
permet de configuer le linky de production egalement depuis l'interface d'integration, et ainsi d'avoir accès au deux PDL( celui de production et celui de consommation )
si vous pouvez me faire un retour et confirmer que tout est ok

**Comment by vincentsticky** [comment]
Bonjour
Désolé pour mon retour tardif.
J'ai installé la v1.1.2.0alpha2 mais je pense pas comme il faut.
Je n'ai pas d'option supplémentaire dans l'interface d'intégration
Je vais réessayer et vous tiens au courant.
Merci

**Comment by saniho** [comment]
essaye en faisait l'installation de la derniere v1.1.2.0RC1
normalement, tu auras un sensor contenant ta production

![image](https://user-images.githubusercontent.com/52693545/104778042-ff8e2900-577c-11eb-8808-d150af3f0f79.png)

**Comment by vincentsticky** [comment]
Non j'ai pareil. Je vais essayer avec la RC2.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vincentsticky** [comment]
pareil. J'ai bien un sensor consommation, et conso quotidienne, mais pas
production...

J'ai tout désinstallé, rebooté, pius réinstallé en copiant bien l'api dans
custom components




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le dim. 17 janv. 2021 à 15:15, Vincent Legros <vincentsticky@gmail.com> a
écrit :

> Non j'ai pareil. Je vais essayer avec la RC2.
>
>
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Virus-free.
> www.avast.com
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
> <#m_-7437326047399671471_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>

**Comment by saniho** [comment]
hello, peux-tu me passer ton pdl et token, en mp, pour que je check ?

**Comment by vincentsticky** [comment]
Comment?

**Comment by saniho** [comment]
ici par exemple : https://forum.hacf.fr/u/saniho

**Comment by saniho** [comment]
@vincentsticky , sauf erreur, je n'ai pas vu de mp avec tes credentials ...

**Comment by vincentsticky** [comment]
Hello saniho, c'est pas une erreur.
J'avoue ne pas comprendre comment t'envoyer un MP. Peux tu me donner un
mail ?

**Comment by saniho** [comment]
voici mon mail : sanihogithub(at)gmail.com

**Comment by saniho** [comment]
@vincentsticky , merci pour l'exemple, cela m'a permis de voir que certains on eux PDL( un consommation/un production ), mais toi tu en as que un seul...seulement aucun moyen d'identifier cela dans les caractéristique du PDL :(
je vais être obligé de l'ajouter dans la configuration...mais cela va demander un peu de delai le temps de faire le dev:(

**Comment by vincentsticky** [comment]
Pas de soucis... Merci pour ton aide.
Pour info, je suis en tri phasé. Peut etre une configuration différente sur
mon PDL ?
En tous cas à ta dispo pour tout test.

**Comment by saniho** [comment]
hello, comme promis, la derniere RC v1.1.2.2RC2, permet de gerer des PDL multi type( production/consommation )
peux-tu faire un test et me dire ?
Cela te créé deux sensor, et chaque sensor aura donc sa propre card

**Comment by vincentsticky** [comment]
Hello
Effectivement j'ai bien deux s'endort
Je verrai comment les données s'affichent
Un grand Merci

**Comment by vincentsticky** [comment]
Ça marche top !
Merci


Le lun. 25 janv. 2021 à 08:36, Vincent Legros <vincentsticky@gmail.com> a
écrit :

> Hello
> Effectivement j'ai bien deux s'endort
> Je verrai comment les données s'affichent
> Un grand Merci
>
>

**Comment by saniho** [comment]
cool, merci pour ta participation
