### ISSUE TITLE
HC/HP non pris en compte à la première installation via l'intégration !

### ISSUE THREAD

**Issue by Rathorian** [saniho/apiEnedis#35]
Bonjour Saniho,

Tout d'abord, merci à toi pour tout le travail apporté avec cette intégration.

Je voulais te signaler (si tu n'es pas au courant) qu'à la première installation via l'intégration, la description de chaque entrée ne s'affiche pas ( Votre token, Votre code, prix HC, prix HP). J'ai renseigné les informations en m'aidant pour le coup de ta documentation en remplissant correctement tous les champs.

Une fois l'intégration terminée, les deux premiers sont bien pris en compte malgré tout (Token et Code) mais les HC/HP, sont vide.
J'ai dû cliquer sur "options" de l'intégration MyEnedis pour réinscrire les HC/HP.

Encore merci pour le travail.

Rathorian

**Comment by saniho** [comment]
Hello, merci pour l'information, la release v1.1.2.0RC1 règle ces soucis.
