### ISSUE TITLE
Plus fonctionnel depuis MAJ 1.1.2.0

### ISSUE THREAD

**Issue by skalimer0** [saniho/apiEnedis#36]
Bonjour,

Sur mon hass.io le plugins n'est plus fonctionnel et j'ai l'erreur suivante :+1: 

Logger: myEnedis
Source: custom_components/myEnedis/myEnedis.py:71
First occurred: 12:42:08 (8 occurrences)
Last logged: 12:42:11

    Erreur inconnue call ERROR 'int' object has no attribute 'keys'
    Erreur last answer 'int' object has no attribute 'keys'
    Erreur last call updateCurrentWeek
    (<class 'Exception'>, Exception(AttributeError("'int' object has no attribute 'keys'")), <traceback object at 0xec87a628>)
    LastMethodCall : updateCurrentWeek

Du coup la seule chose que la sonde récupére c'est ma puissance souscrite de mon forfait, le reste est vide.

De même sur la card, je n'ai jamais eu de tarif ou de consommation HP/HC fonctionnel alors que mon abonnement l'est. Apres c'est secondaire comme problème.

Merci encore pour la fonctionnalité.

**Comment by bolderiz** [comment]
Idem chez moi (ceci dit ca ne marchait pas avant non plus)

**Comment by saniho** [comment]
oups...quand on gere mal les erreurs de enedis... et bien çà plante :(
 la verison 1.1.2.1 règle le soucis
