### ISSUE TITLE
Multiple Source

### ISSUE THREAD

**Issue by foXaCe** [saniho/apiEnedis#37]
Bonjour,

Je possède plusieurs prises avec mesure de consommation.
Est-il possible de rajouter une option pour mettre d'autre entité et d'avoir la conso visuelle de chaque appareil qui apparait sur la carte ?

**Comment by saniho** [comment]
@foXaCe , peux-tu detailler ta demande, un exemple visuel( dessin ) serait un plus pour comprendre ton besoin.
