### ISSUE TITLE
Appel manuel

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#38]
Bonjour,
Est-il possible de déclencher manuellement un appel dans Home Assistant pour rafraîchir l'entity enedis et tous ses attributs (via script ou automatisation par exemple)
Merci d'avance !

**Comment by saniho** [comment]
bonjour, cela pourrait etre envisageable, pourrais-tu me preciser un exemple de cas ou cela serait necessaire ?

**Comment by Toukite** [comment]
J'imagine qu'il y aurait un tas d'usage, mais par exemple je dirais:
 pour programmer un seul appel quotidien à une heure donnée plutôt que de laisser faire HA, ou bien en cas de pb sur un des appels auto pour tenter un 2nd appel, ou bien pour générer volontairement les logs d'un appel, ou bien pour pouvoir exporter les données vers un autre système, etc...

Après oui, je suppose que ça implique de limiter le nb d'appels possibles pour éviter les abus ou un écroulement, mais ce serait vraiment utile !

PS: j'ai remarqué que les données de la veille n'étaient pas dispo dans HA avant la mi journée (pourtant dispo sur enedis dès le réveil)
Aussi, aujourd'hui, c'est KO pour moi: les données d'hier ne se sont pas affichées de la journée, j'ai une jolie colonne de triangles à la place ^^, le reste de l'historique s'affiche bien cependant.

**Comment by Toukite** [comment]
@saniho Je ne trouve pas comment enlever le label "wait answer from user" !

**Comment by saniho** [comment]
est-ce mieux ce jour ?

**Comment by silversmarty** [comment]
Même sujet ici, les données de la veille ne sont pas dispo avant 10h du matin (à peu près) : en attendant, j'ai de jolis triangles d'alerte. 
Est-ce qu'il serait au moins possible de paramétrer dans le yaml (ou l'interface) l'heure à laquelle l'appel se fait ?

Merci :-)

**Comment by herveaurel** [comment]
Je sais rafraichir une entité comme celle ci pour répondre a la question initiale. 
J'ai créé le petit script, que j'appelle a intervalle régulier si la remontée n'est pas faite. 
Et ca me sauve tres souvent ! 
En général, entre 10h et 11h j'ai les remontées grâce au script. 
Je l'ai déjà donné sur mon groupe Facebook ou sur mon Github je ne sais plus. 
Quel est le meilleur moyen de le partager @saniho ? Ici ? 
Merci pour tout le travail.

**Comment by mdeweerd** [comment]
Pour partager je propose d'utiliser un gist - si ce n'est pas long même copier/coller le contenu.
C'est un script HA (yaml) ou Python?

Après, j'imagine qu'il vaut mieux un service mais je crois qu'on se heurte au nommage d'apiEnedis actuellement pour proposer cela (dela devrait être sans majuscule...).

**Comment by herveaurel** [comment]
Je ne sais pas ce qu'est un gist. 
Mais je peux le mettre dans mon github dans la partie tuto, ou le copier ici car la démarche est très courte. Un script HA, avec l'apppel d'un service. Astuce très efficace ! Je m'en sers pour les intégrations hacs qui peuvent avoir besoin d'un refresh.

**Comment by mdeweerd** [comment]
Un GIST c'est un petit ensemble de fichiers qu'on veut partager sans pour autant faire un projet.

On peut le créer ici: https://gist.github.com/ .  Derrière il y a quand même un git.

Ok pour le script HA, c'est la partie "évidente", pour le service (mais c'est toujours bien de fournir un exemple aux utilisateurs), celui d'apiEnedis ne me semble pas fonctionnel, donc c'est la partie à reprendre.

**Comment by herveaurel** [comment]
> Un GIST c'est un petit ensemble de fichiers qu'on veut partager sans pour autant faire un projet.
> 
> On peut le créer ici : https://gist.github.com/ . Derrière il y a quand même un git.
> 
> Ok pour le script HA, c'est la partie "évidente", pour le service (mais c'est toujours bien de fournir un exemple aux utilisateurs), celui d'apiEnedis ne me semble pas fonctionnel, donc c'est la partie à reprendre.

Avec ce simple script, le refresh fonctionne. Je l'appelle dans une auto, a intervalles reguliers si la remontée n'est pas faite. En général, cela fonctionne tres bien. 
J'ai également créé un bouton pour le lancer manuellement (en haut a droite de ma carte).
<img width="178" alt="Capture d’écran 2022-03-18 à 13 19 01" src="https://user-images.githubusercontent.com/64784541/159001830-4029e4bb-1386-4aac-aa5a-4ed3369b026b.png">

`alias: Rechargement intégration myenedis
sequence:
  - service: homeassistant.reload_config_entry
    target:
      entity_id: sensor.myenedis_energy_09397539765420
    data: {}
mode: single`

**Comment by Toukite** [comment]
Je viens de tester ce script mais de mon côté ça ne semble pas redeclencher l'appel enedis, en tout cas je ne vois rien dans les logs hormis un reload de l'entity.

Dommage, cela fait justement quelques jours que je ne vois que des triangles partout sur la card, cette commande m'aurait été bien utile !
J'ai renouvelé mon token dans le doute et la commande de test fonctionne mais nope, triangle triangle triangle :/

**Comment by cba64** [comment]
OK je retesterai lorsque le bug de quota/jour sera fix. Cela dit avant ce bug je n'avais pas spécialement de pb hormis les we où l'api enedis est souvent KO

J'ai 2 entités pour ma part: sensor.myenedis_pdl et sensor.myenedis_energy_pdl, j'ai essayé sur les deux sans succès mais je ré-essaierai.

Et sinon comment vérifies-tu que l'appel n'a pas fonctionné pour éviter de reload pour rien ?

**Comment by Toukite** [comment]
OK je retesterai lorsque le bug de quota/jour sera fix. Cela dit avant ce bug je n'avais pas spécialement de pb hormis les we où l'api enedis est souvent KO

J'ai 2 entités pour ma part: sensor.myenedis_pdl et sensor.myenedis_energy_pdl, j'ai essayé sur les deux sans succès mais je ré-essaierai.

Et sinon comment vérifies-tu que l'appel n'a pas fonctionné pour éviter de reload pour rien ?

**Comment by herveaurel** [comment]
> OK je retesterai lorsque le bug de quota/jour sera fix. Cela dit avant ce bug je n'avais pas spécialement de pb hormis les we où l'api enedis est souvent KO
> 
> 
> 
> J'ai 2 entités pour ma part: sensor.myenedis_pdl et sensor.myenedis_energy_pdl, j'ai essayé sur les deux sans succès mais je ré-essaierai.
> 
> 
> 
> Et sinon comment vérifies-tu que l'appel n'a pas fonctionné pour éviter de reload pour rien ?

Je te montrerai mon auto qui prend en compte la remontée HS en condition quand je serais sur mon PC. 
Le rechargement via ce script refresh toute l'intégration associée à l'entité. Donc pas besoin d'essayer avec plusieurs entités de la même intégration 🙂

**Comment by mdeweerd** [comment]
Je viens d'ajouter un écouteur sur événement #163 qui peut être disponible dans une version > v1.5.0.4 .

Il suffira de déclencher cet événement pour déclencher une consultation de la gateway.  A utiliser avec parsimonie car le nombre d'appel maximum de 50 guêtte !  Un déclenchement entraine une quinzaine d'appels.

**Comment by mdeweerd** [comment]
Depuis la v1.5.1 il est possible de déclencher un appel, dont la réalisation reste soumise aux conditions habituelles d'heures autorisés, de délai et de l'état de réussite précédent.

En pratique, il n'y a à priori plus d'utilité d'y faire appel, les autres problèmes étant réglés.

Pour info:
![image](https://user-images.githubusercontent.com/1504752/161583704-5869bd3d-01eb-4014-b515-011329d28fb4.png)

Je propose de clôturer ce ticket.

**Comment by saniho** [comment]
feature implemented by @mdeweerd 
Closed this issue
