### ISSUE TITLE
Erreur 400 - ADAM-ERR0123

### ISSUE THREAD

**Issue by cba64** [saniho/apiEnedis#39]
Bonjour,

Pour info, je reçois l'erreur suivante sur la mise à jour de type "daily_consumption":

```
data : {"type": "daily_consumption", "usage_point_id": "HIDDEN", "start": "2019-12-01", "end": "2020-01-01"} 

Error JSON : {"error":"result_400","enedis_return":{"error":"ADAM-ERR0123","error_description":"The requested period cannot be anterior to the meter's last activation date","error_uri":"https://bluecoder.enedis.fr/api-doc/consulter-souscrire"}} 
```

**Comment by saniho** [comment]
bonjour, as-tu tester avec les derniere RC ?
Car sauf erreur, je l'ai integré dedans ...

**Comment by cba64** [comment]
Bonjour,
J'utilise la version disponible sur HA (1.1.2.1)

**Comment by saniho** [comment]
bonjour, il faut que tu utilises au minimum cette version 1.1.2.2RC2
pour l'avoir, c'est une version beta, il faut que tu desinstalle via hacs et reintall, et à ce moment bien activer avoir acces au version beta.
