### ISSUE TITLE
0 kWh en heures creuses

### ISSUE THREAD

**Issue by xmow49** [saniho/apiEnedis#4]
Slt,
J'ai installé ton integration, et elle fonctionne bien 👍 
Il manque juste la conso en HC, home assistant me donne ça:
```attribution: ''
version: 1.0.2.5
lastSynchro: '2020-11-25T18:33:40.371725'
lastUpdate: '2020-11-25T18:33:40.371709'
timeLastCall: '2020-11-25T18:33:40.371627'
yesterday: 67689
last_week: 441681
day_1: 67689
day_2: 65074
day_3: 76647
day_4: 79061
day_5: 72474
day_6: 55475
day_7: 56915
daily:
  - 67.68900000000001
  - 65.074
  - 76.647
  - 79.061
  - 72.474
  - 55.475
  - 56.915
halfhourly: []
offpeak_hours: 0
peak_hours: 67.68900000000001
peak_offpeak_percent: 100
yesterday_HC_cost: 0
yesterday_HP_cost: 10.694862
daily_cost: 10.694862
current_week: 132763
last_month: 1172359
current_month: 1277405
last_year: null
current_year: 3910270
errorLastCall: >-
  {'error': 'result_500', 'enedis_return': {'error': 'Internal Server error',
  'error_description': 'Un problème a été rencontré lors du traitement.',
  'error_uri': 'https://bluecoder.enedis.fr/api-doc/consulter-souscrire'}}
monthly_evolution: 0
unit_of_measurement: kWh
friendly_name: myEnedis
```

```offpeak_hours: 0```
Donc cela me donne 0kWh en HC
D'ou viens le problème ?

Merci
Xmow

**Comment by saniho** [comment]
hello @xmow49 , merci pour tes encouragements, concernant ton pb, je penses que le soucis vient de la deéclration du sensor et le fait qu'il n'y ait pas de tarif HC, d'ou le montant yesterday_HC_cost
essaye en indiquant bien ceci dans le (sensor).yaml


- platform: myEnedis
  token: xxx
  code: xxx
  heures_creuses: "[['00:30', '07:00'], ['10:00', '11:30']]"
  hc_cout: 0.0797
  hp_cout: 0.1175
  scan_interval: 3600

**Comment by xmow49** [comment]
Slt,
Merci, cela fonctionne, je pensait que cela récupairait tous seul depuis l'api enedis...
Bref, là ca fonctionne 👍 
Idée d'amélioration: un service à appeler pour refresh les donnés, car auctuelement je devait redémarer home assisatant :-)

Merci
Xmow

**Comment by saniho** [comment]
@xmow49 , pour information le refresh est present toutes les deux heures, tu peux t'en assurer avec cette information dans le sensor lastSynchro: '2020-11-25T18:33:40.371725'
lastUpdate: '2020-11-25T18:33:40.371709'
attention entre 00:00 et09:00 Enedis est indisponible pour les données de la veille, donc souvent synchro en erreur à ce moment là.
