### ISSUE TITLE
 PDL multi type( Consommation & Production )

### ISSUE THREAD

**Issue by algernon2607** [saniho/apiEnedis#40]
Bonjour Saniho

Comment procéder pour accéder aux données de consommation et de production ?
Dans HACS , j'ai installé la derniére version et rien n'apparait dans le sensor comme données de production.

Merci d'avance
Al

**Comment by saniho** [comment]
Hello, peux-tu me passer en mdp ton PDL et token ?( soit par mail soit par message ici : 
https://forum.hacf.fr/u/saniho/

**Comment by algernon2607** [comment]
Voici mon mail : algernon2607@yahoo.com 
Fais moi parvenir ton mail .
Merci
Al

**Comment by saniho** [comment]
voici mon mail : sanihogithub@gmail.com

**Comment by algernon2607** [comment]
Je vous  précise également que j’ai un abonnement de base  6KW sans HC/HP 


Provenance : Courrier pour Windows 10

De : saniho
Envoyé le :mercredi 3 février 2021 22:01
À : saniho/apiEnedis
Cc : algernon2607; Author
Objet :Re: [saniho/apiEnedis] PDL multi type( Consommation & Production )(#40)

voici mon mail : sanihogithub@gmail.com

**Comment by saniho** [comment]
merci, je regarde dès que j'ai un moment

**Comment by saniho** [comment]
@algernon2607 , j'ai mis une nouvelle release en pre-version( v1.1.3.0RC3 ), elle permet d'avoir en permanence un sensor production.
Si tu peux tester et me dire.

**Comment by algernon2607** [comment]
Bonjour @saniho 
J’ai installé ta version béta : j’ai donc 5 senseurs que j’ai mis pour le moment dans une carte entité .(Toutes les valeurs sont à zéro pour le moment).
Je vais laisser vivre pendant quelques temps et je te ferait un retour.(en espérant le soleil :=)
A signaler toutefois un ('call', 'error', 'result_404') sur les senseurs conso et prod.

**Comment by algernon2607** [comment]
Bonsoir
Rien de neuf pour cette journée : toutes les valeurs sont à zéro.
Le ('call', 'error', 'result_404') qui avait disparu un temps , est revenu .....
Je vais laisser passer la journée de demain ....
A+

**Comment by saniho** [comment]
pour info Enedis semble encore cassé...serveur parti en weekend ;(
![image](https://user-images.githubusercontent.com/52693545/107129615-e6355400-68c6-11eb-932d-425ac65a3171.png)

**Comment by algernon2607** [comment]
Bien , les chiffres viennent de remonter ... En ce qui me concerne , l'index prod est le même que l'index production .Quand aux senseurs  history , il remonte des chiffres qui ont l'air d'être un historique mensuel mais je n'arrive pas à faire la corrélation avec un historique glissant ou mensuel date à date.
Je reste à ta dispo pour d'autres essais au cas ou tu veuilles continuer ...

**Comment by algernon2607** [comment]
Encore une précision sur les history : toutes les heures , ils rajoute une valeur à la somme précédente et je ne vois pas à quoi cela correspond .
Actuellement , au bout de 4 rajouts , il indique 990KWh ce qui ne correspond à rien chez moi.

**Comment by saniho** [comment]
dans cette release, le sensory history,history_hp, et history_hc permettra de faire graph sur la consommation par heure
exemple : 
![image](https://user-images.githubusercontent.com/52693545/107158211-e138d900-6988-11eb-9630-4a9632c49b7f.png)

**Comment by saniho** [comment]
pour "l'index prod est le même que l'index production ", peux-tu etre plus précis ?

**Comment by algernon2607** [comment]
Bonjour
Bon , je devais être fatigué : l'index production est le même que l'index consommation alors que ma prod en ce moment est super faible donc injection trés trés faible.
La dénomination de l'index injection est : Energie active injectée totale  EAIT .
Ok pour les history  : je pense que c'est l'unité qui ne va pas . En Wh , cela serait cohérent pour moi.
Encore merci pour tes recherches.

**Comment by saniho** [comment]
@algernon2607 , peux-tu faire un test avec la version v1.1.3.0RC5

**Comment by algernon2607** [comment]
Bonjour @saniho 
Test effectué avec la nouvelle version (installation manuelle car elle ne s'installe pas via HACS).
Consommation OK : tout est correct.
Production : fournit un seul index (pas d'historique journalier) mais celui-ci est correct : j'ai essayé dans ta carte lovelace , c'est bon .
Les history (mis à part les unités ) sont bons. Perso , vu mon abo , je ne garde que history.xxxxxxxx.ALL.
Je vais essayer de voir pour les passer en Wh .
