### ISSUE TITLE
manque de données

### ISSUE THREAD

**Issue by froggy974** [saniho/apiEnedis#41]
Bonjour,

Merci pour cette intégration

Je n'arrive pas à la faire fonctionner chez moi.
Il me manque une partie des données.
Est ce qu'une âme charitable pourrais m'aider à m'indiquer d'où vient le problème  ?

Voici ce que je vois sur le sensor

![image](https://user-images.githubusercontent.com/17068466/107048194-f404af80-67c8-11eb-96c0-5773e96d4387.png)

et ma config : 

```
- platform: myEnedis
   token: jmSn72YoxxxxDi6z56S
   code: 23xxx91 
   hc_cout: 0.095
   hp_cout: 0.095
   heures_creuses: "[['00:30', '07:00'], ['10:00', '11:30']]"
   heuresCreusesON: false
   scan_interval: 3600
```

**Comment by saniho** [comment]
@froggy974 , as-tu bien activé sur ton compte enedis, la remontée horaire ? Si oui, il faut parfois attendre 2 jours que enedis l'active...donc le sensor ne les verra que après ces deux jours

**Comment by froggy974** [comment]
ah oui ca doit etre ca, mon compteur n'est pas encore à l'étape 3, il a été remplacé récemment.
J'imagines qu'il faut que je patiente ..

![image](https://user-images.githubusercontent.com/17068466/107094755-e3275e80-6807-11eb-8f6a-29b695f0a0e2.png)

**Comment by nutsben** [comment]
Bonjour,
J'ai le même soucis.
![image](https://user-images.githubusercontent.com/78533822/107113806-95d7db00-6861-11eb-821e-1d65a54f3295.png)
Pourtant, j'ai bien la remonté horaire activé sur mon compte linky

![image](https://user-images.githubusercontent.com/78533822/107113821-bdc73e80-6861-11eb-8a56-6712b8380439.png)

Par contre, quand je vais dans "gérer l'accès à mes données", je vois ça :
![image](https://user-images.githubusercontent.com/78533822/107113859-fb2bcc00-6861-11eb-9b02-ae820fbbdd55.png)

Est-ce normal ? Pourtant, j'ai bien autorisé Enedis Gateway, j'ai reçu un mail de confirmation de la part d'Enedis.
Y a t-il un moyen d'avoir des logs ? Comment les activer ?

**Comment by saniho** [comment]
pour info : 
![image](https://user-images.githubusercontent.com/52693545/107129639-0c5af400-68c7-11eb-9c37-f646ee7e063e.png)

**Comment by valderaplets** [comment]
Idem ici, même après regénération du token. à suivre donc :/

**Comment by saniho** [comment]
hello, il se peut qu'il faille encore le regenerer .. pour s'en assurer, en installant la derniere version, tu auras l'information sur la card

**Comment by valderaplets** [comment]
Hum mise à jour faite. j'ai pas regénéré le token (je l'avais déjà fait ya quelques jours et mes infos remontaient correctement)
là pour l'instant c'est 404 Nan , mais je préviens si ça change

**Comment by valderaplets** [comment]
a moins qu'il faille forcément le regénérer après ta maj ?

**Comment by valderaplets** [comment]
* token regénéré
* nouveau sensor 'monsensor_2'
* des nouveaux sensors avec hp hc etc 
et ça fonctionne là

**Comment by DarKOrange75** [comment]
Bonjour @saniho , merci pour cette super intégration. Malheureusement elle ne fonctionne pas chez moi, pas de remontée de données de consommation (OK pour la puissance abo et la date de souscription du contrat). J'ai activé la remontée horaire lundi dernier... Merci pour votre aide.

<img width="395" alt="Capture d’écran 2021-03-06 à 07 48 27" src="https://user-images.githubusercontent.com/40524270/110198162-b4c19100-7e50-11eb-9504-020ec1ad4d22.png">
