### ISSUE TITLE
disconnections (error 400) + some layout "optimisation"

### ISSUE THREAD

**Issue by r-jean-pierre** [saniho/apiEnedis#43]
![2021-02-09 12_29_52-Window](https://user-images.githubusercontent.com/9727894/107357699-b5c20580-6ad2-11eb-9c19-7198f7232161.png)

Hi Saniho,

Thank you for your great work for both apiEnedis and content-card-linky 

I got more and more disconnections/unavailability of the api, it says "call error 400"
I'm running v1.1.3.0RC3, and BTW I cannot upgrade to the v1.1.3.0RC5, I tried many times, but nothing happens. I could just copy-paste the new files directly by ssh, but I would prefer to follow the "clean/official" way of doing it (and it was always working for your plug-in and for all the other ones I have, simply through the GUI)

Maybe I'm unlucky with my enedis account, meter, internet connection etc., so I waited a long before reporting this here in github

As a cosmetic suggestion, as being the author of cardLinky, I would prefer to see the day names in bold but not the values. I'm pretty sure that because of bold font for strings like "14.51 kWh", for a few number of pixels, the automatic layout decides to break the line and displays the string onto 2 lines in the table

BR,

JP.

**Comment by saniho** [comment]
Hi, for the bold, I will check this
For the installation, if you have some issue, plaese made uninstall, and reinstall ...

**Comment by saniho** [comment]
for the bold name of the day, please test with the pre release : v1.0.3.9RC
let me know

**Comment by r-jean-pierre** [comment]
Hi,

Thanks for the support 
So I forced uninstall, install, reboot server etc. finally I did it. I'm on v1.1.3.0RC6 for api and v1.0.3.9RC for the card.
Didn't see yet the error 400 and the rendering looks better:

![2021-02-09 21_34_48-Overview - Home Assistant](https://user-images.githubusercontent.com/9727894/107425120-dd3ebf80-6b1e-11eb-85e3-cd12a955dff3.png)

unfortunately it still warps the text but i suppose it's logical as there is not enough horizontal space in columns, it breaks line on a white space

**Comment by saniho** [comment]
if you think it's interesting, perhaps add a version without unit of with only k instead of kWh
or reduce the number of day... 6 days configurable instead of 7 let me now.

**Comment by r-jean-pierre** [comment]
I found by myself a workaround by rounding to 1 decimal :
![2021-02-09 23_16_31-Overview - Home Assistant](https://user-images.githubusercontent.com/9727894/107435896-11b97800-6b2d-11eb-97da-db4474a49779.png)
This is not optimal, it just "works" on my config of screen and resolution. I had luck to +/- understand the JS language and having this final rendering :)

In any case this card is far better and more beautiful than the "official" android-app made by my electricity provider .. :)

**Comment by saniho** [comment]
I have produce a new RC release ( v1.0.3.9RC1 )
in this you can add a param in the card : 
```
nbJoursAffichage: x
```
and x is the number of day, this result for 3 days : 
![image](https://user-images.githubusercontent.com/52693545/107566114-bcd93880-6be4-11eb-86ed-2b9cff44251b.png)
