### ISSUE TITLE
Service Offline

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#45]
Bonjour,

Je rencontre désormais cette erreur:

`2021-02-12 15:23:49 WARNING (SyncWorker_5) [myEnedis] (<class 'Exception'>, Exception('call', 'error', 'service_offline'), <traceback object at 0x7f78782880>)`

* myEnedis sensor v1.1.3.0RC7
*  Content Card Linky v1.0.3.9RC1

J'ai essayé de regarder s'il n'y avait pas un pb avec mon token au cas où, mais le lien "Faire la demande de consentement" sur la page https://enedisgateway.tech et qui renvoie vers https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize retourne désormais une erreur 404 La page que vous recherchez n’existe pas.

**Comment by r-jean-pierre** [comment]
Je crois que ca vient de enedisgateway, si j'envoie directement un curl, j'ai ceci:

{"error":"service_offline","description":"Le service est temporaire Hors-Ligne","support":"https://discord.com/invite/zXrr7ZV"}

**Comment by saniho** [comment]
api Enedis HS....wait & see

**Comment by r-jean-pierre** [comment]
Fonctionnel à nouveau pour moi depuis au moins ce matin 17 février

**Comment by saniho** [comment]
yes, enedis a reparé ;)
