### ISSUE TITLE
Plus rien depuis 2 jours

### ISSUE THREAD

**Issue by Manox35** [saniho/apiEnedis#46]
Absolument plus rien depuis 2 jours. J'ai désinstallé puis j'ai réinstallé, puis relancer, etc mais rien à faire, je n'ai plus de données. C'est assez aléatoire depuis 15 jours

**Comment by saniho** [comment]
probleme chez Enedis...wait and see

**Comment by r-jean-pierre** [comment]
Fonctionnel à nouveau pour moi depuis au moins ce matin 17 février

**Comment by saniho** [comment]
yes, enedis a reparé ;)
