### ISSUE TITLE
Données Max Power

### ISSUE THREAD

**Issue by Skuair** [saniho/apiEnedis#47]
Bonjour,

Je sais qu'il existe en plus de daily_consumption et load_curve, la donnée max_power qui représente la puissance maximum soutirée pour tel jour.
Je l'utilisais sur un autre plugin d'un autre système domotique mais sauf erreur de ma part je ne vois pas cet appel dans ton code.

Pour l'instant je n'ai jamais activé la collecte horaire, ce qui provoque un sensor pas très complet (error_call_400 mais c'est logique) mais le principal remonte quand même pour moi, à savoir la consommation de yesterday. Mais ça serait pas mal d'avoir aussi ce max_power pour yesterday.

Est-ce que c'est volontaire ? Ou alors ça dépend de ce que la gateway propose ?
Merci.

**Comment by saniho** [comment]
merci pour l'idée, je vais voir ce que je pourrais faire....

**Comment by saniho** [comment]
la fonctionnalité est disponible dans la version : v1.1.3.2RC
dans le sensor, ajout de l'attribut : yesterdayConsumptionMaxPower

**Comment by Skuair** [comment]
Super merci, je teste ça dès que possible.

**Comment by Skuair** [comment]
J'ai peut-être loupé un truc mais j'ai l'impression qu'il n'utilise pas cette nouvelle version.
J'ai réinstallé l'intégration via HACS en mettant bien la 1.1.3.2RC, j'ai redémarré HA, le sensor s'est mis à jour avec les données de la veille mais pas de nouvel attribut yesterdayConsumptionMaxPower et surtout l'attribut version contient toujours 1.1.3.1.

J'ai manqué une étape ?

**Comment by saniho** [comment]
en effet, ce n'est pas "normal", je te propose de faire 
![image](https://user-images.githubusercontent.com/52693545/109562178-57d77b00-7ade-11eb-89ab-73610e01eb1e.png)

**Comment by Skuair** [comment]
Rien à faire, j'ai testé ta proposition, ça reste en 1.1.3.1.
J'ai tenté de supprimer l'intégration, supprimer ensuite les entités, puis de réinstaller l'intégration, pareil, c'est fou.
Par contre, sur les 4 ou 5 entités créés par l'intégration, certaines sont bien à la bonne version, comme l'historique HC ou HP je crois.

Du coup, j'ai rebasculé sur la stable, j'attendrai que tu sortes cette version en stable pour tester.
Si l'entité principale se met pas à jour à moment là, là j'investiguerai plus en détails.

**Comment by Skuair** [comment]
Salut, ayant vu que tu avais publié la nouvelle version stable j'ai voulu mettre à jour : j'avais le même soucis, toujours l'ancienne version qui restait. Après avoir désinstallé bien 5 fois de suite, j'ai enfin pu avoir la version correct avec l'attribut maxpower.
Sauf, qu'il vaut 0, alors que yesterday est correct.
Y'a-t-il quelque chose de spécial à mettre en place (côté HA ou espace enedis) ?

**Comment by saniho** [comment]
normalement rien de special, si l'information est fournie par Enedis, tu dois la voir apparaitre
![image](https://user-images.githubusercontent.com/52693545/111001996-f25c7780-8384-11eb-9655-ec8152279a1e.png)

**Comment by Skuair** [comment]
J'ai bien les données sur le compte enedis mais toujours 0 sur HA.
Étant donné que je n'ai pas activé la collecte horaire, est-il possible que ton code renvoie une exception et termine le programme avant d'atteindre la fonction d'appel à maxPower ?
Car je sais que cette donnée (avec la conso simple) est dispo même en ayant la collecte horaire non activée.

**Comment by saniho** [comment]
hello, peux-tu me donner ton code pdm et token en mp pour que je puisses voir ce que je pourrais faire ?

**Comment by Skuair** [comment]
Salut, en fait en modifiant légèrement ton code, j'ai pu faire fonctionner et récupérer la valeur.
En effet, en mettant l'appel à self.updateYesterdayConsumptionMaxPower() juste après le premiers updateYesterday(), je récupère bien mes valeurs :
`if (self.getStatusLastCall() or self.getLastMethodCallError() == "updateYesterday"):
                            self.updateYesterday()`
`if (self.getStatusLastCall() or self.getLastMethodCallError() == "updateYesterdayConsumptionMaxPower"):
                            self.updateYesterdayConsumptionMaxPower()`

Cela confirme ce que je pensais : étant donné que de mon côté la collecte horaire n'est pas activée, les fonctions qui suivent updateYesterday() plantent avec l'erreur (The customer objected to the load curve recording (ADAM-ERR0075-enedis_return_ko)), de ce fait, comme l'appel à MaxPower était à la fin, il ne passait jamais dedans.
En le mettant juste après updateYesterday, ça marche car ces données ne nécessitent pas la collecte horaire.

Cette collecte n'étant pas active chez tout le monde et non obligatoire, il faut peut-être adapter le code afin que les seules fonctions qui ne la nécessite pas puissent marcher tout de même.

A mon avis, pour résoudre cela il faudrait faire l'un des 3 points suivants :
- soit catcher toute exception dans un tableau de messages et permettre de passer à la fonction suivante sans sortir du script pour appeler toutes les fonctions dispos et renvoyer à la fin le tableau d'erreurs (le mieux à mon avis)
- soit mettre les 2 fonctions qui ne nécessitent pas la collecte horaire au début, mais en sachant que dans tous les cas, le reste plantera (pas super propre)
- soit côté paramétrage de l'intégration, ajouter une case à cocher / ou un paramètre dans le yaml pour demander si la collecte horaire est activée, et si non ne pas passer dans les fonctions qui la nécessitent (peut-être le moins long à faire ?)

**Comment by saniho** [comment]
merci pour l'info, je vais essayer de voir pour trapper proprement l'erreur, est-ce que tu as toujours ADAM-ERR0075 ?
peux-tu me donner le json que tu reçois en retour ?

**Comment by Skuair** [comment]
Oui j'ai toujours cette erreur mais depuis ma modif j'ai bien les valeurs
dans maxPower qui changent.

Comment je vois le json en retour ? Un log à activer ?

**Comment by saniho** [comment]
normalement cela devrait etre bon avec la dernier version v1.1.4.1, si tu peux tester et me confirmer

**Comment by Skuair** [comment]
Je viens de tester c'est ok, merci. J'ai même les infos dans les last_month et last_year maintenant.
Nickel.
