### ISSUE TITLE
Permètre de configurer les heures creuses depuis le GUI et prendre en compte des heures creuses uniquement de nuit

### ISSUE THREAD

**Issue by Nardol** [saniho/apiEnedis#48]
Hello,

Serait-il possible de pouvoir configurer les horaires des heures creuses via la configuration via l'interface graphique ?
En somme, pouvoir configurer la même chose que ce qui est faisable via YAML.

Car dans mon cas, il semble que mon compteur Linky ne communique pas les heures creuses.
De plus, comment peut-on configurer des heures creuses dans mon cas sachant qu'elles sont entre 22:36 et 06:36 ? Est-ce qu'il faudrait mettre 00:00-06:36 et 22:36-23:59 ? Sachant que du coup, ça exclurais 23:59 qui est pourtant bien en HC.

**Comment by saniho** [comment]
en effet, à  ce jour seul via le YAML on peut forcer les horaires differentes de celles données par Enedis...cela viendra dans une prochaine version pour la partie UI
Sinon, tu peux indiquer ceci dans le yaml : 00:00-06:36 et 22:36-24:00

**Comment by saniho** [comment]
pourriez-vous tester avec la version 1.2.0.0rc1, attention, la config se fait uniquement avec la configuration ( et plus le YAML...bien penser à le desactiver )

**Comment by Nardol** [comment]
OK, j'ai donc configuré via l'interface graphique.
Le format a l'air d'être bien passé.
