### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by gogui63** [saniho/apiEnedis#5]
Hello, 

Suite à la dernière maj qui inclut le changement du nom du sensors sensor.myenedis_numero_pdl, j'ai voulu modifier le nom du sensor pour qu'il match avec mes template que je m'étais fait sauf que je suis tombé là dessus en voulu changer le nom du sensor :

Cette entité n'a pas d'ID unique, par conséquent ses paramètres ne peuvent pas être gérés à partir de l'interface utilisateur. Consultez le documentation pour plus de détails.

https://www.home-assistant.io/faq/unique_id

Encore merci pour ton travail 👍 (Je t'ai MP sur discord pour te donner mon token et pdl)

Édit : une autre remarque, ce n'est peut être pas une bonne idée de mettre dans le nom du sensor le pdl (ou comme je dis au dessus , laisser la possibilité à l'user de l'éditer en ajoutant un unique ID) car certains partagent leur conf sur github et n'ont pas envie que tout le monde connaisse leur PDL :-D

**Comment by saniho** [comment]
merci pour l'information, j'ai regardé et pour avoir la possibilité de gerer le nom, il faut que l'integration soit faite via un flow specifique... Je verrais dans une prochaine evolution pour prendre en compte cela
merci
