### ISSUE TITLE
Each day it's the same

### ISSUE THREAD

**Issue by Manox35** [saniho/apiEnedis#50]
It works one day ans then 

Logger: myEnedis
Source: custom_components/myEnedis/myEnedis.py:81
First occurred: 11:30:05 (14 occurrences)
Last logged: 11:30:16

Erreur inconnue call ERROR ('call', 'error', 'result_404')
Erreur last answer ('call', 'error', 'result_404')
Erreur last call updateDataYesterdayHCHP
(<class 'Exception'>, Exception(Exception(Exception('call', 'error', 'result_404'))), <traceback object at 0x7f6d10e100>)
LastMethodCall : updateDataYesterdayHCHP

I have all data with the curl command
strange !!

**Comment by saniho** [comment]
Enedis have lost all agreement with partner, please renewall your "agreement" with https://enedisgateway.tech/
let me know

**Comment by Manox35** [comment]
I did it, now it seems to work. Thx
