### ISSUE TITLE
Erreur lors de la commande de test

### ISSUE THREAD

**Issue by DarKOrange75** [saniho/apiEnedis#51]
Bonjour,

J'ai activé ce matin la collecte de la consommation horaire (l'enregistrement était déjà actif), j'ai accepté le partage de données avec apiEnedis et la commande de test (copier/coller depuis la page de validation de l'api) retourne une erreur :

{"error":"result_404","enedis_return":{"error":"no_data_found","error_description":"no measure found for this usage point","error_uri":"https://bluecoder.enedis.fr/api-doc/consulter-souscrire"}}

Merci pour votre aide.

**Comment by saniho** [comment]
@DarKOrange75 , en effet, il faut parfois attendre 48/72h avant que Enedis n'active la collecte...
