### ISSUE TITLE
Ban suite a un trop grand nombre de demande

### ISSUE THREAD

**Issue by Nadios-Vistos** [saniho/apiEnedis#55]
Bonjour,
Quelle surprise j'ai eu aujourd'hui en voyant ce message : Après un trop grand nombre de demande erroné et non corriger j'ai décider de vous ban.
Soit je comprend que c'est pour éviter de saturer le serveur ou le réseau, mais une explication sur la résolution de demandes erronées, aurait été appréciable quand même... Y a t il un moyen de corriger cela ? Sachant que dans la journée j'avais eu un autre message me demandant de refaire le consentement, ce que j'ai fait mais sans succès. En espérant pouvoir résoudre le soucis.
Bonne journée.

**Comment by DarKOrange75** [comment]
Bonjour,

Même problème ici, ban :-(

<img width="392" alt="Capture d’écran 2021-03-10 à 07 55 42" src="https://user-images.githubusercontent.com/40524270/110589148-49403200-8176-11eb-8a8a-f9e7dfce63db.png">

**Comment by guillaumebignon** [comment]
Bonjour, même problème ici,
Après redémarrage, le message est différent :
![image](https://user-images.githubusercontent.com/10077544/110618318-e8752180-8196-11eb-88a8-7c40a0610116.png)

Le token a été configuré la semaine dernière donc il me paraît improbable qu'il soit expiré, mais j'ai ce warning dans les logs avant le ban :
`WARNING (SyncWorker_5) [myEnedis] myEnedis err ('call', 'error', 'token_refresh_401')`

**Comment by Rykian** [comment]
Même problème ici.
> Soit je comprend que c'est pour éviter de saturer le serveur ou le réseau, mais une explication sur la résolution de demandes erronées, aurait été appréciable quand même...

Le ban provient de enedisgateway.tech, pas du module Home-Assistant je pense qu'il faut se plaindre directement à EnedisGateway pour ça. Par contre, le ban est probablement causé par un mauvais appel du module apiEnedis.

**Comment by Nardol** [comment]
J'ai également des "token refresh 401" aujourd'hui.

**Comment by sidwin9** [comment]
J'ai le même problème.
![image](https://user-images.githubusercontent.com/45182426/110829824-d7acd480-8298-11eb-9252-751b5657a554.png)

**Comment by Rykian** [comment]
En relançant l'inscription sur enedisgateway et en modifiant l'API Key dans ma configuration, c'est reparti pour moi !

**Comment by sidwin9** [comment]
L'API Key est le Token je suppose. J'ai relancé l'inscription et cela ne corrige rien pour moi.

**Comment by saniho** [comment]
il y a quelques soucis avec  https://enedisgateway.tech/, cela devrait bientot etre corrigé .... je vous tiens informés dès que j'ai plus d'informations.

**Comment by ZeckFR** [comment]
Bonjour,

Même comportement que mes camarades.
Ne serait-il pas intéressant d'implémenter le choix de la gateway Enedis cible?
Le projet https://github.com/guillaumezin/DomoticzLinky utilise  la passerelle https://enedis.domoticz.russandol.pro/, nettement plus stable, et qui doit finalement se comporter à l'identique.

**Comment by arkane2002** [comment]
Hello,

pour information : Pour le Ban, hier (11/03) Enedisgateway.tech a fait une erreur de déploiement qui a eu pour conséquence de faire expirer tous les token.
Le pb a été corrigé mais vous devez refaire votre consentement (bouton vert en bas de https://enedisgateway.tech/).

A noter aussi qu'un BAN intervient en temps normal si vous faites plus de 24 appels en 24 heures.
Donc si vous faites des reboot serveur attention aux surplus d'appels

**Comment by m4dm4rtig4n** [comment]
Bonjour,

Suite à une mise en prod foireuse d’hier, j’ai malencontreusement complètement désynchroniser les refresh_token avec ceux d’Enedis…
L’impact est que si vous avez fait une demande depuis la mise en production (hier soir) et que votre refresh_token était expirer (3h de durée de vie), vous serez obliger de refaire des consentements…
=> https://enedisgateway.tech/

Bref, veuillez m’excuse de la gêne occasionnée.

**Comment by ZeckFR** [comment]
Bonjour @m4dm4rtig4n et merci pour les infos.

> L’impact est que si vous avez fait une demande depuis la mise en production (hier soir) et que votre refresh_token était expirer (3h de durée de vie), vous serez obliger de refaire des consentements…
> => https://enedisgateway.tech/

Pour ma part, j'obtiens systématiquement un message du type :
{"error":"token_new_400","description":"Une erreur est survenue, merci de renouveller vos consentements plus tard.","pertubation":"Enedis rencontre un soucis avec le navigateur Chrome sur la demande de consentement"}

Et ce, quel que soit le navigateur utilisé.
Une idée du problème ?

**Comment by m4dm4rtig4n** [comment]
> Bonjour,
> 
> Même comportement que mes camarades.
> Ne serait-il pas intéressant d'implémenter le choix de la gateway Enedis cible?
> Le projet https://github.com/guillaumezin/DomoticzLinky utilise la passerelle https://enedis.domoticz.russandol.pro/, nettement plus stable, et qui doit finalement se comporter à l'identique.

Pour la petite histoire, j'ai du mettre en place un système de ban car ils commencent à y avoir pas mal d'utilisateurs qui utilise la passerelle et le service ce fait spam de demandes foireuse...

**Comment by m4dm4rtig4n** [comment]
> Bonjour @m4dm4rtig4n et merci pour les infos.
> 
> > L’impact est que si vous avez fait une demande depuis la mise en production (hier soir) et que votre refresh_token était expirer (3h de durée de vie), vous serez obliger de refaire des consentements…
> > => https://enedisgateway.tech/
> 
> Pour ma part, j'obtiens systématiquement un message du type :
> {"error":"token_new_400","description":"Une erreur est survenue, merci de renouveller vos consentements plus tard.","pertubation":"Enedis rencontre un soucis avec le navigateur Chrome sur la demande de consentement"}
> 
> Et ce, quel que soit le navigateur utilisé (Chrome/Edge/Opera).
> Une idée du problème ?

Edge/Opera sont sur le même moteur à savoir Chromium.
Essaie avec Firefox :/

Le soucis ne vient pas de chez moi malheureusement, je ne peut rien faire tant qu'Enedis ne fix pas le soucis.

**Comment by ZeckFR** [comment]
> Edge/Opera sont sur le même moteur à savoir Chromium.
> Essaie avec Firefox :/

> En gros une fois les consentements fait, Enedis te redirige normalement vers mon service avec en paramètre GET tt les informations.
> Sauf qu'avec Chrome & co Enedis te redirige vers :
> https://enedisgateway.tech/oauth?code=500&error=server_error&error_description=lincs-internal-server-error

A défaut de Firefox (flemme de dl et installer), je viens de tenter avec IE.
Ce dernier me montre une page incomplète, car il n'a pas dû savoir interpréter le code associé, mais j'ai bien l'URL de redirection, et je confirme que je vois bien un access_token, un refresh_token, et mes 2 usage_points_id.
Par contre, tu peux me préciser si je dois utiliser l'access_ ou le refresh_token dans ma config ?
J'aurai tendance à utiliser le refresh, mais j'ai un doute.

Merci pour ton aide !

**Comment by m4dm4rtig4n** [comment]
usage_points_id = Point de livraison.
access_token= Ton token d'identification a mon API.
refresh_token = Je le stock en BDD pour pouvoir refresh ton token automatiquement lors de l'expiration de access_token (3h)

**Comment by m4dm4rtig4n** [comment]
> Edit : je viens de tester via la commande cURL que j'ai retrouvée dans mon historique, c'est l'access_token, qu'il faut utiliser.
> Je remonte ma config avec ces paramètres. Problème à priori réglé pour moi.

C'est la où tout est la difficulté, c'est que cette erreur avec Chrome est complètement aléatoire....

**Comment by arkane2002** [comment]
> > Edit : je viens de tester via la commande cURL que j'ai retrouvée dans mon historique, c'est l'access_token, qu'il faut utiliser.
> > Je remonte ma config avec ces paramètres. Problème à priori réglé pour moi.
> 
> C'est la où tout est la difficulté, c'est que cette erreur avec Chrome est complètement aléatoire....

Je confirme. la première fois, avec chrome, aucun pb j'ai eu un retour avec toutes les infos.
Aujourd'hui, tjrs sur chrome, ça n'a pas marché. Avec Firefox aucun problème.

**Comment by m4dm4rtig4n** [comment]
Je viens de les relancer à ce sujet par mail.

**Comment by m4dm4rtig4n** [comment]
On est pas sauvé...

Réponse d'Enedis : 

> Le code erreur 500 que vous rencontre fait l’objet d’une anomalie rencontrée par plusieurs utilisateur dans le parcours 
> de consentement client. L’URL retour, une fois le consentement réalisé, renvoi ce code erreur au lieu du code 
> d’authentification permettant ensuite la récupération des token.
> 
> Cette anomalie étant assez aléatoire et la seule alternative pour le moment est de vider le cache du navigateur et 
> retenter l’opération (en attendant le correctif prévu pour la fin du mois normalement).

**Comment by ZeckFR** [comment]
Ils ont au moins pris la peine de répondre, et de donner une date pour un correctif.

**Comment by m4dm4rtig4n** [comment]
> Ils ont au moins pris la peine de répondre, et de donner une date pour un correctif éventuel.

J'y crois moyennement ça fait des mois que le fix devait être corrigé...

**Comment by totoantibes** [comment]
je n'arrive ple meme à jouter l'integration myEnedis. après renseignement des champs ca me fait" Aborted"
