### ISSUE TITLE
HA manisfet

### ISSUE THREAD

**Issue by guillaumebignon** [saniho/apiEnedis#56]
Bonjour, 

Ce log apparait dans HA, 

`WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'myEnedis'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'myEnedis'`

C'est pas dérangeant pour l'instant, mais ça pourrait le devenir plus tard !

**Comment by delphiki** [comment]
Hello, ça a déjà été géré, et ça sera sûrement dispo à la prochaine release : https://github.com/saniho/apiEnedis/pull/53

**Comment by saniho** [comment]
yes, ce sera dans la prochaine version
