### ISSUE TITLE
Consommation comparable Mois/semaine/jour année précédente

### ISSUE THREAD

**Issue by arkane2002** [saniho/apiEnedis#58]
Actuellement, bientôt mi-mars, la carte indique la consommation comparable du mois de février par rapport à février 2020. C'est top.
Pour juger de sa consommation, il serait très utile, et motivant, d'avoir de la même manière le comparable Année précédente pour : 

- La semaine en cours
- la veille
comme c'est déjà indiqué pour le mois précédent.

Pouvoir voir aujourd'hui qu'hier on a consommé de manière très supérieure à l'année dernière c'est sympa, ça rappellerai à l'ordre.

Actuellement chez moi c'est l'inverse. J'ai consommé sur Février 33% de moins que l'an dernier : 
- Mise en place cet été d'une pompe à chaleur
- passage en hivernage piscine passif au lieu d'actif

Qu'en penses-tu ?

Bonne journée

**Comment by saniho** [comment]
J'avais en effet pensé à cela, mais me disant que au vue de l'impact meteorologique de la consommation( t° exterieur de la veille, différente de la veille sur l'an passé ), et des effets, il valait mieux lisser la valeur
Après, cela peut toujours est ajouter et chacun le met dans la card s'il le souhaite.
Dis moi ce que tu en penses.

**Comment by arkane2002** [comment]
Le rendre optionnel serait parfait.

Après tu sais plus les maisons sont bien isolées moins l'impact extérieur est important. Donc dans des maison modernes je pense que le comparable prend tout son sens. 
Après, soyons fou, il est possible de récupérer la météo année-1 aussi, faut que je retrouve où mais je l'avais fait ya qqs années pour un projet pro. 

Merci pour ton taf 👍

**Comment by saniho** [comment]
@arkane2002 , cela t'irait genre ceci  ? 
semainevssemaineanneepasse : x %
yesterdayvsyesterdaysemainepassee : x %
?
pour la semaine, verrais-tu une comparaison au n° de semaine ou plutot à la semaine contenant la date de la veille ?

**Comment by arkane2002** [comment]
Salut,
yesterdayvsyesterdaysemainepassee : vs semaine passée ou vs semaine année passée ? Le nom peut être trompeur. 

Comparaison au numéro de semaine me paraît plus juste.
Et présente l'avantage de pouvoir donner une Info supplémentaire 'le numéro de semaine' 😉

Merci pour ton taf 👍

**Comment by saniho** [comment]
hello, voici ce que cela pourrait donné sur la semaine en cours, ton avis ?
![image](https://user-images.githubusercontent.com/52693545/111842933-876cec80-8900-11eb-9e5b-5a2a7ce62a41.png)

**Comment by saniho** [comment]
et ceci si on ajoute le comparatif de la veille 
![image](https://user-images.githubusercontent.com/52693545/111844203-d9167680-8902-11eb-928c-2a1fe2265a7c.png)

**Comment by saniho** [comment]
livré dans la derniere installation card + sensor

**Comment by ioannispelelis** [comment]
@saniho  j'ai une question con c'est quoi l'option pour qu'on l'active sur la card? j'ai pas trouvé dans la doc de la content-card-linky.
A moins que je l'ai raté ailleurs

**Comment by arkane2002** [comment]
En regardant le code voici les éléments de configuration qui existent et qui ont donné lieu à un paramétrage de la card qui pourrait ressemblé à ça 👍    
ça fonctionne très bien chez moi.   
```
- type: 'custom:content-card-linky'
        card_mod:
          style: |
            ha-card {
              background: none;
              box-shadow: none;    
            }      
        entity: sensor.myenedis_xxxxxxxxxxxxxx
        showIcon: true
        showHistory : true
        showPeakOffPeak: true
        showInTableUnit : false
        showDayPrice : true
        showDayPriceHCHP: false
        showDayHCHP: false
        showDayName: "long"
        showError: true
        showPrice: true
        showTitle: true
        showCurrentMonthRatio: true
        showMonthRatio: true
        showWeekRatio: true
        showYesterdayRatio: true
        titleName: "titlename"
        nbJoursAffichage: 7
#        kWhPrice: undefined
```

**Comment by ioannispelelis** [comment]
@arkane2002  j'ai rajouté la config suivante sur la card

```
showMonthRatio: true
showWeekRatio: true
showYesterdayRatio: true
```

Mais rien n'y fait ma card reste comme ceci
![image](https://user-images.githubusercontent.com/57101460/115534406-05be0500-a298-11eb-9959-7abf96998026.png)

J'ai également essayé de passer le showMonthRatio en false pour voir et la variation par rappord au mois ne disparait pas pour autant.. Bizarre c'est comme si ces config n'etait pas prise en compte chez moi.
Pourtant j'ai mis à jour via HACS la dernière version de apiEnedis et de content-card-linky....

**Comment by Toukite** [comment]
@ioannispelelis vide ton cache et/ou reboot ton HA
Moi ça s'affiche mais aucune des données A-1 n'est récupérée correctement, seules les valeurs courantes sont bien récupérées, et du coup j'ai 0% de delta sur les 4 valeurs
![image](https://user-images.githubusercontent.com/42780622/115535684-48cca800-a299-11eb-9bac-512ff2fdc30a.png)


@arkane2002 top merci j'ai pu rajouter quelques options qu'il me manquait ! 
Est-ce qu'il existe une option pour la conso d'hier affichée en grand haut à gauche, qui permettrait soit de cacher totalement l'info comme on peut faire avec le showPrice, soit d'afficher les deux possibilités d'affichage en même temps (avec le showPeakOffPeak false/true) ?

**Comment by ioannispelelis** [comment]
@Toukite  j'avais pensé au reboot déjà je l'ai fait hier.. Mais j'ai zappé le cache.. j'ai fait un CTRL+F5 sur le navigateur et en effet ca recharger sans le cache comme il faut. Merci
![image](https://user-images.githubusercontent.com/57101460/115537911-9c3ff580-a29b-11eb-8325-426cbf502639.png)

**Comment by ioannispelelis** [comment]
@Toukite  pour tes donnes A-1 qui sont vides. si je comprends bien le principe de ce compartif c'est de comparer toujours par rapport a la periode de l'année dernière (la semaine dernière VS la meme semaine 1 an avant, etc...) avais-tu un linky fonctionnel qui communiquait en 2020? Sinon c'est surement normal que les valeurs A-1 (annee dernière) soient vide
