### ISSUE TITLE
argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by delphiki** [saniho/apiEnedis#59]
![Capture d’écran de 2021-03-17 14-11-22](https://user-images.githubusercontent.com/303778/111473491-62735080-872b-11eb-8b36-ab6c6f613adb.png)

J'ai cette erreur depuis aujourd'hui, avec cette trace dans les logs : 

> 2021-03-17 14:12:51 WARNING (SyncWorker_15) [myEnedis] myEnedis ...XXXXXXXXXXXX update lancé, status precedent : False, lastCall :None
> 2021-03-17 14:12:51 WARNING (SyncWorker_15) [myEnedis] mise à jour effectuee
> 2021-03-17 14:12:54 WARNING (SyncWorker_15) [myEnedis] ------------------------------------------------------------
> 2021-03-17 14:12:54 WARNING (SyncWorker_15) [myEnedis] Erreur inconnue call ERROR argument of type 'bool' is not iterable
> 2021-03-17 14:12:54 WARNING (SyncWorker_15) [myEnedis] Erreur last answer argument of type 'bool' is not iterable
> 2021-03-17 14:12:54 WARNING (SyncWorker_15) [myEnedis] Erreur last call updateProductionYesterday
> 2021-03-17 14:12:54 WARNING (SyncWorker_15) [myEnedis] (<class 'TypeError'>, TypeError("argument of type 'bool' is not iterable"), <traceback object at 0x66df4188>)
> 2021-03-17 14:12:54 WARNING (SyncWorker_15) [myEnedis] LastMethodCall : updateProductionYesterday

J'ai un contrat sans heure creuse (et donc la checkbox décochée dans les options).

**Comment by Toukite** [comment]
J'ai la même erreur en v1.1.3.2 je n'ai pas lundi mardi
Contrat hp hc

PS: rien à voir mais tant que je suis là : la tendance n'a jamais fonctionné chez moi j'ai aussi 0% vs février et les mois précédents c'était pareil

**Comment by DarKOrange75** [comment]
idem

**Comment by delphiki** [comment]
> PS: rien à voir mais tant que je suis là et que je vois ce screen : la tendance n'a jamais fonctionné chez moi non plus j'ai aussi 0% vs février et les mois précédents c'était pareil

Pour ma part c'est logique, je n'ai mon linky que depuis cette année. :)

**Comment by arkane2002** [comment]
Même erreur aussi.

Le curl fonctionne parfaitement par contre.
Je n'ai pas noté de changement dans les données évident mais comme je n'ai pas pris le soin d'historiser les réponses curl j'ai pu passé à côté.

@saniho qu'en penses-tu ?

**Comment by saniho** [comment]
la nouvelle version compatible avec l'evolution de la gateway est disponible ( v1.1.4.0 )

**Comment by delphiki** [comment]
De mon côté c'est tout bon après la mise à jour vers la v1.1.4.0, merci !

**Comment by ullysse31** [comment]
bonjour

moi cela n'a rien changé

**Comment by delphiki** [comment]
> bonjour
> 
> moi cela n'a rien changé

Tu as bien restart HA ?

**Comment by ullysse31** [comment]
oui tout redemarré 
2 fois :-(

**Comment by ullysse31** [comment]
ca y est ca c'est mis a jour 
c'est bon 
![Captureoff](https://user-images.githubusercontent.com/78451240/111828323-6c43b200-88eb-11eb-80de-894c9e73aadc.PNG)

**Comment by ullysse31** [comment]
![Captureok](https://user-images.githubusercontent.com/78451240/111828394-88dfea00-88eb-11eb-82ba-3b60608b14b4.PNG)
