### ISSUE TITLE
Pas de données après reboot

### ISSUE THREAD

**Issue by arkane2002** [saniho/apiEnedis#60]
Bonjour,

Je rencontre un problème vraiment génant.
Je n'ai plus de données le matin lorsque j'accède au dashboard :
![2021-03-23 10_04_40-Aperçu - Home Assistant](https://user-images.githubusercontent.com/22443363/112121367-7998bf00-8bbf-11eb-992f-4469aa5d207c.png)
Le curl de enedisgateway fonctionne très bien.
Mais je n'ai aucune données.
Au début je devais attendre 11h pour avoir des données mais là il est 14h42 et je n'ai toujours rien.
Chose étrange maintenant le comparable avec février 2020 donne 0% alors qu'hier encore j'étais à -33%.

Analyse : 
au reboot, à 2h19 : 
`2021-03-23 02:19:42 ERROR (SyncWorker_2) [myEnedis] Error JSON : {"tag":"offline","error_code":504,"description":"Les API d'Enedis sont actuellement en maintenance (23h-3h)","alert_user":true,"enedis_return":false,"support":"https://discord.gg/DfVJZme"}`
=> Je vais donc modifier l'heure de reboot pour la fixer à 3h30 du matin.

à 3h19 : 
`2021-03-23 03:19:59 INFO (SyncWorker_11) [myEnedis] updateManagerSensor - done - 19879739429528`

Pas d'erreur dans les logs. et Dashboard toujours vierge.

Que faire ? quelle cause ?

**Comment by saniho** [comment]
peux-tu me dire quelle version tu as ?

**Comment by ullysse31** [comment]
j'ai pareil apres mise a jour 1.1.4.1

**Comment by teuf93** [comment]
Pareil chez moi....

**Comment by arkane2002** [comment]
> peux-tu me dire quelle version tu as ?

Version 1.1.4.1
Pas d'erreur particulière dans le log.
Mais l'impression que l'update ne se fait pas en fait après un reboot.

En moyenne je dois attendre 10h30 le matin (et un restart ha) pour avoir les données.

**Comment by arkane2002** [comment]
Je complète.
Il faut que je reboot HA pour que le composant récupère des informations.
Il y a donc une synchro qui ne se fait qu'au restart HA. Il faudrait exposer le service pour qu'on puisse le lancer à la demande. Je suis presque sur que ça résoudrai les problèmes liés au hard reboot du pi pour ma part qui se fait après minuit (pas le choix car les services enedis sont down de 23h à 3h et j'ai des services qui ne peuvent pas s'interrompre avant 23h).
@saniho tu peux nous donner quelques pistes pour la mise à jour du composant ?

merci

**Comment by saniho** [comment]
j'ai livrée une release(  1.1.4.3RC ) ...peux-tu me dire si c'est mieux ?
