### ISSUE TITLE
apienedis ne syncrhonise pas

### ISSUE THREAD

**Issue by ioannispelelis** [saniho/apiEnedis#62]
Bonjour,

Depuis quelques jours j'ai des erreurs avec l'apiEnedis et les derniers jours ne synchronisaient plus sur la carte
J'ai reboot la VM de HomeAssistant (pour d'autres raisons que ce soucis) et depuis je n'ai plus aucune données qui s'affichent sur la carte
![enedis](https://user-images.githubusercontent.com/57101460/112680683-fa7ce280-8e6d-11eb-870d-983a40cfda53.png)

Si je regarde les logs de HA il semblerait qu'il y ait une erreur sur le téléchargement de données du dernier jour (ceci depuis plusieurs jours donc)
![log](https://user-images.githubusercontent.com/57101460/112680806-1e402880-8e6e-11eb-8c40-de1fd294ce86.png)

Si je lance la commande curl de test en J-1 j'ai bien la même erreur qu'il n'y a pas de données pour hier
![curl j-1](https://user-images.githubusercontent.com/57101460/112681017-65c6b480-8e6e-11eb-99ee-916791716388.png)

Par contre si je lance la commande curl en j-2 la pas d'erreur.
![curl j-2](https://user-images.githubusercontent.com/57101460/112681244-b6d6a880-8e6e-11eb-822e-a36a3619a99c.png)

Du coup je comprends bien que à priori le dernier jour n'est pas disponible sur le serveur (bien qu'il s'affiche sur mon compte enedis)
Mais ce que je comprends pas c'est pourquoi vu que les jours précédents semblent bien être synchro sur le serveur, l'apienedis et donc la carte lovelace ne montre pas au moins les autres données des autres jours de la semaine et du mois?

Merci

**Comment by palmitoto** [comment]
Je constate la même chose.

**Comment by ioannispelelis** [comment]
Bon ce matin le résultat est différent les 2 derniers jours sont indispo mais la carte c'est au moins mise à jour pour les jours plus anciens.
Et j'ai une erreur sur la carte:  _ErrorLastCall
no measure found for this usage point (no_data_found-enedis_return_ko)_
![image](https://user-images.githubusercontent.com/57101460/112719947-fa2b2880-8efb-11eb-92fa-c43e32a0b38c.png)

**Comment by ullysse31** [comment]
Pareil pour moi 
![image](https://user-images.githubusercontent.com/78451240/112737440-f084dd80-8f5a-11eb-9b2b-2d700e393303.png)

**Comment by ioannispelelis** [comment]
Et ce matin ca a synchro touts les jours mais il reste une erreur sur la carte lovelace... bizarre
![image](https://user-images.githubusercontent.com/57101460/112746782-6caa1000-8fb1-11eb-898a-f5c05521ffa8.png)

**Comment by palmitoto** [comment]
Pour ma part, tout est rentré dans l'ordre. Plus d'erreur.

**Comment by Donokami** [comment]
Dans mon cas, je n'ai tjrs rien. L'api Gateway semble vraiment instable!

**Comment by m4dm4rtig4n** [comment]
Ce n'est pas l'api gateway, mais Enedis qui te renvoie les erreurs :/

**Comment by totoantibes** [comment]
Voici la réponse à la commande de test apres l'obtention d'un n'eme TOKEN sur la gateway enedis. Bizarre car cela fonctionnait il y a un mois. depuis je n'arrive pas 1a récuperer les données...

{"tag":"enedis_return_ko","error_code":"no_data_found","description":"no measure found for this usage point","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}

**Comment by saniho** [comment]
Peux-tu me dire si avec la derniere version, c'est mieux

**Comment by ioannispelelis** [comment]
J'ai l'impression que c'est un peu mieux. il me semble que la ou il a toujours du mal a syncro en ce moment c'est plus les weekend. je sais pas si c'est une coincidence ou genre une maintenance chez enedis?
Par contre maintenant il affiche une erreur différente de quota? c'est lié à quoi?
![image](https://user-images.githubusercontent.com/57101460/115291706-5e38b980-a155-11eb-89c1-6067e8266b25.png)

**Comment by totoantibes** [comment]
moi ca fait 2 mois que ca foire...

Voici le dernier LOG HA.

Logger: myEnedis
Source: custom_components/myEnedis/myEnedis.py:96
First occurred: 2:01:53 AM (114 occurrences)
Last logged: 1:09:38 PM

params : None
data : {"type": "consumption_load_curve", "usage_point_id": "25947177991470", "start": "2021-04-19", "end": "2021-04-20"}
Error JSON : {"tag":"enedis_return_ko","error_code":"no_data_found","description":"no measure found for this usage point","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}
data : {"type": "consumption_load_curve", "usage_point_id": "25947177991470", "start": "2021-04-13", "end": "2021-04-20"}
************************************************************




ce que je vois dans le détail de la carte: 
Version
1.1.4.3
VersionGit
1.1.4.3
VersionUpdateAvailable
false
TypeCompteur
consommation
ActivationDate
2017-11-10
LastUpdate
2021-04-20T13:10:28.534997
TimeLastCall
2021-04-20T13:10:28.534938
Yesterday
4860
Last week
36268
YesterdayLastYear
7541
YesterdayConsumptionMaxPower
2023
Day 1 HP
-1
Day 2 HP
-1
Day 3 HP
-1
Day 4 HP
-1
Day 5 HP
-1
Day 6 HP
-1
Day 7 HP
-1
Day 1 HC
-1
Day 2 HC
-1
Day 3 HC
-1
Day 4 HC
-1
Day 5 HC
-1
Day 6 HC
-1
Day 7 HC
-1
Dailyweek cost
-1, -1, -1, -1, -1, -1, -1
Dailyweek costHC
-1, -1, -1, -1, -1, -1, -1
Dailyweek HC
-1, -1, -1, -1, -1, -1, -1
Dailyweek
2021-04-19, 2021-04-18, 2021-04-17, 2021-04-16, 2021-04-15, 2021-04-14, 2021-04-13
Dailyweek costHP
-1, -1, -1, -1, -1, -1, -1
Dailyweek HP
-1, -1, -1, -1, -1, -1, -1
Day 1
-1
Day 2
-1
Day 3
-1
Day 4
-1
Day 5
-1
Day 6
-1
Day 7
-1
Daily
-1, -1, -1, -1, -1, -1, -1
Halfhourly
Offpeak hours
- - '03:04'
- '08:04'
- - '08:04'
- '13:34'
- - '13:34'
- '16:34'
Peak hours
0.000
Peak offpeak percent
0
Yesterday HC cost
0.000
Yesterday HP cost
0.000
Daily cost
0.00
Yesterday HC
0.000
Yesterday HP
0.000
Current week
4.860
Current week last year
7.396
Last month
194.294
Last month last year
216.945
Current month
106.634
Current month last year
123.556
Last year
2437.965
Current year
699.859
ErrorLastCall
ErrorLastCallInterne
Monthly evolution
-10.441
Current week evolution
-34.289
Current month evolution
-13.696
Yesterday evolution
-35.552
Subscribed power
6 kVA
Offpeak hours enedis
HC (3H04-8H04;13H34-16H34)

**Comment by palmitoto** [comment]
Moi c'est comme @ioannispelelis, depuis la mise à jour le code erreur a changé : 
![Capture d’écran 2021-04-21 à 10 09 05](https://user-images.githubusercontent.com/966556/115519868-e3bd8600-a289-11eb-8bd6-31506e357fb0.png)

**Comment by totoantibes** [comment]
toujours pas de prix/conso sur ma "card" 
![image](https://user-images.githubusercontent.com/30798304/116550459-16edbe00-a8f7-11eb-8b88-706edf378e9c.png)

**Comment by ullysse31** [comment]
pour moi  plus d'erreurs depuis quelques jours 
tout est OK 
![image](https://user-images.githubusercontent.com/78451240/116552578-7baa1800-a8f9-11eb-9234-a367b8510f62.png)
