### ISSUE TITLE
Faux positif 'no data found'

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#63]
![image](https://user-images.githubusercontent.com/42780622/114875515-a4141b80-9dfd-11eb-8759-1b8c73f961f3.png)
Bonjour,
Ce n'est pas très grave mais c'était pour signaler que j'avais ce message en permanence, même si les données remontent correctement
sensor v1.1.4.2
card v1.0.3.9

**Comment by saniho** [comment]
en effet, ceci est un faux positif generé par l'api Enedis :(
en attente de correction de leur part ... en espérant que cela vienneun jour
