### ISSUE TITLE
Question sur la tendance

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#64]
![image](https://user-images.githubusercontent.com/42780622/114875873-066d1c00-9dfe-11eb-9c0d-4231e2697584.png)
Bonjour,
Je ne comprends pas cet élément sur la card, qui a toujours été à 0 depuis plusieurs mois que j'utilise cette intégration.
Pouvez-vous m'expliquer ?
sensor v1.1.4.2
card v1.0.3.9
Merci d'avance !

**Comment by saniho** [comment]
La tendance, indique si ta consommation du mois précèdent était +/- importante que celle du même mois sur l'année précédente
ici mars 2021 est comparé à mars 2020

**Comment by saniho** [comment]
livré dans la derniere version ( mettre à jour sensor + card )
et ajouter dans la card ceci : 
```
showWeekRatio: true
showYesterdayRatio: true
```

**Comment by Toukite** [comment]
Merci !
Je n'avais pas vu l'année je pensais que c'était la comparaison par rapport au mois précédent d'où ma question !

Du coup j'ai fait les maj. Donc si je comprends bien il faut que seul 1 de ces 3 paramètres soit mis à true c'est ça ?
Par exemple : 
showMonthRatio: false
showWeekRatio: true
showYesterdayRatio: false
?
Ou on peut en afficher plusieurs ?
J'ai essayé diverses combinaisons mais aucun effet sur ma card (même après avoir vidé le cache) du coup je ne comprends pas trop et je ne trouve pas l'info ou screen dans la doc. Peux tu m'expliquer comment ca marche stp ?

**Comment by Toukite** [comment]
@saniho en fait après reboot l'affichage fonctionne, cependant j'ai un pb sur la récupération des données A-1:

![image](https://user-images.githubusercontent.com/42780622/115534078-b24bb700-a297-11eb-96fc-510fe10c6910.png)

Quand je survole avec la souris, je vois que les 4 valeurs utilisées pour comparer (Mois Précédent A-1 / Mois A-1 / Semaine A-1 / Hier A-1) valent toutes zéro, alors que les 4 valeurs courantes sont bien récupérées, mais du coup le delta affiche 0%
