### ISSUE TITLE
Ajouter une configuration permettant de cacher l'historique par rapport à l'année dernière

### ISSUE THREAD

**Issue by domo-home** [saniho/apiEnedis#65]
Bonjour, 
Je viens d'ajouter le composant et de m'inscrire sur le site Enedis. Donc pendant 1 an, je n'aurai pas de valeur par rapport à l'année dernière.
Serait il possible de rajouter un paramètre permettant de cacher cette partie ?
![image](https://user-images.githubusercontent.com/64208224/115003003-a5991e80-9ea5-11eb-8bf6-ae357fe60e0a.png)

Merci pour le travail effectué.

Pierre

**Comment by saniho** [comment]
sera ajouté dans la prochaine version de la card
showMonthRatio: false

https://github.com/saniho/content-card-linky

**Comment by saniho** [comment]
livré dans la derniere version
