### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by flouck** [saniho/apiEnedis#68]
Hi everyone,
Do you think it would be possible to keep this documentation and the Linky Lovelace card up to date?
I know you guys are doing tremendous work to make this the best feature ever but keeping the readme updated would help all the community to use your integration and your card properly.
It would also reduce the number of questions you receive all the time on the forum.
Thank you and keep up the great work!

**Comment by saniho** [comment]
try to do this ;)
But if you want ot participate, don't hesitate to made a pull requests ;)
