### ISSUE TITLE
Valeurs de consommation en cours incohérentes

### ISSUE THREAD

**Issue by sidwin9** [saniho/apiEnedis#69]
Bonjour,

Depuis la dernière mise à jour, mes valeurs de consommation en cours sont complètement incohérentes avec la consommation réelle et la consommation journalière. Des valeurs de l'ordre de 140 kWh en max sont annoncées alors que pratiquement rien n'est en fonction chez moi, 4 kWh en min. Les consommations journalière de l'ordre de  4 à 7 KWh sont annoncées et elles, sont réalistes.

**Comment by saniho** [comment]
pourriez-vous tester avec la version 1.2.0.0rc1, attention, la config se fait uniquement avec la configuration ( et plus le YAML...bien penser à le desactiver )

**Comment by sidwin9** [comment]
Bonjour,

Ca fonctionne avec les Bêtas versions mais je dois régulièrement redémarrer mon Home Assistant pour que les mise à jours des données se mettent à jour.

**Comment by saniho** [comment]
Peux-tu essayer la dernière version pour voir si c'est stable...ps bcp d erreur quota en ce moment chez enedis..
