### ISSUE TITLE
 Problème de date

### ISSUE THREAD

**Issue by akanegally** [saniho/apiEnedis#70]
Bonjour,

Tout d'abord merci pour votre contribution.

je viens d'intégrer le capteur avec la carte linky sur mon serveur domotique. 

J'ai un erreur au niveau de la requete envoyée à enedis au sujet de la date: 
Start date should be before end date. (Invalid_request-enedis_return_ko)
[Voir la capture d'écran](https://ibb.co/n77Qm37)

Il semlerait que je récupère tout de même des données.

Pour information, j'ai suivi l'installation par HACS.
Mise à part la configuration, tout s'est passé sans problème.

En effet, je n'avais pas de fichier sensors.yaml, j'ai donc directement ajouté la section suivante dans mon fichier configuration.yaml

sensor:
  - platform: myEnedis
    token: ***
    code: 19187698941870 
    hc_cout: 0.1384
    hp_cout: 0.1904
    heures_creuses: "[['00:30', '07:00'], ['10:00', '11:30']]"
    heuresCreusesON: true
    scan_interval: 3600

Cette section est repris de la documentation.

Y a t il quelque chose d'incorrecte ?

Cdt,

**Comment by saniho** [comment]
pourriez-vous tester avec la version 1.2.0.0rc1, attention, la config se fait uniquement avec la configuration ( et plus le YAML...bien penser à le desactiver )
