### ISSUE TITLE
Plus de mise à jour des données

### ISSUE THREAD

**Issue by sidwin9** [saniho/apiEnedis#71]
Bonjour,

Depuis 3 jours, je n'ai plus aucun affichages des données même après un redémarrage de Home Assistant.
![image](https://user-images.githubusercontent.com/45182426/117338685-25137f80-ae9f-11eb-93f6-323797af09cf.png)

**Comment by saniho** [comment]
pourriez-vous tester ave la version 1.2.0.0rc1, attenttion, la config se fait uniquement avec la configuration ( et plus le YAML...bien penser à le desactiver )

**Comment by sidwin9** [comment]
Bonjour,

Le test par ligne de commande Unix ne fonctionne pas également, voici le résultat 
{"tag":"enedis_return_ko","error_code":"no_data_found","description":"no measure found for this usage point","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}~ $

Le résultat est identique en créant un nouveau token.

**Comment by saniho** [comment]
avez-vous bien activé la remonté horaire ?

**Comment by sidwin9** [comment]
Bonjour,

L'autorisation de relevée des données horaires sur le site ENEDIS étant valide pendant 1 an, cette dernière était périmée. J'ai validé une nouvelle autorisation valide pour une nouvelle année et tout est rentré dans l'ordre.

Merci.
