### ISSUE TITLE
plus rien depuis mise a jour 1.2.0.1

### ISSUE THREAD

**Issue by ullysse31** [saniho/apiEnedis#74]
bonjour
je viens de mettre a jour en 1.2.0.1 et plus rien 
![image](https://user-images.githubusercontent.com/78451240/119682755-6ca87e00-be43-11eb-8fec-ede1d1f76188.png)

les sensors  , avec ronds rouge " restauré"
![image](https://user-images.githubusercontent.com/78451240/119682954-9497e180-be43-11eb-93ae-d4bcb3407c86.png)

![image](https://user-images.githubusercontent.com/78451240/119683481-f8baa580-be43-11eb-9314-40cf80f22950.png)

quelqu'un a le meme soucis?

**Comment by saniho** [comment]
Hello, as tu fait attention dans cette version la configuration doit se faire via l interface graphique et non via le yaml.

**Comment by ullysse31** [comment]
il faut enlever ce qu'il y a dans le YAML ?

**Comment by ullysse31** [comment]
j'ai enlevé ce qu'il y avait dans le yaml 
tout desinstallé
reinstallé , j'ai bien mon integration myenedis et mes 5 entités
![image](https://user-images.githubusercontent.com/78451240/119690989-7aadcd00-be4a-11eb-940e-6fb4a81af5eb.png)
mais 2 en indisponible

![image](https://user-images.githubusercontent.com/78451240/119690824-50f4a600-be4a-11eb-89d8-b6bacbdc4db9.png)
et 
![image](https://user-images.githubusercontent.com/78451240/119691128-9a44f580-be4a-11eb-8c3b-fc09aab45cbf.png)

**Comment by saniho** [comment]
il y a deux soucis, pour le premier
1/ il faudrait que tu supprimer la config dans yaml
2/ redemarrer ha
3/ supprimer les entité de myenedis
4/ redemarrer ha
5/ recreer ta config myenedis
6/ redemarrer
Pour le deuxième, c'est lié à enedis...à voir si après les actions ci-dessous, cela ne se produit plus.

**Comment by ullysse31** [comment]
alors j'ai effacé les lignes Myenedis dans le Yaml
redémarrage
suppression de l'integration , qui a supprimé les  entités 
redemarrage
re Hacs , installation depot,
dans intégration , remis la config 
( sans changer l'ancien token) 
redémarrage et  j'ai 2 entités indisponibles
![image](https://user-images.githubusercontent.com/78451240/119719146-b9eb1680-be68-11eb-9489-3b9b527931f2.png)

dans outil de développement j'ai ca 

![image](https://user-images.githubusercontent.com/78451240/119719481-19e1bd00-be69-11eb-89df-bea6f99cfdf5.png)

la carte  lovelace 
![image](https://user-images.githubusercontent.com/78451240/119719621-4b5a8880-be69-11eb-85ca-6be18fb9b008.png)

![image](https://user-images.githubusercontent.com/78451240/119719724-6cbb7480-be69-11eb-945a-0a9cad066c2c.png)

**Comment by ullysse31** [comment]
apres avoir supprimé "unaviable" dans outil de développement
j'ai ca 

![image](https://user-images.githubusercontent.com/78451240/119720651-890be100-be6a-11eb-9042-1f91dcea6b1d.png)
![image](https://user-images.githubusercontent.com/78451240/119720728-a0e36500-be6a-11eb-93a1-3499069fcd8c.png)
![image](https://user-images.githubusercontent.com/78451240/119720789-b48ecb80-be6a-11eb-9b19-bdaa6bb90c7a.png)

**Comment by ullysse31** [comment]
en changeant le token 

![image](https://user-images.githubusercontent.com/78451240/119729183-a776da00-be74-11eb-9a82-84fdcfba8438.png)

**Comment by saniho** [comment]
Hello, j'ai livré une nouvelle version peux-tu tester ?

**Comment by ullysse31** [comment]
bonjour,
oui je l'ai installé hier soir , et ca a marché direct !!! :-) impecable
