### ISSUE TITLE
Scan interval sans configuration yaml

### ISSUE THREAD

**Issue by Skuair** [saniho/apiEnedis#76]
Bonjour,
A ce que j'ai cru comprendre, depuis les dernières versions la configuration ne se fait plus via yaml mais directement dans l'écran de configuration de l'intégration.
Cependant, dans le yaml je pouvais paramétrer le scan interval (c'est surtout pour ça que j'avais rajouté des lignes dans le yaml).
Comment faire maintenant avec seulement la config via UI ?

Merci.

**Comment by saniho** [comment]
Dans la configuration il n'est plus possible de gerer la fréquence de mise a jour, ceci afin d'éviter que enedis ne soit "surchargé"

**Comment by Skuair** [comment]
Ok, du coup quelle est la fréquence de rafraîchissement définie en dur ?

Romain

**Comment by saniho** [comment]
Dans la prochaine version cela sera une fois par jour entre 10:00 et 10:30...... Sauf si enedis est hs et dans ce cas il y aura de nouvelles tentative ultérieurement.

**Comment by Skuair** [comment]
D'accord merci pour la précision.
