### ISSUE TITLE
No more sync

### ISSUE THREAD

**Issue by Kriss1670** [saniho/apiEnedis#77]
Error message stating that the limit of 10 requests per day has been reached. No more sync since that.
Moreover, on Enedis site, the authorization to tranfer data doesn't appear.

**Comment by ullysse31** [comment]
comme ca ?
![image](https://user-images.githubusercontent.com/78451240/122237746-dc98aa00-cebf-11eb-824d-6feba44bd8d0.png)

**Comment by Kriss1670** [comment]
Bonjour,

Je suis en déplacement jusqu’à samedi mais ça ressemble à ça. J’ai souvent les données des jours précédents, mais je perds souvent les données du jour avec un message d’erreur rouge en bas proche de celui-ci.
Dès que je rentre, je vous confirme avec une ou des captures d’écran.

Merci

De : ullysse31
Envoyé le :mercredi 16 juin 2021 16:28
À : saniho/apiEnedis
Cc : Kriss1670; Author
Objet :Re: [saniho/apiEnedis] No more sync (#77)

comme ca ?

**Comment by saniho** [comment]
Une solution devrait arriver d'ici peu.....

**Comment by Kriss1670** [comment]
Super !
J’ai eu Enedis au téléphone suite à un message un peu « colère ». Ils m’ont étonné par leur intérêt et leur conscience du sujet.
Merci pour votre travail.

**Comment by saniho** [comment]
Voilà, la derniere rc est arrivée(1.3.0.1 ), elle permet de gere le nombre maximal de call, et une mise en cache.
Attention, il vous faudra environ 24h avant que cela fonctionne correctement( le temps de la remise à zero du compteur d'appel .. )

**Comment by Kriss1670** [comment]
Bonsoir,

J’ai la version 1.2.0.4 sur GitHub, pas la 1.3.0.1. Je vais surveiller.
Sinon, étant débutant sur HA, y-a-t-il un moyen de mettre à jour l’intégration ou faut-il supprimer l’ancienne et réinstaller ?

Merci beaucoup.

De : saniho
Envoyé le :lundi 21 juin 2021 21:34
À : saniho/apiEnedis
Cc : Kriss1670; Author
Objet :Re: [saniho/apiEnedis] No more sync (#77)

Voilà, la derniere rc est arrivée(1.3.0.1 ), elle permet de gere le nombre maximal de call, et une mise en cache.
Attention, il vous faudra environ 24h avant que cela fonctionne correctement( le temps de la remise à zero du compteur d'appel .. )

**Comment by saniho** [comment]
Si tu n'avais pas mis la première fois l'accès aux versions beta alors il te faut désinstaller et ensuite réinstaller en activant acces aux versions beta...comme cela la prochaine fois tu pourras faire lupdat e directement...

**Comment by Kriss1670** [comment]
Merci !

De : saniho
Envoyé le :mardi 22 juin 2021 18:33
À : saniho/apiEnedis
Cc : Kriss1670; Author
Objet :Re: [saniho/apiEnedis] No more sync (#77)

Si tu n'avais pas mis la première fois l'accès aux versions beta alors il te faut désinstaller et ensuite réinstaller en activant acces aux versions beta...comme cela la prochaine fois tu pourras faire lupdat e directement...
