### ISSUE TITLE
Persistence des données

### ISSUE THREAD

**Issue by Nardol** [saniho/apiEnedis#78]
Hello,

﻿Vu la limite journalière imposée par les restrictions d'Enedis, la persistence des donées devient vraiment nécessaire.

Un exemple : dans l'après-midi, l'intégration Nest m'oblige à redemander un token, ce que je n'arrive pas à faire sans avoir à redémarrer HA pour avoir la notification et le bouton reconfigurer.
Du coup je valide le token et là, HACS me trouve une mise à jour d'intégration.
Du coup, encore redémarrage.
Conséquence : j'ai atteint la limite de consultation de l'API et donc, plus aucune donnée dispo.

Y a-t-il une solution à l'étude ?
Aucune possibilité de stocker les données localement d'une façon ou d'une autre ?

**Comment by saniho** [comment]
Bonjour une solution est en cours de dev et ne devrait pas tarder a sortir...

**Comment by saniho** [comment]
Voilà, la derniere rc est arrivée(1.3.0.1 ), elle permet de gere le nombre maximal de call, et une mise en cache.
Attention, il vous faudra environ 24h avant que cela fonctionne correctement( le temps de la remise à zero du compteur d'appel .. )
