### ISSUE TITLE
Error longueur pdl avec 2 pdl

### ISSUE THREAD

**Issue by pbranly** [saniho/apiEnedis#79]
Lapi envoi une demande avec mes 2 pdl xxxxxxxxx, yyyyyyyyy
Enedis refuse et l’accès est ensuite bloqué

**Comment by saniho** [comment]
Hello, astu bien defini deux entrées dans la config, j ai l'impression que tu aurais mis les deux dans le champ pdl...

**Comment by pbranly** [comment]
Bonjour
Non j’ai bien 2 intégrations différentes
Je viens de revérifier 
Depuis maintenant plus d’une semaine je n’ai plus de données
Chaque compteur est en erreur « plus de 14 caractères ou/et plus de 10 demandes des tôt les matin.
Madmartigan a décelé le pb de double envoi dans ses traces

**Comment by saniho** [comment]
Hello
Peux-tu tester avec la dernière rc et me tenir informé
Attention attendre 24h avant de voir si ok ou non.

**Comment by pbranly** [comment]
Yep, c’est installé depuis ce matin. Je te dis demain si ça refonctionne 
Philippe

**Comment by saniho** [comment]
ok avec derniere version : 1.3.1.6
