### ISSUE TITLE
Mise à jour 1.2.0.4 dispo mais impossible de mettre à jour depuis HA

### ISSUE THREAD

**Issue by ankorez** [saniho/apiEnedis#80]
Hello,

Top cette intégration merci beaucoup 👍 
Je suis en 1.2.0.3 tout fonctionne correctement mais j'ai depuis une dizaine de jour une notification pour installer la version 1.2.0.4 avant je pouvais mettre à jour par l'interface web il me semble, ce n'est plus possible ?

merci de votre aide

**Comment by ullysse31** [comment]
salut 
tu vas dans HACS , reinstaller, et il y a la version 1.2.0.4
mais moi ca bug 

![image](https://user-images.githubusercontent.com/78451240/122667675-48c32880-d1b4-11eb-9558-bd03770c4896.png)

**Comment by ankorez** [comment]
Hello @ullysse31 
merci pour ton retour mais je n'ai pas d'option réinstaller :(
Quand je vais dans config/integrations j'ai 
![image](https://user-images.githubusercontent.com/56384118/122669826-5af69400-d1bf-11eb-9d0c-e45b574cddd0.png)

Sinon pour ton message d'erreur il va disparaitre demain :)

**Comment by ullysse31** [comment]
re
c'est pas dans les integrations  ou tu peux reinstaller 
mais dans HACS

![image](https://user-images.githubusercontent.com/78451240/122669935-bf195800-d1bf-11eb-9432-efac62e7669b.png)

**Comment by ankorez** [comment]
ah d'accord !
merci pour ton aide du coup le dépôt avait disparu !!!! je ne le voyais pas dans HACS 
je l'ai remis c'est tout bon merci @ullysse31

**Comment by ullysse31** [comment]
coool ;-)
