### ISSUE TITLE
Erreur 500-limit_reached

### ISSUE THREAD

**Issue by bbo76** [saniho/apiEnedis#81]
Bonjour,
Depuis quelques temps j'ai cette erreur sur la card, j'ai cherché ou je pouvais modifier ce quota mais je le trouve nulle part dans la config de l'intégration.
![image](https://user-images.githubusercontent.com/20109987/123269358-307a4300-d4ff-11eb-8fc5-04c8e593e1ca.png)

**Comment by Nadios-Vistos** [comment]
Même soucis sur ma config. Pourtant je n'ai rien modifié.

**Comment by saniho** [comment]
En effet,  le quota à été mis en place, car enedis trouve qu'on les intereroge de trop ;)
Peux-tu tester avec la derniere rc, et me dire si c'est mieux( attention, attendre 24h, avant que cela soit totalement fonctionnel )

**Comment by DarKOrange75** [comment]
Same issue… where can I fix that ?

**Comment by mdeweerd** [comment]
The daily limit should be 50 now.

In practice every Linky requires about 25 requests each day.

'apiEnedis' has been updated since 24 Jun 2021 to improve the handling of failing requests.
Normally things should return to normal the next day.

You can examine the home-assistant.log to get more information about requests that were made and their results and share this in a new Issue.

**Comment by warlordattack** [comment]
i have 50 limit reached error, how to fix it please ?

**Comment by mdeweerd** [comment]
If the credentials are valid, waiting 1 day should be ok.

Note that the limit is 50 for your credentials in total.

There could be another reason, you may find hints in the log.

How many requests did you find in your log?  If you find 50 for a given day, then you hit the limit.  If not, the gateway may be at fault as well.  This often goes away after one day.

If things persist, you should provide more information from the logs.

**Comment by warlordattack** [comment]
is there some variable to set, then it will not make more calls then the limit ?
where is the log please ?

**Comment by mdeweerd** [comment]
The log is 'home-assistant.log' and this is in the config directory.
There is a 'myEnedis' directory in the custom component directory (apiEnedis/myEnedis) where each meter has a subdirectory and in there you can find the results of the API calls.

Each meter requires 18 API calls per day - so this allows for maximum 2 meters per day with a margin of 14 calls.

The number of calls is internally limited to 50 per day already to avoid stressing the gateway more than it already is.

On my end, yesterday I got quite a few timeouts reported by the gateway and stayed under the limit.  However even calls with timeouts count towards the total.

I guess that you had quite some timeouts too, so you may have exceeded the total.
