### ISSUE TITLE
Gestion des logs (error/warn/info)

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#82]
Bonjour,

Petit souci pas bien grave, l'intégration fonctionne bien quand Enedis est up, mais par contre la gestion des niveaux de logs pourrait être améliorée. 

Je surveille régulièrement les logs HA, et même quand tout va bien j'ai 80% des messages qui sont liés à cette intégration, cf screenshot ci-dessous:

![image](https://user-images.githubusercontent.com/42780622/125282922-2dad8980-e318-11eb-9725-81281fd95cac.png)

Est-il prévu d’améliorer ceci ?

**Comment by saniho** [comment]
dans la derniere version( 1.3.1.0 ), cela devrait etre mieux...juste encore quelques un  au cas ou un debug necessaire
