### ISSUE TITLE
Détection de nouvelle version

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#83]
Bonjour,

Un petit bug trouvé sur la détection de version: actuellement en 1.3.0.10, l'outil considère que 1.3.0.6 est supérieur (à priori il ne fallait pas dépasser 10 :) !)

![image](https://user-images.githubusercontent.com/42780622/125283490-c217ec00-e318-11eb-8fad-5f9bd859bfd4.png)

![image](https://user-images.githubusercontent.com/42780622/125283428-b62c2a00-e318-11eb-8d15-aae9688324b2.png)

**Comment by gerardsamara** [comment]
Meme chose chez moi avec la dernière version 1.3.0.10

**Comment by saniho** [comment]
en effet, j'ai "réglé" le soucis en passant à la version 1.3.1.0
je verrais plus tard mieux le gerer

**Comment by saniho** [comment]
pb réglé avec la derniere rc : 1.3.1.10
