### ISSUE TITLE
Conso HP / HC différente d'Enedis

### ISSUE THREAD

**Issue by Toukite** [saniho/apiEnedis#85]
Bonjour,

Je me sers de cette intégration (v1.3.1.6) pour insérer les données quotidiennement dans une table custo. Cela me permet par la suite d'effectuer des calculs pour reproduire la facture mensuelle réelle.
Cependant, je me suis rendu compte que les données remontées par l'intégration ne sont pas totalement en phase avec ce que remonte Enedis. 

Exemple pour cette semaine:
**Intégration HA:**
Day 1 | 20/07/2021 |  HP 6647 | HC 4667 | TOTAL 11.31
Day 2 | 19/07/2021 |  HP 6082 | HC 4835 | TOTAL 10.92
Day 3 | 18/07/2021 |  HP 6309 | HC 6633 | TOTAL 12.94
Day 4 | 17/07/2021 |  HP 7927 | HC 12104 | TOTAL 20.03
Day 5 | 16/07/2021 |  HP 10534 | HC 8336 | TOTAL 18.87
Day 6 | 15/07/2021 |  HP 10350 | HC 14794 | TOTAL 25.14
Day 7 | 14/07/2021 |  HP 10066 | HC 10449 | TOTAL 20.52

**Export csv directement depuis l'espace client Enedis:**
Day 1 | je n'ai pas les infos
Day 2 | 19/07/2021 | HP 5897 | HC 5020 | TOTAL 10,92
Day 3 | 18/07/2021 | HP 5968 | HC 6974 | TOTAL 12,94
Day 4 | 17/07/2021 | HP 7016 | HC 13015 | TOTAL 20,03
Day 5 | 16/07/2021 | HP 10164 | HC 8706 | TOTAL 18,87
Day 6 | 15/07/2021 | HP 10510 | HC 14634 | TOTAL  25,14
Day 7 | 14/07/2021 | HP 10071 | HC 10444 | TOTAL 20,52

La conso totale journalière est OK, mais la conso HP/HC est en écart.

Mes heures creuses sont la nuit de 02h26 à 07h56, puis en journée de 12h56 à 15h26

Savez-vous d'où ça peut venir ?
Merci d'avance !

**Comment by saniho** [comment]
Hello, en effet, c'est "normal", Enedis ne donne pas par minutes l'information mais selon un créneau, exemple toutes les 20 minutes, donc si ton mode change à 02:26, tu as 4 minutes qui sont en HC, mais moi, je n'ai la consommation que de 02:20 à 02:30 .. don impossible à découper :(
j'ai malheureusement pas de solution pour toi ...

**Comment by Toukite** [comment]
Ok merci pour les explications

Pour mieux comprendre, s'agît-il de l'api /v4/metering_data/consumption_load_curve ? Si oui, ne pourrait-on pas l'appeler avec interval_length=PT01M afin de gérer ce cas ? 
Je connais peu de personnes qui ont des heures HP/HC qui tombent juste avec l'arrivée du linky, mais peut être que peu de personnes ont besoin de ce niveau de précision je ne sais pas...

Autre piste mais moins précise : ramener à la minute via calcul (si enedis te donne 100 de conso sur 10min, considérer que ça fait 10 de conso sur 1 minute)

PS: J'ai des compétences dev, je serais prêt à mettre la main à la patte mais je n'ai jamais travaillé sur ce type de projet (github / open source / intégration HA), il faudrait que je vois comment monter un env de dev etc pour contribuer et proposer des merge request ^^ (enfin il faudrait aussi que ça t'intéresse)

**Comment by saniho** [comment]
malheureusement le pas PTxxM n'est pas un argument de la fonction, mais un élément du retour pour indiquer la valeur retour.
Si tu veux participer c'est avec plaisir.
Le plus simple install pycharm, et récupére mon projet via un git clone, et ensuite tu fais une branche, tes modifications, ton test unitaires et tu demande sla merge request ;)
