### ISSUE TITLE
Support https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics pour le dashboard Energie de Home Assistant

### ISSUE THREAD

**Issue by vlebourl** [saniho/apiEnedis#86]
Home Assistant vient de publier une mise à jour avec un nouveau panneau Energie qui nécessite les statistiques à long terme.
Voici la page d'aide dédiée : https://www.home-assistant.io/more-info/statistics/

**Comment by Minims** [comment]
More information here : https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics.

Not the subject, but can we add the Enedis logo to this integration too ? :-)

**Comment by aardjoun** [comment]
Any updates here ?

**Comment by saniho** [comment]
hello, I have tried, but not work, perhaps I don't understand the implementation, if somebody have any idea, don't hesitate to contact me...

**Comment by aardjoun** [comment]
https://github.com/home-assistant/core/blob/d4864f575075aa68d3a6106a10114ab3c586201a/homeassistant/components/atome/sensor.py
Maybe look at the total energy linky official component and look at the device_class_energy const. Tks

**Comment by MaxWaldorf** [comment]
Hi

Interested as well. Any updates?

**Comment by silversmarty** [comment]
Same here, it would be awesome!

**Comment by saniho** [comment]
no solution found, Energy is a real time measure, but myEnedis get data in asynchronous.....
