### ISSUE TITLE
L'intégration myENEDIS  incompatible avec la fonction Energy introduite en HA 2021.8

### ISSUE THREAD

**Issue by gerardsamara** [saniho/apiEnedis#87]
Bonjour ,

cette nouvelle fonction a été introduite dans la version 2021.8  , et est à configurer pour utiliser cette fonction ( menu configuration -> Energy ) 

![Capture config energy](https://user-images.githubusercontent.com/69084518/129169343-47fd0ba9-4031-43d2-a495-76a7ff28afe9.JPG)

Mais les sensors de consommationmyEnedis  ne sont pas visibles dans liste déroulante concernée

![Capture energy config](https://user-images.githubusercontent.com/69084518/129169164-3e796a52-6a3b-4816-a578-a480531a103f.JPG)

Une évolution de l'intégration "myEnedis" est nécéssaire pour etre compatible avec cette nouvelle fonction Energy
Merci d'avance

**Comment by Crocmagnon** [comment]
Dupliqué de https://github.com/saniho/apiEnedis/issues/86

**Comment by saniho** [comment]
en effet, et à ce jour, aucune solution trouvée, car la fonction Energy est une remonté temps reel, sauf que là, le plugin est sur du desynchro ....
