### ISSUE TITLE
Prix au mois

### ISSUE THREAD

**Issue by kweebix** [saniho/apiEnedis#9]
Bonjour est-il possible de rajouter une option pour avec le calcul de la sommes total sur 1 mois ou par semaine ?

**Comment by saniho** [comment]
bonsoir, dans la derniere version v1.1.1.0, un nouveau sensor contient maintenant le prix de la veille

![image](https://user-images.githubusercontent.com/52693545/103946489-ef4fcb80-5136-11eb-9efb-703ec168b61c.png)
