### ISSUE TITLE
Consommation d'hier

### ISSUE THREAD

**Issue by landaisbenj** [saniho/apiEnedis#92]
Je ne sais pas si c'est normal, mais je n'ai pas ma consommation du jour (je pense que oui car je n'ai jamais entendu parlé de la consommation en cours sur l'api enedis).

Du coup je me pose des questions sur les ratios :
![image](https://user-images.githubusercontent.com/32144431/139468460-768fd65c-586a-4ca9-9730-d48290f4e925.png)

Je suppose qu'il ne faudrait pas parler de ratio par rapport à la consommation d'hier, vu qu'il s'agit deja de la consommation d'hier...

Je pense que la carte devrait etre pensé comme un indicateur de la consommation d'hier (et non pas en cours), et du coup d'un ration par rapport à la consommation de la veille...

**Comment by silversmarty** [comment]
Effectivement, je trouve que ce point n'est pas très clair non plus... :-)

**Comment by saniho** [comment]
en effet, le terme n'est peut-etre pas le meilleur, quand on parle de % par rapport à hier, il faut considéré par exemple que le 24% est une comparaison entre le 18/11/2021 et le 18/11/2020
si vous avez une meilleur proposition ... je suis à l'écoute

**Comment by landaisbenj** [comment]
A oui comme à gauche ratio par rapport à 2020. Ok je comprend mieux alors. Est-ce pareil pour le ratio semaine ?? C’est intéressant pour la réflexion. Peut-être dans ce cas qu’on pourrais plutôt exprimer : consommation sur la journée par rapport à l’année dernière. Quelque chose genre « ratio N-1 journalier » « ratio N-1 semaine » etc. 

D’ailleurs ça soulève 2 questions, comment ça se passe un 29 février ? Et la semaine c’est glissant ou c’est semaine complète ?

**Comment by silversmarty** [comment]
Oui, ou ratio j-1/8 vs j-9/15 pour une semaine glissante, par exemple. 
Dans tous les cas, quelle que soit la mention, je pense que c'est important de détailler la façon de calculer dans la documentation

**Comment by saniho** [comment]
@landaisbenj  pour le 29 fevrier, et bien pas de conparaison ;)
pour la semaine, c'est du glissant, exemple si tu es jeudi, on compare du lundi au mercredi sur année N et année N-1
@silversmarty  : n'hésite pas à rajouter ta page dans la documentation( fichier readme.md ) et de proposer une merge ensuite
