### ISSUE TITLE
Niveau de logs

### ISSUE THREAD

**Issue by silversmarty** [saniho/apiEnedis#94]
Hello,

tout d'abord, merci pour cette fantastique intégration ! 

J'ai une requête à proposer : pouvoir gérer le niveau de logs dans l'interface. En l'état, et alors que l'intégration semble marcher parfaitement chez moi, je me retrouve avec une grande quantité de lignes dans le Journal de HA qui sont dues à l'intégration API Enedis :
![image](https://user-images.githubusercontent.com/17980711/142605080-18dc7e2e-d68a-4a91-9a07-f3c6b13fd440.png)

Du coup, cela rend terriblement compliqué la lecture des autres logs (aucune intégration n'est aussi verbeuse) alors que les informations affichées ne font que "rendre compte" de ce qui se passe (pas d'action à entreprendre pour améliorer les choses côté utilisateur). 

Serait-il possible de régler le niveau de logs que l'on désire avoir ? Dans certaines intégrations (modules complémentaires), les logs sont séparés dans une autre interface, ce qui rend la chose beaucoup plus compréhensible...

Merci
Paul

**Comment by saniho** [comment]
bonsoir, le niveu de log par application se règle dans le fichier configuration.yaml avec la clef logger
vous devriez arriver à gerer le niveau que vous souhaitez via cette option.

**Comment by Toukite** [comment]
Bonjour,

De mon côté j'ai testé ceci:

```
logger:
  default: info
  logs:
    custom_components.myEnedis: warn
```

Mais ça ne fonctionne pas, j'ai toujours les énormes pavés INFO de myEnedis dans les logs :(
Si quelqu'un trouve la bonne config à mettre, je suis intéressé !
