### ISSUE TITLE
Can’t add sensor to HA Energy

### ISSUE THREAD

**Issue by Dominik-1980** [saniho/apiEnedis#96]
Hello.

I have installed this Integration together with the Lovelace Card. It works great, but I can't add the sensor to Home Assistant Energy, I think because Long-term Statistics is not correctly implemented in your Integration.

Please have a look at 

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by saniho** [comment]
I have try to do this, but don"t find the way, espcially, because myEnedis is asynchronous data...
If you seen something else let me know

**Comment by Dominik-1980** [comment]
Could this help?

They have to have the right unit (be a measure of Wh or kWh), device_class: energy and state_class:measurement

**Comment by Dominik-1980** [comment]
![image](https://user-images.githubusercontent.com/32244806/142942111-dfe46800-6601-48fc-8179-d2db148c6be6.jpeg)

Can we add "device_class: energy" to this sensor?
Or create a sensor in the configuration.yaml with the right attributes with the value of this one?

**Comment by mdeweerd** [comment]
I have done something for gazpar for that, but did not try to port it to the enedis sensor:
https://community.home-assistant.io/t/ha-requires-m3-for-gas-i-converted-daily-kwh-reports-to-total-increasing-m/343728

That basically:
- Creates a counter that is used to keep the total.  The initial value could be Linky's value when putting this in service.
- The counter is then transformed in a sensor (using a platform: template).
- These sensors are then assigned the right classes (using the customization feature).
- And finaly, there is the automation that adds the daily consumption to the counter intially created at a fixed time every day.

**Comment by saniho** [comment]
j'ai en effet reussi à faire une intégration, pour le moment ce n'est que à la journée... vous pouvez la tester de votre coté avec la version en pre release : 1.3.2.0

**Comment by BadGones0l** [comment]
Bonjour, 

Je confirme cela fonctionne par contre je n'ai pas la consommation journalier mais la consommation total

![image](https://user-images.githubusercontent.com/66170163/145583189-e956b042-3ce2-4ee3-a9cc-89100da6e99a.png)

Est-il possible de corriger cela ?

**Comment by mdeweerd** [comment]
Bonjour
Maintenant que vous avez l'index, vous ajoutez cela comme source d'énergie gas (http://homeassistant.local:8123/config/energy) et la consommation apparaîtra dans l'historique comme consommation journalière (/par semaine/par mois/par an).

La consommation journalière apparaît également comme une propriété de l'état (aller dans développeur, puis regardez sensor.grdf_consommation_gaz).
