### ISSUE TITLE
Erreur meter_reading depuis plusieurs jours

### ISSUE THREAD

**Issue by Skuair** [saniho/apiEnedis#98]
Bonjour,

Depuis le 22/11, j'ai l'erreur 'meter_reading' qui est affichée dans les attributs, et plus de consommation loguée. Pourtant l'attribut timeLastCall est bien modifié tous les jours donc j'en conclus que je reçoit l'erreur à chaque appel depuis 10 jours.

Sur le forum hacf j'avais vu passer un soucis avec la passerelle mais est-ce toujours le cas ou c'est de mon côté le soucis ?
Merci.

**Comment by moriss1919** [comment]
bonjour
dans le meme cas avec l'erreur : no measure found for this usage point (no_data_found-enedis_return_ko)
pourtant tout était fonctionnel idem aux alentours du 22/11

**Comment by Dominik-1980** [comment]
La meme chose ici. Depuis le 22/11.
Je crois c'est un fault de la API Enedis...

**Comment by saniho** [comment]
hello, le soucis vient de la gateway entre apienedis et enedis ... la personne en charge de cette partie travaille dessus pour résoudre le soucis. En faisant un reboot de HA, vous changer d'heure de synchro et cela peut soulager la gateway

**Comment by Skuair** [comment]
Bonjour, je reviens sur ce soucis car en fait depuis l'ouverture de cette fiche, je n'ai jamais eu de nouveau de données. Je suis toujours en erreur meter_reading.
Home assistant redémarre assez souvent avec les mises à jour donc d'après ta réponse, ça aurait dû un jour se remettre mais non.
Il y a toujours un soucis sur la gateway ou alors c'est moi qui doit faire un truc spécial ?

**Comment by saniho** [comment]
peux-tu essayer avec cette version "beta" : 1.3.2.6

**Comment by Skuair** [comment]
Je viens à l'instant de mettre à jour avec la 1.3.2.7, mais toujours
meter_reading.
TimeLastCall bien positionné à maintenant.

**Comment by saniho** [comment]
peux-tu regarder dans le log de homeassitant, si il y aurait pas un traceback "interessant"

**Comment by Skuair** [comment]
Alors effectivement, j'avais pas pensé à vérifier les logs (j'ai
volontairement mis une severity à fatal pour ne pas avoir de logs sur du
polling sur des appareils éteins la nuit....)

Mais en réactivant la severity error j'ai donc :

"error":"token_refresh_401","description":"Une erreur est survenue,
merci de renouveller vos consentements."

Ça semble donc s'expliquer je vais renouveler et je te dirai.
Par contre peut-être voir pourquoi l'erreur affichée dans l'entity n'est
pas la même.

Romain

**Comment by Teka101** [comment]
Bonjour,

J'ai le même soucis, et je viens de découvrir que sur https://mon-compte-particulier.enedis.fr/ ma collecté des données n'était plus activé... je viens de la réactiver et je suppose que d'ici demain j'aurai de nouveau un HA fonctionnel

**Comment by Skuair** [comment]
Question un peu bête mais comment je modifie le token dans HA après un renouvellement de consentements ? Faut désinstaller et réinstaller l'intégration ?

**Comment by Teka101** [comment]
> Question un peu bête mais comment je modifie le token dans HA après un renouvellement de consentements ? Faut désinstaller et réinstaller l'intégration ?

Il faut aller dans la page des intégration de HA et là, il y a un bouton pour configurer et changer la token

**Comment by Skuair** [comment]
Merci, j'étais resté dans la page HACS pour configurer, j'avais zappé que l'intégration était dans le menu "intégration"..
En tout cas, c'est bon j'ai des données qui sont arrivées, merci.

Petite question technique avant de clôturer, quel est le namespace de cette intégration pour changer le niveau de log ? j'ai essayé custom_components.myEnedis ou custom_components.apiEnedis, mais c'est pas pris en compte, je trouve ça où ?

**Comment by Teka101** [comment]
Aucune idée pour le log :)

**Comment by saniho** [comment]
il faut indiquer ceci : 
```
logger:
  default: error
  logs:
    custom_components.myEnedis: error
    myEnedis: error
```

**Comment by Skuair** [comment]
Merci.
